#!/bin/sh
QMAILDUID=`id -u qmaild`
NOFILESGID=`id -g qmaild`
MAXSMTPD=`cat /var/qmail/control/concurrencyincoming`
BLACKLIST=`cat /var/qmail/control/blacklists`
SMTPD="/var/qmail/bin/qmail-smtpd"
TCP_CDB="/etc/tcprules.d/tcp.smtp.cdb"
RBLSMTPD="/usr/bin/rblsmtpd"
HOSTNAME=`hostname`
VCHKPW="/home/vpopmail/bin/vchkpw"

IP=0
PORT=25

RECORDIO="/usr/bin/recordio"

export SMTPAUTH="" \
    SSL=0 \
    REQUIRE_AUTH=0 \
    FORCE_TLS=0 \
    DENY_TLS=0 \
    AUTH=1 \
    REQUIRE_AUTH=0 \
    ALLOW_INSECURE_AUTH=1

exec /usr/bin/softlimit -m 64000000 \
    /usr/bin/tcpserver -v -R -H -l $HOSTNAME -x $TCP_CDB -c "$MAXSMTPD" \
    -u "$QMAILDUID" -g "$NOFILESGID" $IP $PORT \
    $RBLSMTPD $BLACKLIST $SMTPD $VCHKPW /bin/true 2>&1
