#!/bin/sh
QMAILDUID=`id -u qmaild`
NOFILESGID=`id -g qmaild`
MAXSMTPD=`cat /var/qmail/control/concurrencyincoming`
SMTPD="/var/qmail/bin/qmail-smtpd"
TCP_CDB="/etc/tcprules.d/tcp.smtp.cdb"
HOSTNAME=`hostname`
VCHKPW="/home/vpopmail/bin/vchkpw"

RECORDIO="/usr/bin/recordio"

IP=0
PORT=587

export SMTPAUTH="!" \
    SSL=0 \
    REQUIRE_AUTH=0 \
    FORCE_TLS=1 \
    DENY_TLS=0 \
    AUTH=1 \
    REQUIRE_AUTH=0 \
    ALLOW_INSECURE_AUTH=0

exec /usr/bin/softlimit -m 64000000 \
    /usr/bin/tcpserver -v -R -H -l $HOSTNAME -x $TCP_CDB -c "$MAXSMTPD" \
    -u "$QMAILDUID" -g "$NOFILESGID" $IP $PORT \
    $SMTPD $VCHKPW /bin/true 2>&1
