#!/bin/sh

if [ -f ./custom.run ] ; then
	. ./custom.run
	return $?
fi

rm -rf ./env/*;

cat /etc/courier/authlib/authdaemonrc | /usr/bin/envconv

exec /usr/bin/envdir ./env/ \
	/usr/libexec/courier-authlib/authdaemond 2>&1
