#!/bin/sh

if [ -f ./custom.run ] ; then
	. ./custom.run
	return $?
fi

#LOGSIZE=`cat /var/qmail/control/logsize`
#LOGCOUNT=`cat /var/qmail/control/logcount`

#exec /usr/bin/setuidgid qmaill \
#	/usr/bin/multilog t s$LOGSIZE n$LOGCOUNT /var/log/qmail/smtps 2>&1

exec /usr/bin/setuidgid qmaill \
	/var/qmail/bin/splogger smtps 2>&1
