<?php
	// MR -- TODO!
?>

<script type="text/javascript" src="/theme/menu/office/js/jscookmenu.js"></script>
<link rel="stylesheet" href="/theme/menu/office/css/style.css" type="text/css" />
<script type="text/javascript" src="/theme/menu/office/js/script.js">
</script>

<div id="wb_MenuBar1" style="margin:0;padding:0;text-align:left;z-index:2000;">
	<div id="MenuIDMenuBar1">
		<ul>
			<li>
				<span>
				</span>
				<a href="/display.php?frm_action=show" target="_self">Home</a>
			</li>
			<li>
				<span>
				</span>
				<span>
					Administration
				</span>
				<ul>
					<li>
						<span>
						</span>
						<span>
							List
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									<a href="/display.php?frm_action=list&frm_o_cname=all_domain" target="_self">All Domains</a>
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									<a href="/display.php?frm_action=list&frm_o_cname=actionlog" target="_self">Action&nbsp;Log</a>
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Server
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Client
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Resources&nbsp;Plan
								</span>
							</li>
						</ul>
					</li>
					<li>
						<span>
						</span>
						<span>
							Support
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									Help&nbsp;Desk
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Messages
								</span>
							</li>
						</ul>
					</li>
					<li>
						<span>
						</span>
						<span>
							Update
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									Password
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Information
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Update&nbsp;Home
								</span>
							</li>
						</ul>
					</li>
					<li>
						<span>
						</span>
						<span>
							Config
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									Custom&nbsp;Buttons
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Reverse&nbsp;Dns
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Dns&nbsp;Config
								</span>
							</li>
						</ul>
					</li>
					<li>
						<span>
						</span>
						<span>
							Advanced
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									Scavenge&nbsp;Time
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									General&nbsp;Settings
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									System&nbsp;Under&nbsp;Maintenance
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Config&nbsp;Self&nbsp;Backup
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Download&nbsp;Config
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Force&nbsp;Delete&nbsp;Server
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Directory&nbsp;Indexes
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Details
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Upload&nbsp;Logo
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Child&nbsp;Appearance
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Port&nbsp;Config
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Skeleton&nbsp;and&nbsp;Disable
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Blocked&nbsp;Ips
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Notification&nbsp;Home
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Login&nbsp;Options
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									License&nbsp;Update
								</span>
							</li>
						</ul>
					</li>
				</ul>
			</li>
			<li>
				<span>
				</span>
				<span>
					Servers
				</span>
				<ul>
					<li>
						<span>
						</span>
						<span>
							Resources
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									Domain&nbsp;Defaults
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Auxilliary&nbsp;Logins
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Login&nbsp;History
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Shell&nbsp;Access
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Dns&nbsp;Templates
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Backup&nbsp;Home
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									IP&nbsp;Addresses
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Ssl&nbsp;Certificates
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Add&nbsp;Domain
								</span>
							</li>
						</ul>
					</li>
					<li>
						<span>
						</span>
						<span>
							Security
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									SSH&nbsp;Config
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Watchdog
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Lxguard
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Blocked&nbsp;Hosts
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									SSH&nbsp;Authorized&nbsp;Keys
								</span>
							</li>
						</ul>
					</li>
					<li>
						<span>
						</span>
						<span>
							Server
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									Services
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Processes
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Component&nbsp;Info
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Command&nbsp;Center
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Switch&nbsp;Program
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Timezone
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									SSH&nbsp;Terminal
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Log&nbsp;Manager
								</span>
							</li>
						</ul>
					</li>
					<li>
						<span>
						</span>
						<span>
							Machine
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									Driver&nbsp;Configuration
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Reboot
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Poweroff
								</span>
							</li>
						</ul>
					</li>
				</ul>
			</li>
			<li>
				<span>
				</span>
				<span>
					Hosting
				</span>
				<ul>
					<li>
						<span>
						</span>
						<span>
							Domain
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									FTP&nbsp;Users
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Mysql&nbsp;Databases
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									File&nbsp;Manager
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Default&nbsp;Domain
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Cron&nbsp;Scheduled&nbsp;Task
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Traceroute
								</span>
							</li>
						</ul>
					</li>
					<li>
						<span>
						</span>
						<span>
							Web
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									FTP&nbsp;Sessions
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									PHP&nbsp;Config
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Webserver&nbsp;Config
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									FTP&nbsp;Config
								</span>
							</li>
						</ul>
					</li>
					<li>
						<span>
						</span>
						<span>
							Mail
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									Server&nbsp;Mail&nbsp;Settings
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Mail&nbsp;Queue
								</span>
							</li>
							<li>
								<span>
								</span>
								<span>
									Mails&nbsp;Per&nbsp;Client
								</span>
							</li>
						</ul>
					</li>
					<li>
						<span>
						</span>
						<span>
							Database
						</span>
						<ul>
							<li>
								<span>
								</span>
								<span>
									Mysql&nbsp;Password&nbsp;Reset
								</span>
								<ul>
									<li>
										<span>
										</span>
										<span>
											Database&nbsp;Admins
										</span>
									</li>
								</ul>
							</li>
						</ul>
					</li>
				</ul>
			</li>
			<li>
				<span>
				</span>
				<span>
					Account
				</span>
				<ul>
					<li>
						<span>
						</span>
						<span>
							Domains
						</span>
					</li>
					<li>
						<span>
						</span>
						<span>
							Clients
						</span>
					</li>
					<li>
						<span>
						</span>
						<span>
							Servers
						</span>
					</li>
				</ul>
			</li>
		</ul>
	</div>
	<script type="text/javascript">
		cmDrawFromText('MenuIDMenuBar1', 'hbr', cmThemeOffice, 'ThemeOffice');
	</script>
</div>

<?php
	// MR -- TODO!
?>