<?php 

$driver['hostdeny'] = "linux";
$driver['dns'] = array("bind", "djbdns");
$driver['spam'] = array("bogofilter", "spamassassin");
$driver['mailinglist'] = "ezmlm";
$driver['ffile'] = "linux";
$driver['installapp'] = "linux";
$driver['allinstallapp'] = "linux";
$driver['pserver'] = "linux";
$driver['rubyrails'] = "linux";
$driver['uuser'] = "linux";
$driver['ftpuser'] = "pureftp";
$driver['web'] = array("apache", "lighttpd", "nginx", "lighttpdproxy", "nginxproxy");
$driver['mmail'] = array("qmail");
$driver['cron'] = "linux";
$driver['llog'] = "linux";
$driver['davuser'] = 'lighttpd';
$driver['sshconfig'] = 'linux';
