#!/bin/sh

echo "*** Add domain ini for Rainloop webmail ***"

read -r -d '' ini_content << EOF
imap_host = "127.0.0.1"
imap_port = 993
imap_secure = "SSL"
smtp_host = "127.0.0.1"
smtp_port = 587
smtp_secure = "TLS"
smtp_auth = On
EOF

path=$(dir -l /home/kloxo/httpd/webmail/rainloop/data/*/_default_/domains/ 2>/dev/null|grep '/:'|awk -F"/:" '{print $1}')

if [ "${path}" == "" ] ; then
	echo "- Directory not exists"
	exit
else
	for z in $path ; do
		if [ "${1}" == "" ] ; then
			doms=$(/home/vpopmail/bin/vdominfo|grep 'domain:'|awk '{print $2}')
	
			for x in ${doms} ; do
				echo "- '${x}.ini' added"
				echo ${ini_content} > ${z}/${x}.ini
			done
		else
			echo "- '${1}.ini' added"
			echo ${ini_content} > ${z}/${1}.ini
		fi
	done
fi
