#!/bin/sh

. /script/counter-start.inc

t=$(mysql -V|awk '{print $5}')
u=$(echo $t|grep -i '5.0.')

if [ "$u" != "" ] ; then
	echo "Need update mysql first..."
	echo "- Run 'yum replace mysql --replace-with=mysql55'" 
	echo "- For OpenVZ VPS, add 'innodb_use_native_aio=0' under '[mysqld]' in '/etc/my.cnf'"
	exit
fi

chkconfig kloxo on

sh /script/fixlxphpexe

. /script/directory
lxphp.exe ../bin/common/cleanup.php --without-services

. /script/counter-end.inc


