#!/bin/sh

. /script/counter-start.inc

if [ "$(rpm -qa|grep 'yum-presto')" == "" ] ; then
	if [ "$(yum list *yum*|grep '@')" != "" ] ; then
		yum install -y yum-presto deltarpm
	fi
fi

## trouble with mysql55 for qmail-toaster
sed -i 's/exclude\=mysql51/exclude\=mysql5/g' /etc/yum.repos.d/mratwork.repo

if [ ! -L /usr/bin/chkconfig ] ; then
	## MR -- fix issue if running restart in cron
	ln -s /sbin/chkconfig /usr/bin/chkconfig
fi

## MR -- importance for CentOS 6+ for cp/mv/rm
#sh /script/disable-alias

t=$(mysql -V|awk '{print $5}'|grep -i '5.0.')

if [ "$t" != "" ] ; then
	echo "Need update mysql first..."
	echo "- Run 'yum replace mysql --replace-with=mysql55'" 
	echo "- For OpenVZ VPS, add 'innodb_use_native_aio=0' under '[mysqld]' in '/etc/my.cnf'"
	exit
fi

chkconfig kloxo on

sh /script/fixlxphpexe
sh /script/set-kloxo-php

. /script/directory
lxphp.exe ../bin/common/cleanup.php

echo
echo "*** Restart services - BEGIN ***"
sh /script/restart-services --force
echo "*** Restart services - END ***"
echo

. /script/counter-end.inc

