#!/bin/sh

echo "*** Clear memory cache/buffers (recommended: per-hour) ***"

if [ "$1" != "" ] ; then
	t=$1
else
	t="0.85"
fi

i=$(free -m|grep 'Mem'|awk '{print $3/$2}')
j=$(printf "%.2f\n" $i)

if [ "$(ps aux|grep 'backup'|grep -v 'grep')" == "" ] ; then
	e=$(echo "$j>=$t"|bc)
	if [ "$e" == "1" ] ; then
		#s="- Clear memory ('$j' >= '$t' usage) with restart-all"
		s="- Clear memory ('$j' >= '$t' usage)"
		sh /script/clearcache3
		#sh /script/restart-all
	else
		s="- No clear memory ('$j' < '$t' usage)"
	fi
else
	s="- No clear memory (because 'backup' in progress; '$j' usage)"
fi

d="$(date +'%Y-%m-%d %H:%M:%S')"

echo $s
echo "$d $s" >> /usr/local/lxlabs/kloxo/log/cron-clearcache

