#!/bin/sh

echo "*** Process for disable service ***"

if [ "${1}" != "" ] ; then
	echo "- Disable '${1}' service"

	if [ "$(command -v systemctl)" != "" ] ; then
		if [ "$(systemctl list-unit-files|grep ^${1}.service)" != "" ] ; then
			systemctl disable ${1} >/dev/null 2>&1
			systemctl daemon-reload >/dev/null 2>&1
		else
			chkconfig ${1} off 2>/dev/null
		fi
	else
		chkconfig ${1} off 2>/dev/null
	fi

	if [ "${2}" != "" ] ; then
		if [ "$(command -v systemctl)" != "" ] ; then
			systemctl ${2} ${1}.service 2>/dev/null
		else
			service ${1} ${2} 2>/dev/null
		fi
	fi
else
	echo "- Format: ${0} <servicename>"
fi
