#!/bin/sh

echo "*** Process for disable firewall ***"

for x in iptables ip6tables ; do
	if [ -f /etc/sysconfig/${x} ] ; then
		echo "- '/etc/sysconfig/${x}' exists and then rename to '${x}.kloxosave'"
		'mv' -f /etc/sysconfig/${x} /etc/sysconfig/${x}.kloxosave
	else
		echo "- No exists for '/etc/sysconfig/${x}'"
	fi
done

for y in iptables firewall firewalld ; do
	c=$(command -v ${y})
	if [ "${c}" != "" ] ; then
		b=$(basename ${c})
		echo "- Found '${b}' command and then disable/inactivate service"

		if [ "$(command -v systemctl)" != "" ] ; then
			systemctl disable ${b}
			systemctl daemon-reload >/dev/null 2>&1
		else
			chkconfig ${b} off 2>/dev/null
			chkconfig --del ${b} 2>/dev/null
		fi

		service ${b} stop 2>/dev/null
	fi
done
