#!/bin/sh

if [ "$1" == "--help" ] ; then
	echo
	echo " ------------------------------------------------------------------------------"
	echo "  format: sh $0 <programs> [--force]"
	echo " ------------------------------------------------------------------------------"
	echo "  programs"
	echo "      - bind/djbdns/nsd/pdns/mydns/yadifa"
	echo "  --force"
	echo "      - for re-install"
	echo
	exit;
fi

echo
echo "- For help, type '$0 --help'"

if [ "$#" == 0 ] ; then
	echo "- No argument supplied."
	echo
	exit
fi

if [ "${2}" == "--force" ] || [ "${2}" == "-y" ] ; then
	type="reinstall"
else
	type="install"
fi

. /script/counter-start.inc

if [ -f /script/custom.dns.inc ] ; then
	. /script/custom.dns.inc
else
	. /script/dns.inc
fi

dns_select="dns_${1}"

if [ -z "${dns_select}" ] ; then
	yum ${type} ${dns_select} -y

	if [ "${dns_select}" == "dns_djbdns" ] ; then
		for i in axfrdns dnscache dnslog tinydns ; do
			rm -f /home/${i}
		done
	fi
	
	chkconfig ${dns_select} off
	service ${dns_select} stop
else
	echo "- Input not match"
	echo
	exit
fi

. /script/counter-end.inc

echo

