#!/bin/sh

echo "*** Enable SELinux (in 'permissive' mode)"

#if [ "$(grep envID /proc/self/status)" == "" ] ; then
if [ "$(sh /script/virtual-info -t)" == "container" ] ; then
	echo "- Not work in Container-type VPS (like OpenVZ)"
	exit
fi

for i in policycoreutils setroubleshoot setools ; do
	if [ "$(rpm -q $i)" == "" ] ; then
		echo "- Installing $i"
		yum -y install $i
	fi
done

if [ "$1" == "enforcing" ] || [ "$2" == "enforcing" ] ; then
	sed -i '/^SELINUX=/d' /etc/selinux/config
	echo -e "SELINUX=permissive" > /etc/selinux/config
	# don't need reboot
	echo enforcing > /selinux/enforce
else
	echo -e "SELINUX=permissive" > /etc/selinux/config
	# don't need reboot
	echo permissive > /selinux/enforce
fi

if [ -f /.autorelabel ] ; then
	#touch /.autorelabel
	rm -f /.autorelabel
fi

if [ "$1" == "--relabel" ] || [ "$2" == "--relabel" ] ; then
	echo "- Relabeling... Wait!"
	restorecon -Rv -n /
	fixfiles relabel /
fi

echo "WARNING: - Run with:
echo " - '$0 --relabel' if want relabel files/directories"
echo " - '$0 enforcing' if want as 'enforcing' mode (default: 'permissive')"
