#!/bin/sh

if [ "$(rpm -qa yum-presto)" == "" ] ; then
	if [ "$(yum list *yum*|grep '@')" != "" ] ; then
		yum install -y yum-presto deltarpm
	fi
fi

## trouble with mysql55 for qmail-toaster
if [ "$(cat /etc/yum.conf|grep 'exclude=')" != "" ] ; then
	sed -i 's/\(exclude\=\)\(.*\)\(mysql5\*\|mysql5?\*\|MariaDB\*\|dovecot\*\)\(.*\)/\1\4 mysql5\*/g' /etc/yum.conf
else
	echo "exclude=mysql5*" >> /etc/yum.conf
fi

if [ ! -L /usr/bin/chkconfig ] ; then
	## MR -- fix issue if running restart in cron
	ln -s /sbin/chkconfig /usr/bin/chkconfig
fi

if [ "$(rpm -qa sudo)" == "" ] ; then
	## Add sudo
	yum install -y sudo
fi

if [ "$(cat /etc/yum.conf|grep 'sslverify')" != "" ] ; then
	sed -i '/sslverify/d' /etc/yum.conf
fi

echo 'sslverify=false' >> /etc/yum.conf

## MR -- importance for CentOS 6+ for cp/mv/rm
# sh /script/disable-alias


## MR -- make install x86_64 only in 64bit OS
if [ "$(cat ~/.rpmmacros|grep '_query_all_fmt')" == "" ] ; then
	echo "%_query_all_fmt %%{name}-%%{version}-%%{release}.%%{arch}" >> ~/.rpmmacros
fi

## MR -- remove 32bit packages in 64bit OS
if [ "$(uname -m)" == "x86_64" ] ; then
	yum remove -y *.i386 *.i686
fi

if [ "$(rpm -qa redhat-lsb)" == "" ] ; then
	yum install -y redhat-lsb
fi