#!/bin/sh

listpath="/usr/local/lxlabs/kloxo/etc/list"

echo "Update Services Branch List"

for x in $(dir -l ${listpath}/set.*.lst|awk '{print $9}') ; do
	f=$(basename $x)
	n=${f%.lst}
	n=${n#set.}
	if [ -f ${listpath}/custom.${f} ] ; then
		p=${listpath}/custom.${f}
	else
		p=${listpath}/${f}
	fi

	echo "- List for '${n}' branch"

	if [ "${n}" == "php" ] ; then
		s=$(cat ${p}|tr ',' '\n'|sed -e 's/\(.*\)/\1-cli/g'|tr '\n' ' ')
		a=$(yum info ${s}|grep -e ^'Name' -e ^'Version'|awk '{print $3}'|xargs -n2 -d'\n'|sed 's/\(.*\)-cli \(.*\)/\1_\(as_\2\)/g'|sort|tr '\n' ','|sed 's/\(.*\),/\1/g')
	else
		s=$(cat ${p}|tr ',' ' ')
		a=$(yum info ${s}|grep -e ^'Name' -e ^'Version'|awk '{print $3}'|xargs -n2 -d'\n'|sed 's/\(.*\) \(.*\)/\1_\(as_\2\)/g'|sort|tr '\n' ','|sed 's/\(.*\),/\1/g')
	fi

	echo ${a} > ${listpath}/${n}.lst

	if [ "${n}" == "web" ] ; then
		echo ${a}|tr ',' '\n'|grep httpd|grep -v lighttpd|tr '\n' ','|sed 's/\(.*\),/\1/g' > ${listpath}/httpd.lst
		echo ${a}|tr ',' '\n'|grep lighttpd|tr '\n' ','|sed 's/\(.*\),/\1/g' > ${listpath}/lighttpd.lst
		echo ${a}|tr ',' '\n'|grep nginx|tr '\n' ','|sed 's/\(.*\),/\1/g' > ${listpath}/nginx.lst
		echo ${a}|tr ',' '\n'|grep hiawatha|tr '\n' ','|sed 's/\(.*\),/\1/g' > ${listpath}/hiawatha.lst
	fi

	if [ "${n}" == "database" ] ; then
		echo ${a}|tr ',' '\n'|grep -e 'mysql' -e 'mariadb' -e 'MariaDB'|tr '\n' ','|sed 's/\(.*\),/\1/g' > ${listpath}/mysql.lst
	fi
done