#!/bin/sh

sysctlf="/etc/sysctl.conf"

echo ">>> Modified ${sysctlf} <<<"

sed -i '/### begin/,/### end/d' ${sysctlf}

## MR - https://bbs.archlinux.org/viewtopic.php?pid=1002264
#       also add 'fs.aio-max-nr' for mysql 5.5 innodb aio issue
read -r -d '' patch1 << EOF
### begin -- add by Kloxo-MR
#fs.aio-max-nr = 33554432
#fs.file-nr = 33554432
#fs.file-max = 33554432
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 3
#vm.swappiness = 10
#vm.vfs_cache_pressure = 100
#vm.dirty_background_ratio = 15
#vm.dirty_ratio = 5
### end -- add by Kloxo-MR
EOF

#if [ ! -f /proc/user_beancounters ] ; then
#if [ "$(grep envID /proc/self/status)" != "" ] ; then
if [ "$(sh /script/virtual-info -t)" != "container" ] ; then
	echo "- Modified process"
	echo "${patch1}" >> ${sysctlf}
	sysctl -e -p
else
	echo "- No modified because in Container-type VPS (like OpenVZ)"
fi

limitsf="/etc/security/limits.conf"

echo ">>> Modified ${limitsf} <<<"

sed -i '/### begin/,/### end/d' ${limitsf}

echo "- Modified process"

read -r -d '' patch2 << EOF
### begin -- add by Kloxo-MR
*     soft  nofile  131072
*     hard  nofile  131072
root  soft  nofile  131072
root  hard  nofile  131072
### end -- add by Kloxo-MR
EOF

echo "${patch2}" >> ${limitsf}
ulimit -n 131072 >/dev/null 2>&1

echo ">>> Modified ulimit <<<"

if yum list installed *yum*|grep @ >/dev/null 2>&1 ; then
	if [ "$(uname -m)" == "x86_4" ] ; then
		v="1280000"
		m="1280000"
		d="128000"
	else
		v="160000"
		m="160000"
		d="128000"
	fi
else
	if [ "$(uname -m)" == "x86_4" ] ; then
		v="320000"
		m="320000"
		d="128000"
	else
		v="160000"
		m="160000"
		d="128000"
	fi

fi

ulimit -v $v -m $m -d $d
echo "- Modified with '-v $v -m $m -d $d'"

