#!/bin/sh

T="$(date +%s%N)"

sh /script/fixdns
sh /script/fixweb
sh /script/fixphp
sh /script/fixftpuser
sh /script/fixmail-all

# Time interval in nanoseconds
T="$(($(date +%s%N)-T))"
# Seconds
S="$((T/1000000000))"
# Milliseconds
M="$((T/1000000))"

printf "Process Time: %02d:%02d:%02d:%02d.%03d (dd:hh:mm:ss:xxxxxx)\n" \
	"$((S/86400))" "$((S/3600%24))" "$((S/60%60))" "$((S%60))" "${M}"