#!/bin/sh

cfile='/etc/ssh/sshd_config'

if [ "$(grep '^Protocol 2' {$cfile})" == "" ] ; then
	echo "Protocol 2" >> $cfile
	echo "Add 'Protocol 2' to ${cfile}"
else
	echo "Already exists 'Protocol 2' in ${cfile}"
fi

if [ "$(grep -i '^hostkey /etc/ssh/ssh_host_ed25519_key' ${cfile})" == "" ] ; then
	echo "Hostkey /etc/ssh/ssh_host_ed25519_key" >> $cfile
	echo "Add 'Hostkey /etc/ssh/ssh_host_ed25519_key' to ${cfile}"
else
	echo "Already exists 'Hostkey /etc/ssh/ssh_host_ed25519_key' in ${cfile}"
fi

if [ "$(grep -i '^hostkey /etc/ssh/ssh_host_rsa_key' ${cfile})" == "" ] ; then
	echo "Hostkey /etc/ssh/ssh_host_rsa_key" >> $cfile
	echo "Add 'Hostkey /etc/ssh/ssh_host_rsa_key' to ${cfile}"
else
	echo "Already exists 'Hostkey /etc/ssh/ssh_host_rsa_key' in ${cfile}"
fi

service sshd restart
service pure-ftpd restart