#!/bin/sh

if [ "$(rpm -qa|grep 'yum-presto')" == "" ] ; then
	if [ "$(yum list *yum*|grep '@')" != "" ] ; then
		yum install -y yum-presto deltarpm
	fi
fi

## trouble with mysql55 for qmail-toaster
if [ "$(cat /etc/yum.conf|grep 'exclude=')" != "" ] ; then
	sed -i 's/\(exclude\=\)\(.*\)\(mysql5\*\|mysql5?\*\|MariaDB\*\|dovecot\*\)\(.*\)/\1\4 mysql5\*/g' /etc/yum.conf
else
	echo "exclude=mysql5*" >> /etc/yum.conf
fi

if [ ! -L /usr/bin/chkconfig ] ; then
	## MR -- fix issue if running restart in cron
	ln -s /sbin/chkconfig /usr/bin/chkconfig
fi
