#!/bin/sh

if [ "$(rpm -qa yum-presto)" == "" ] ; then
	if [ "$(yum list *yum*|grep '@')" != "" ] ; then
		yum install -y yum-presto deltarpm >/dev/null 2>&1
	fi
fi

## trouble with mysql55 for qmail-toaster
if [ "$(cat /etc/yum.conf|grep 'exclude=')" != "" ] ; then
	sed -i 's/\(exclude\=\)\(.*\)\(mysql5\*\|mysql5?\*\|MariaDB\*\|dovecot\*\)\(.*\)/\1\4 mysql5\*/g' /etc/yum.conf
else
	echo "exclude=mysql5*" >> /etc/yum.conf
fi

if [ ! -L /usr/bin/chkconfig ] ; then
	## MR -- fix issue if running restart in cron
	ln -s /sbin/chkconfig /usr/bin/chkconfig
fi

if [ "$(rpm -qa sudo)" == "" ] ; then
	## Add sudo
	yum install -y sudo >/dev/null 2>&1
fi

if [ "$(cat /etc/yum.conf|grep 'sslverify')" != "" ] ; then
	sed -i '/sslverify/d' /etc/yum.conf
fi

echo 'sslverify=false' >> /etc/yum.conf

## MR -- importance for CentOS 6+ for cp/mv/rm
# sh /script/disable-alias


## MR -- make install x86_64 only in 64bit OS
if [ ! -f ~/.rpmmacros ] || [ "$(cat ~/.rpmmacros|grep '_query_all_fmt')" == "" ] ; then
	echo "%_query_all_fmt %%{name}-%%{version}-%%{release}.%%{arch}" >> ~/.rpmmacros
fi

## MR -- remove 32bit packages in 64bit OS
if [ "$(uname -m)" == "x86_64" ] ; then
	yum remove -y *.i386 *.i686 >/dev/null 2>&1
fi

if [ "$(rpm -qa redhat-lsb)" == "" ] ; then
	yum install -y redhat-lsb >/dev/null 2>&1
fi

if [ "$(rpm -qa dhclient)" == "" ] ; then
	yum install -y dhclient >/dev/null 2>&1
fi

path='/etc/sysconfig/network-scripts'
for x in $(dir -l ${path}/ifcfg-*|awk '{print $9}'|tr '\', ' ') ; do
	if [ "$(cat ${x}|grep -i 'dhcp')" != "" ] ; then
		y=${x#${path}/ifcfg-}
		dhclient ${y} >/dev/null 2>&1
	fi
done

if [ ! -d /var/log/hiawatha ] ; then
	mkdir -p /var/log/hiawatha
fi

chmod 777 /var/run

if [ "$(lxphp.exe -v 2>/dev/null | head -n 1 | cut -d " " -f 2 | cut -c 1,3)" == "54" ] ; then
	if [ "$(yum list yum* | grep '@')" != "" ] ; then
		sh /script/phpm-installer php56s >/dev/null 2>&1
		sh /script/fixlxphpexe php56s >/dev/null 2>&1
		sh /script/restart >/dev/null 2>&1
	fi
fi

sh /script/fix-limits > /dev/null 2>&1
