#!/bin/bash

# release on Kloxo-MR 7.0.0
# by mustafa.ramadhan@lxcenter.org

# ENVIRONMENT VARIABLE PRIMER FOR REFERENCE
# $0 script invoked
# $1, $2, $3 are the command line arguments
# $# Number of command line arguments 
# $@ all command line arguments - white space is preserved
# $* all command line arguments - white space striped 

if [ "$#" == 0 ] ; then
	echo
	echo " ------------------------------------------------------------------------------"
	echo "  format:"
	echo "    sh $0 --type=<> --key=<> --value=<> [--client=<>] [--domain=<>]"
	echo " ------------------------------------------------------------------------------"
	echo
	echo " Formula: 'key IN type value' (example 'spf IN TXT \"v=spf1 a mx ~all\"')"
	echo
	echo " --client: is optional and able to '--client=client1,client2' for multiple clients"
	echo " --domain: is optional and able to '--domain=domain1.com,domain2.com' for multiple domains"
	echo
	exit;
fi

request1=$1
REC_TYPE=${request1#--type\=}

request2=$2
REC_KEY=${request2#--key\=}

request3=$3
REC_VALUE=${request3#--value\=}

if [ "$REC_TYPE" == "" ] ; then
	echo "Empty --type= entry..."
	exit
fi

if [ "$REC_KEY" == "" ] ; then
	echo "Empty --key= entry..."
	exit
fi

if [ "$REC_VALUE" == "" ] ; then
	echo "Empty --value= entry..."
	exit
fi

. /script/directory
lxphp.exe ../bin/misc/fixdnsaddrecord.php $*