#!/bin/bash

# release on Kloxo-MR 7.0.0
# by mustafa.ramadhan@lxcenter.org

# ENVIRONMENT VARIABLE PRIMER FOR REFERENCE
# $0 script invoked
# $1, $2, $3 are the command line arguments
# $# Number of command line arguments 
# $@ all command line arguments - white space is preserved
# $* all command line arguments - white space striped 

if [ "$#" == 0 ] ; then
	echo
	echo " ------------------------------------------------------------------------------"
	echo "  format:"
	echo "    sh $0 --ttype=<> --hostname=<>"
	echo " ------------------------------------------------------------------------------"
	echo
	exit;
fi

request1=$1
REC_TTYPE=${request1#--ttype\=}

request2=$2
REC_HOSTNAME=${request2#--hostname\=}

if [ "$REC_TTYPE" == "" ] && [ "$REC_HOSTNAME" == "" ] ; then
	echo "Empty --ttype= --hostname= entry..."
	exit;
else
	if [ "$REC_TTYPE" == "" ] ; then
		echo "Empty --ttype= entry..."
		exit;
	elif [ "$REC_HOSTNAME" == "" ] ; then
		echo "Empty --hostname= entry..."
		exit;
	fi
fi

. /script/directory
lxphp.exe ../bin/misc/fixdnsremoverecord.php $*