#!/bin/sh

INIT_DIR="/usr/local/lxlabs/kloxo/init"

if [ "$1" != "" ] ; then
	base_name="$1"
	echo "${base_name}" > ${INIT_DIR}/php_active
else
	if [ -f ${INIT_DIR}/php_active ] ; then
		base_name="$(cat ${INIT_DIR}/php_active)"
	else
		base_name="php53s"
		echo "${base_name}" > ${INIT_DIR}/php_active
	fi
fi

mkdir -p /opt/${base_name}/custom

cp -rf ${INIT_DIR}/${base_name}/* /opt/${base_name}/custom/

cp -rf ${INIT_DIR}/${base_name}/*.sh /opt/${base_name}/custom
chmod 755 /opt/${base_name}/custom/*.sh

cp -rf ${INIT_DIR}/${base_name}/*.ini /opt/${base_name}/etc

chown -R root:root /opt/${base_name}

ln -sf /opt/${base_name}/custom/php-cli.sh /usr/bin/lphp.exe
ln -sf /opt/${base_name}/custom/php-cli.sh /usr/bin/lxphp.exe

cp -f ${INIT_DIR}/kloxo.init /etc/rc.d/init.d/kloxo
chown root:root /etc/rc.d/init.d/kloxo
chmod 0775 /etc/rc.d/init.d/kloxo

echo "Execute fixlxphpexe for ${base_name}..."
