#!/bin/sh

# repairs lxguard using data from logs.
# argument in seconds to extend scan period

'rm' -f /home/kloxo/lxguard/access.info
'rm' -f /home/kloxo/lxguard/hitlist.info

. /script/directory
lxphp.exe ../bin/common/lxguard.php $*