#!/bin/sh
echo ""
echo "Change qmail.init"
cp -rf /usr/local/lxlabs/kloxo/file/qmail.init /etc/rc.d/init.d/qmail
chmod 755 /etc/rc.d/init.d/qmail
echo "--------------------------"
echo "Set '/home/vpopmail/bin/vchkpw' for 6751 permissions"
chmod 6751 /home/vpopmail/bin/vchkpw
echo "--------------------------"
echo "Set '/var/qmail/control/locals' with 'localhost' only"
echo 'localhost' > /var/qmail/control/locals
echo "--------------------------"
echo "Modified MAXDAEMONS and MAXPERIP on '/etc/courier/imapd'"
sed -i 's/MAXDAEMONS\=40/MAXDAEMONS\=60/' /etc/courier/imapd
sed -i 's/MAXPERIP\=4/MAXPERIP\=20/' /etc/courier/imapd
echo "--------------------------"
sh /script/fixvpop
echo "--------------------------"
sh /script/fix-qmail-assign
echo "--------------------------"
sh /script/fixmail
echo "--------------------------"
sh /script/fixwebmail
echo ""