#!/bin/sh
echo ""
echo "Change qmail.init"
cp -rf /usr/local/lxlabs/kloxo/file/qmail.init /etc/rc.d/init.d/qmail
chmod -f 0755 /etc/rc.d/init.d/qmail
echo "--------------------------"
echo "Set '/home/vpopmail/bin/vchkpw' for root:root ownership"
chown -f root:root /home/vpopmail/bin/vchkpw
echo "Set '/home/vpopmail/bin/vchkpw' for 4751 permissions"
chmod -f 4755 /home/vpopmail/bin/vchkpw
echo "--------------------------"
echo "Copy qmail-smtp run script"
cp -rf /usr/local/lxlabs/kloxo/file/smtp_run /var/qmail/supervise/smtp/run
chown -f qmaill:qmail /var/qmail/supervise/smtp/run
chmod -f 0751 /var/qmail/supervise/smtp/run
echo "Copy qmail-submission run script"
cp -rf /usr/local/lxlabs/kloxo/file/submission_run /var/qmail/supervise/submission/run
chown -f qmaill:qmail /var/qmail/supervise/submission/run
chmod 751 /var/qmail/supervise/submission/run
echo "--------------------------"
echo "Create qmail-smtp-ssl (port 465)"
cp -rf /var/qmail/supervise/smtp /var/qmail/supervise/smtp-ssl
cp -rf /usr/local/lxlabs/kloxo/file/smtp-ssl_run /var/qmail/supervise/smtp-ssl/run
cp -rf /usr/local/lxlabs/kloxo/file/smtp-ssl_log_run /var/qmail/supervise/smtp-ssl/log/run
echo "--------------------------"
echo "Set '/var/qmail/control/locals' with 'localhost' only"
echo 'localhost' > /var/qmail/control/locals
echo "--------------------------"
echo "Modified MAXDAEMONS and MAXPERIP on '/etc/courier/imapd'"
sed -i 's/MAXDAEMONS\=40/MAXDAEMONS\=60/' /etc/courier/imapd
sed -i 's/MAXPERIP\=4/MAXPERIP\=20/' /etc/courier/imapd
echo "--------------------------"
sh /script/fixvpop
echo "--------------------------"
sh /script/fix-qmail-assign
echo "--------------------------"
sh /script/fixmail
echo "--------------------------"
sh /script/fixwebmail
echo ""