#!/bin/sh

. /script/counter-start.inc

if [ -f /script/custom.fix.inc ] ; then
	. /script/custom.fix.inc
else
	. /script/fix.inc
fi

. /script/directory
lxphp.exe ../bin/fix/fixphpini.php $*

. /script/counter-end.inc
