#!/bin/sh
# declaring Variables
reponame="kloxong"
repourl="https://github.com/KloxoNGCommunity/kloxong/raw/initial-rpm/"
relrpmname="kloxong-release.rpm"

yum clean all

if [ "$(rpm -qa|grep $reponame-release)" != "" ] ; then
	yum update $reponame* -y
else
	cd /tmp

	'rm' -rf /etc/yum.repos.d/kloxo.repo
	'rm' -rf /etc/yum.repos.d/kloxo-mr.repo
	'rm' -rf /etc/yum.repos.d/kloxo-custom.repo
	'rm' -rf /etc/yum.repos.d/lxcenter.repo
	'rm' -rf /etc/yum.repos.d/lxlabs.repo	
	'rm' -rf /etc/yum.repos.d/kloxong.repo.*
	'rm' -rf /tmp/kloxong*
	
	if [ "$(rpm -qa|grep wget)" == "" ] ; then
		yum install wget -y
	fi
	wget $repourl/$relrpmname --no-check-certificate
	rpm -ivh $relrpmname
	yum update $reponame-* -y
fi

. /script/fix-urgent
