#!/bin/sh
# declaring Variables
reponame="kloxong"
repourl="https://github.com/mustafaramadhan/kloxo/raw/rpms/release/neutral/noarch"
relrpmname="mratwork-release-0.0.1-1.noarch.rpm"


yum clean all

if [ "$(rpm -qa|grep '$reponame-')" != "" ] ; then
	yum update $reponame* -y
else
	cd /tmp

	'rm' -rf /etc/yum.repos.d/kloxo.repo
	'rm' -rf /etc/yum.repos.d/kloxo-mr.repo
	'rm' -rf /etc/yum.repos.d/kloxo-custom.repo
	'rm' -rf /etc/yum.repos.d/lxcenter.repo
	'rm' -rf /etc/yum.repos.d/lxlabs.repo	
	'rm' -rf /etc/yum.repos.d/mratwork.repo.*
	
	wget $repourl/$relrpmname --no-check-certificate
	rpm -ivh $relrpmname
	yum update $reponame-* -y
fi

. /script/fix-urgent
