#!/bin/sh

if [ -f /script/custom.fix.inc ] ; then
	. /script/custom.fix.inc
else
	. /script/fix.inc
fi

. /script/directory
lxphp.exe ../bin/fix/fixssl.php $*

cd /

ssl_key=$(dir -l /etc/letsencrypt/live/*/chain.pem 2>/dev/null|awk '{print $9}'|tr '\n' ' ')

for i in ${ssl_key[*]} ; do
	base_name=$(basename $i)
	path_name=${i%/$base_name}
	dom_name=${path_name#/etc/letsencrypt/live/}

	echo "- Processing for '${dom_name}' ssl files"

	cd ${path_name}
	cat privkey.pem cert.pem chain.pem > all.pem
	

	ln -sf ${path_name}/privkey.pem /home/kloxo/ssl/${dom_name}.key
	ln -sf ${path_name}/cert.pem /home/kloxo/ssl/${dom_name}.crt
	ln -sf ${path_name}/chain.pem /home/kloxo/ssl/${dom_name}.ca
	ln -sf ${path_name}/all.pem /home/kloxo/ssl/${dom_name}.pem
done

