#!/bin/sh

if [ -f /script/custom.fix.inc ] ; then
	. /script/custom.fix.inc
else
	. /script/fix.inc
fi

if [ ! -f /etc/cron.d/update_ssl ] ; then
	sh /script/fix-cron-ssl
fi

. /script/directory
lxphp.exe ../bin/fix/fixssl.php $*

