#!/bin/sh
. /script/directory

lxphp.exe ../bin/misc/installWebmailDb.php

if [ "$( rpm -qa kloxong*telaen*)" != "" ] ; then
	yum remove kloxo*telaen* -y
fi

if [ "$( rpm -qa kloxong*squirrelmail*)" != "" ] ; then
	yum remove kloxong*squirrelmail* -y
fi