#!/bin/sh

if [ "$(rpm -qa httpry)" == "" ] ; then
	yum -y remove httpry
fi

if [ -f /etc/logrotate.d/httpry ] ; then
	'rm' -f /etc/logrotate.d/httpry
fi

if [ -f /etc/rc.d/init.d/httpry ] ; then
	service httpry stop
	chkconfig --del httpry
	'rm' -f /etc/rc.d/init.d/httpry
fi

if [ -f /usr/lib/systemd/system/httpry.service ] ; then
	service httpry stop
	chkconfig --del httpry
	'rm' -f /usr/lib/systemd/system/httpry.service
	systemctl daemon-reload
fi

