#!/bin/sh

echo "*** Install Pure-ftpd rpm without capability (resolve for LXC container) ***"

if [ "${1}" == "" ] ; then
	ver1=$(rpm -q --queryformat '%{VERSION}' pure-ftpd)
	rel=$(rpm -q --queryformat '%{RELEASE}' pure-ftpd)
	ver="${ver1}-${rel}"
else
	ver=${1}
fi

cd /tmp
rm -f pure-ftpd*.rpm

echo "- Get src.rpm from mratwork repo and installed"
if [ "$(ps --no-headers -o comm 1)" == "systemd" ] ; then
	wget http://download.fedoraproject.org/pub/epel/7/SRPMS/p/pure-ftpd-${ver}.src.rpm
else
	wget http://rpms.mratwork.com/repo/mratwork/SRPMS/pure-ftpd-${ver}.mr.src.rpm
fi

rpm -ivh pure-ftpd*

echo " - Replace to '--without-capabilities' in pure-ftpd.spec"
sed -i 's/--with-capabilities/--without-capabilities/g' /root/rpmbuild/SPECS/pure-ftpd.spec
echo " - Change 'release' to 100"
sed -i 's/%{?dist}/00%{?dist}/g' /root/rpmbuild/SPECS/pure-ftpd.spec

echo "- Install dependencies"
yum install pam-devel libcap-devel openldap-devel selinux-policy-devel rpm-build MariaDB-devel postgresql-devel -y

echo "- Create rpm"
rpmbuild -bb --define 'dist .mr' /root/rpmbuild/SPECS/pure-ftpd.spec

echo "- Update rpm"
rpm -Uvh /root/rpmbuild/RPMS/x86_64/pure-ftpd-${ver1}*.rpm

sh /script/restart-ftp

echo
echo "* Note:"
echo "  - Format: $0 [target-version]"
echo "    where [target-version] = 1.0.37-1"
