#!/bin/sh

for i in mysqld mysql ; do
	if [ -f /etc/rc.init.d/${item} ] ; then
		cmdf=${i}
	fi
	#if [ "$(command -v systemctl)" != "" ] ; then
	if [ "$(ps --no-headers -o comm 1)" == "systemd" ] ; then
		if [ -f /usr/lib/systemd/system/${item}.service ] ; then
			cmdf=${i}
		fi
	fi
done

service ${cmdf} stop

mv -f /var/lib/mysql/kloxo /var/lib/mysql/kloxoold
latest=$(dir /home/kloxo/selfbackup/self/__backup/*.zip|sort -n|tail -1); unzip $latest -d /tmp
sh /script/upcp -y

service ${cmdf} stop

mysqld_safe --init-file=/tmp/mebackup.dump

service ${cmdf} start
