#!/bin/sh

if [ "$#" == 0 ] ; then
	echo
	echo " ---------------------------------------------------------------------------"
	echo "  format: sh $0 <module_name>"
	echo " ---------------------------------------------------------------------------"
	echo " - Because lxphp still in php 5.2.x, better use the same version"
	echo "   Example: echo 'sh $0 php52-xcache'"
	echo
#	echo " - If using Centos 6, add inside '/etc/yum.repos.d/kloxo-mr.repo' with:"
#	echo "     [kloxo-mr-ius-centos5]"
#	echo "     name=Kloxo-MR - IUS Community Packages for Enterprise Linux 5"
#	echo "     baseurl=http://dl.iuscommunity.org/pub/ius/stable/Redhat/5/\$basearch"
#	echo "     enabled=1"
#	echo "     gpgcheck=0"
#	echo "     includepkgs=php52*"
#	echo
	echo " - Certain modules need 'extension=/usr/local/lxlabs/ext/php/lib/xxx.so'"
	echo "   rather than 'extension=xxx.so' inside their ini file on"
	echo "   '/usr/local/lxlabs/ext/php/etc/php.d')"
	echo
	echo " - Check '/usr/local/lxlabs/ext/php/error.log' after testing with"
	echo "   'lxphp.exe -m'"
	echo
	exit;
fi

yum install yum-utils -y

rm -rf /tmp/lxphp-module/* >/dev/null 2>$1

mkdir -p /tmp/lxphp-module >/dev/null 2>$1

cd /tmp/lxphp-module >/dev/null 2>$1

yumdownloader $1

rpm2cpio *.rpm | cpio -idmv

cp -rf /tmp/lxphp-module/usr/lib/php/modules/* /usr/local/lxlabs/ext/php/lib >/dev/null 2>$1
cp -rf /tmp/lxphp-module/usr/lib64/php/modules/* /usr/local/lxlabs/ext/php/lib >/dev/null 2>$1

cp -rf /tmp/lxphp-module/usr/lib/php/zend/* /usr/local/lxlabs/ext/php/zend >/dev/null 2>$1
cp -rf /tmp/lxphp-module/usr/lib64/php/zend/* /usr/local/lxlabs/ext/php/zend >/dev/null 2>$1

cp -rf /tmp/lxphp-module/etc/php.d/* /usr/local/lxlabs/ext/php/etc/php.d >/dev/null 2>$1

chown lxlabs:lxlabs -R /usr/local/lxlabs  >/dev/null 2>$1




