#!/bin/sh

if [ "$1" == "reverse" ] ; then
	mv -f /usr/local/lxlabs/kloxo/etc/conf/slave-db.db /usr/local/lxlabs/kloxo/etc/conf/slave-db.db.bck
	sh /script/restart -y
else
	. /script/directory
	lxphp.exe ../bin/install/create.php --install-type=slave
	sh /script/restart -y
fi