#!/bin/bash

#ps hax -o rss,user | awk '{a[$2]+=$1;}END{for(i in a)print i" "int(a[i]/1024+0.5);}' | sort -rnk2

if [ "$(rpm -qa|grep smem)" == "" ] ; then
	yum install smem -y
fi

smem -u -t -k

echo
echo "* Note: web servers also run under 'apache' username"
echo