#!/bin/bash

#ps hax -o rss,user | awk '{a[$2]+=$1;}END{for(i in a)print i" "int(a[i]/1024+0.5);}'

ps -eo user,pid,ppid,rss,vsize,pcpu,pmem,command --sort vsize

#if [ "$(rpm -qa|grep smem)" == "" ] ; then
#	yum install smem -y
#fi

## trouble running smem in bash
#/usr/bin/smem -u -t -k

#echo ""
#echo "* Note: memory size in MB; web servers also run under 'apache'"
#echo ""