php53u_run="yum install -y --skip-broken php53u-* --exclude=*debuginfo* --exclude=php53u-xcache --exclude=php53u-pecl-imagick --exclude=php53u-eaccelerator"

php54_run="yum install -y --skip-broken php54-* --exclude=*debuginfo* --exclude=php54-xcache --exclude=php54-mysql --exclude=php54-pecl-zendopcache --exclude=php54-pgsql84 --exclude=php54-pecl-memcache"

php55u_run="yum install -y --skip-broken php55u-* --exclude=*debuginfo*"
php55w_run="yum install -y --skip-broken php55w-* --exclude=*debuginfo*"

php56u_run="yum install -y --skip-broken php56u-* --exclude=*debuginfo* --exclude=php56u-opcache --exclude=php56u-fpm-httpd --exclude=php56u-fpm-nginx --exclude=php56u-pecl-sphinx"
php56w_run="yum install -y --skip-broken php56w-* --exclude=*debuginfo*"

php70u_run="yum install -y --skip-broken php70u-* --exclude=*debuginfo* --exclude=php70u-fpm-httpd --exclude=php70u-fpm-nginx"
php70w_run="yum install -y --skip-broken php70w-* --exclude=*debuginfo* --exclude=php70w-mysql"

php71u_run="yum install -y --skip-broken php71u-* --exclude=*debuginfo* --exclude=php71u-fpm-httpd --exclude=php71u-fpm-nginx"
php71w_run="yum install -y --skip-broken php71w-* --exclude=*debuginfo* --exclude=php71w-mysql"

