#!/bin/sh

if [ "$#" == 0 ] ; then
	echo
	echo " ---------------------------------------------------------------------------"
	echo "  format: sh $0 <extension_name>"
	echo " ---------------------------------------------------------------------------"
	echo " - Because php52s using php 5.2.x, better use the same version"
	echo "   Example: 'sh $0 php52-xcache'"
	echo
	echo " - Certain extension need 'extension=/opt/php52s/lib/xxx.so'"
	echo "   rather than 'extension=xxx.so' inside their ini file on"
	echo "   '/opt/php52s/etc/php.d')"
	echo
	echo " - Check '/opt/php52s/error.log' after testing with 'php52s -m'"
	echo
	exit;
fi

yum install yum-utils -y

mkdir -p /tmp/php52s-module

cd /tmp/php52s-module

yumdownloader $1

rpm2cpio *.rpm | cpio -idmv >/dev/null 2>$1

for a in lib lib64 ; do
	b="/tmp/php52s-module/usr/$a/php/modules"
	if [ -d $b ] ; then
		echo "- copy extension .so to /opt/php52s/lib"
		cp -rf $b/* /opt/php52s/lib
	fi
done

for a in lib lib64 ; do
	b="/tmp/php52s-module/usr/$a/php/zend"
	if [ -d $b ] ; then
		echo "- copy zend extension .so to /opt/php52s/zend"
		cp -rf $b/* /opt/php52s/zend
	fi
done

b="/tmp/php52s-module/etc/php.d"
if [ -d $b ] ; then
	echo "- copy extension .ini to /opt/php52s/etc/php.d"
	cp -rf $b/* /opt/php52s/etc/php.d
fi

rm -rf /tmp/php52s-module/*
