#!/bin/sh

if [ "$#" == 0 ] ; then
	echo
	echo " ---------------------------------------------------------------------------"
	echo "  format: sh $0 <extension_name>"
	echo " ---------------------------------------------------------------------------"
	echo " - Because php52s using php 5.4.x, better use the same version"
	echo "   Example: 'sh $0 php54-xcache'"
	echo
	echo " - Certain extension need 'extension=/opt/php52s/lib/xxx.so'"
	echo "   rather than 'extension=xxx.so' inside their ini file on"
	echo "   '/opt/php52s/etc/php.d'"
	echo
	echo " - Testing with 'php52s -m'"
	echo
	exit;
fi

yum install yum-utils -y

rm -f *.rpm

cd /opt/php52s

yumdownloader $1

rpm2cpio *.rpm | cpio -idmv >/dev/null 2>$1

