#!/bin/sh

yum -y install php53s php53s-bcmath php53s-enchant php53s-fpm php53s-gd php53s-imap \
	php53s-intl php53s-ldap php53s-litespeed php53s-mbstring php53s-mcrypt \
	php53s-mysql php53s-pdo php53s-process php53s-pspell php53s-recode php53s-snmp \
	php53s-soap php53s-tidy php53s-xml php53s-xmlrpc

if [ "$(uname -m)" == "x86_64" ] ; then
	ln -sf /opt/php53s/usr/lib64 /opt/php53s/usr/lib
fi

chmod 755 /usr/local/lxlabs/kloxo/init/php53s-cgi.sh
chmod 755 /usr/local/lxlabs/kloxo/init/php53s-cli.sh

ln -sf /usr/local/lxlabs/kloxo/init/php53s-cli.sh /usr/bin/lphp.exe
ln -sf /usr/local/lxlabs/kloxo/init/php53s-cli.sh /usr/bin/lxphp.exe