#!/bin/sh

#yum -y install php53s-cli php53s-intl php53s-ldap php53s-litespeed php53s-mbstring php53s-mcrypt \
#	php53s-mysql php53s-pdo php53s-process php53s-pspell php53s-recode php53s-snmp \
#	php53s-soap php53s-tidy php53s-xml php53s-xmlrpc php53s-fpm php53s-bcmath php53s-enchant \
#	php53s-gd php53s-imap --skip-broken

#cp -rf /usr/local/lxlabs/kloxo/init/php53s/* /opt/php53s/custom/

#if [ "$(uname -m)" == "x86_64" ] ; then
#	ln -sf /opt/php53s/usr/lib64 /opt/php53s/usr/lib
#	sed -i "s:/opt/php53s/usr/lib/:/opt/php53s/usr/lib64/:" /opt/php53s/custom/php53s.ini
#fi

#for i in cgi cli ls fpm ; do
#	if [ -f /usr/local/lxlabs/kloxo/init/php53s/php-${i}.sh ] ;  then
#		cp -rf /usr/local/lxlabs/kloxo/init/php53s/php-${i}.sh /opt/php53s/custom/php-${i}.sh
#		chmod 755 /opt/php53s/custom/php-${i}.sh
#		ln -sf /opt/php53s/custom/php-${i}.sh /usr/bin/php53s-${i}
#	fi
#done

#sh /script/fixlxphpexe php53s

if rpm -qa|grep php53s >/dev/null 2>&1 ; then
	yum remove php53s* -y
	rpm -e php53s-fpm --noscripts
fi

sh /script/phpm-installer php53s
