#!/bin/sh

if [ "${1}" == "-y" ] || [ "${1}" == "--force" ] ; then
	action=${1}
else
	action=""
fi

for i in $(ls -ld /etc/opt/remi/php* | awk '{print $9}' | sed 's:/etc/opt/remi/::g' | tr '\n' ' ') ; do
	if [ "$(readlink /usr/bin/${i}-cli)" == "/etc/opt/remi/${i}/custom/php-cli.sh" ] ; then
		sh /script/phpm-installer $i $action
	fi
done