#!/bin/sh

base_name=$1
extension_name=$2
uname_m=$(uname -m)

if [ "$#" == 0 ] ; then
	echo
	echo " ---------------------------------------------------------------------------"
	echo "  format: sh $0 <version_target> <extension_name>"
	echo " ---------------------------------------------------------------------------"
	echo " - Better use the same version; Example: 'sh $0 php52m php52-xcache'"
	echo
	echo " - Testing with '${base_name} -m'"
	echo
	exit;
fi

if rpm -qa|grep 'yum-utils' >/dev/null 2>&1 ; then
	echo "'yum-utils' already exists"
else
	echo "Installing 'yum-utils'"
	yum install yum-utils -y
fi

repoquery --qf='%{name}' --requires --resolve ${extension_name}|egrep -iv '(php|mysql|postgresql|mariadb|httpd|openssl)(.*)'|sort -u > /opt/${base_name}/${extension_name}-dependencies
yum -y install $(cat /opt/${base_name}/${extension_name}-dependencies) >/dev/null 2>$1

cd /opt/${base_name}

'rm' -f *.rpm

yumdownloader ${extension_name} >/dev/null 2>$1

rpm2cpio *.rpm | cpio -idmv >/dev/null 2>$1

'rm' -rf ./*.rpm

for i in /opt/${base_name}/etc/php.d/*ini ; do
	sed -i 's:/usr/lib'${uname_m}'/php/modules::' ${i}
	if [ "$(cat $i|grep 'zend_extension=/opt/')" == "" ] ; then
		sed -i 's:zend_extension=/:zend_extension=/opt/'${base_name}'/usr/lib'${uname_m}'/php/modules/:' ${i}
	fi
done

