#!/bin/sh

base_name="${1}"

cd /opt/${base_name}

mkdir -p /opt/${base_name}/custom

echo "- Copy '${base_name}' sh script to custom dir..."
cp -rf /usr/local/lxlabs/kloxo/init/${base_name}/* /opt/${base_name}/custom/
chmod 755 /opt/${base_name}/custom/*.sh

for i in cgi cli ls fpm ; do
	if [ -f /usr/local/lxlabs/kloxo/init/${base_name}/php-${i}.sh ] ;  then
		ln -sf /opt/${base_name}/custom/php-${i}.sh /usr/bin/${base_name}-${i}
	fi
done

echo "- Adjustment extension_dir in php.ini of '${base_name}'..."
if [ "${base_name}" != "php52s" ] ; then
	if [ "$(uname -m)" == "x86_64" ] ; then
		sed -i "s:/usr/lib/:/usr/lib64/:" /opt/${base_name}/custom/php.ini
	else
		sed -i "s:/usr/lib64/:/usr/lib/:" /opt/${base_name}/custom/php.ini
	fi
fi

echo "- Copy '${base_name}' config files..."
cp -rf /usr/local/lxlabs/kloxo/init/${base_name}/* /opt/${base_name}/etc/