#!/bin/sh

if [ "$1" == "--help" ] ; then
	echo
	echo " ------------------------------------------------------------------------------"
	echo "  format: sh $0 <phpXYm|phpXYs>"
	echo " ------------------------------------------------------------------------------"
	echo "  phpXYm/phpXYs"
	echo "      - start from php52m/php52s"
	echo "      - phpXYm for 'multiple php'"
	echo "      - phpXYs for 'special php' for Kloxo-MR panel"
	echo
	exit;
fi

if [ "$#" == 0 ] ; then
	echo
	echo "- For help, type '$0 --help'"
	echo
	exit
fi

base_name="${1}"

main_path="/opt/${base_name}"

. /script/counter-start.inc

## MR -- remove last char (default m or s)
src_name="${base_name%?}"

if [ "$(grep 's' <<<${base_name})" == "" ] && [ "$(grep 'm' <<<${base_name})" == "" ] ; then
	echo "* WARNING: only for phpXYm or phpXYs (change XY from 52)"
else
	echo "- Remove ${base_name}-fpm service"

	stype=$(ps --no-headers -o comm 1)

	if [ -f ${main_path}/usr/sbin/php-fpm ] ; then
		service ${base_name}-fpm stop
		'rm' -rf ${main_path} >/dev/null 2>&1
		chkconfig ${base_name}-fpm off >/dev/null 2>&1
		chkconfig --del ${base_name}-fpm >/dev/null 2>&1
		if [ "${stype}" == "systemd" ] ; then
			'rm' -f /usr/lib/systemd/system/${base_name}-fpm.service >/dev/null 2>&1
			systemctl daemon-reload >/dev/null 2>&1
		else
			'rm' -f /etc/rc.d/init.d/${base_name}-fpm >/dev/null 2>&1
		fi
	fi
fi

. /script/counter-end.inc
