#!/bin/sh

base_name="${1}"
DATE="${2}"

## MR -- remove last char (default m or s)
src_name="${base_name%?}"

if [ "$(uname -m)" == "x86_64" ] ; then
	uname_m="64"
else
	uname_m=""
fi

cd /opt/${base_name}

mkdir -p /opt/${base_name}/custom

x="- Copy certain files to '/opt/${base_name}/custom'"
echo $x
echo $x >>/opt/${base_name}/install${DATE}.log

cp -rf /usr/local/lxlabs/kloxo/init/${base_name}/* /opt/${base_name}/custom/

x="- Set .sh to 755"
echo $x
echo $x >>/opt/${base_name}/install${DATE}.log

chmod 755 /opt/${base_name}/custom/*.sh

x="- Create .sh symlink"
echo $x
echo $x >>/opt/${base_name}/install${DATE}.log

for i in cgi cli ls fpm ; do
	if [ -f /usr/local/lxlabs/kloxo/init/${base_name}/${base_name}-${i}.sh ] ;  then
		x="-- From '/opt/${base_name}/custom/${base_name}-${i}.sh' to '/usr/bin/${base_name}-${i}'"
		echo $x
		echo $x >>/opt/${base_name}/install${DATE}.log

		ln -sf /opt/${base_name}/custom/${base_name}-${i}.sh /usr/bin/${base_name}-${i}
	fi
done

#if [ "${src_name}" != "php52" ] ; then
#	## MR -- php53/php54/php55 must to blank extenstion_dir in php.ini and set directly to each module ini
#	echo "- Change '${base_name}' extension path for modules ini..."
#	for i in /opt/${base_name}/etc/php.d/* ; do
#		if [ "$(find ${i} -type f | xargs grep 'extension=/opt/')" == "" ] ; then
#			if [ "$(find ${i} -type f | xargs grep 'extension=/usr/lib')" != "" ] ; then
#				sed -i 's:extension=/usr/lib/:extension=/opt/'${base_name}'/usr/lib'${uname_m}'/:' ${i}
#				sed -i 's:extension=/usr/lib'${uname_m}'/:extension=/opt/'${base_name}'/usr/lib'${uname_m}'/:' ${i}
#			else
#				if [ "$(find ${i} -type f | xargs grep 'extension = ')" != "" ] ; then
#					sed -i 's:extension = :extension=/opt/'${base_name}'/usr/lib'${uname_m}'/php/modules/:' ${i}
#				else
#					sed -i 's:extension=:extension=/opt/'${base_name}'/usr/lib'${uname_m}'/php/modules/:' ${i}
#				fi
#			fi
#		fi
#	done
#else
	## MR -- php52 only work if add extension_dir path
	#echo "- Change '${base_name}' for php.ini..."
	#if [ "${base_name}" == "php52m" ] ; then
	#	sed -i 's:/usr/lib/php/modules:/usr/lib'${uname_m}'/php/modules:' /opt/${base_name}/custom/php.ini
	#fi

	#sed -i 's:/usr/lib/php/modules:/usr/lib'${uname_m}'/php/modules:' /opt/${base_name}/custom/${base_name}.ini

	if [ "${uname_m}" == "64" ] ; then
		x="- Create symlink from /opt/${base_name}/usr/lib64 to /opt/${base_name}/usr/lib"
		echo $x
		echo $x >>/opt/${base_name}/install${DATE}.log

		ln -sf /opt/${base_name}/usr/lib64 /opt/${base_name}/usr/lib
	fi
#fi