#!/bin/sh

if [ "$1" == "--help" ] ; then
	sh /script/phpm-config-setup --help
else
	for i in $(cat /usr/local/lxlabs/kloxo/etc/list/set.php.lst|tr ',', '\n'|sed 's/[wu]//g'|uniq) ; do
		if [ "${i}" != "php" ] ; then
			sh /script/phpm-config-setup ${i}m $*
			sh /script/phpm-config-setup ${i}s $*
		fi
	done
fi