#!/bin/sh

if [ "$1" == "--help" ] ; then
	echo
	echo " ------------------------------------------------------------------------------"
	echo "  format: sh $0 <phpXYm|phpXYs> [--force]"
	echo " ------------------------------------------------------------------------------"
	echo "  phpXYm/phpXYs"
	echo "      - start from php52m/php52s"
	echo "      - phpXYm for 'multiple php'"
	echo "      - phpXYs for 'special php' for Kloxo-MR panel"
	echo "  --force"
	echo "      - for re-install"
	echo
	exit;
fi

if [ "$#" == 0 ] ; then
	echo
	echo "- For help, type '$0 --help'"
	echo
	exit
fi

base_name="${1}"

if [ "$(grep 's' <<<${base_name})" == "" ] && [ "$(grep 'm' <<<${base_name})" == "" ] ; then
	echo "* WARNING: only for phpXYm or phpXYs (change XY to 52 - 70)"
	exit
fi

## MR -- remove last char (default m or s)
src_name="${base_name%?}"

if [ "$(uname -m)" == "x86_64" ] ; then
	uname_m="64"
else
	uname_m=""
fi

x="- Disable certain modules (rename to .nonini) in 'php.d' and 'php-zts.d'"
echo ${x}
echo ${x} >>/opt/${base_name}/install.log

for j in php.d php-zts.d ; do
	if [ -d /opt/${base_name}/etc/${j} ] ; then
		for a in $(dir -l /opt/${base_name}/etc/${j}|egrep "(\.ini|\.nonini)$"|awk '{print $9}'|tr '\n' ' ') ; do
			x="-- Fix 'extension' path of '${a}' in '/etc/${base_name}/etc/${j}'"
			echo $x
			echo $x >>/opt/${base_name}/install.log

			## MR -- remove path in 'extension='
			sed -i 's:extension = /:extension=/:' /opt/${base_name}/etc/${j}/${a}

			if [ "$(cat /opt/${base_name}/etc/${j}/${a} 2>/dev/null|grep 'zend_extension=')" == "" ] ; then
				sed -ri 's:extension=/(.*)/:extension=:g' /opt/${base_name}/etc/${j}/${a}
			else
				if [ "$(cat /opt/${base_name}/etc/${j}/${a} 2>/dev/null|grep 'zend_extension=/opt/php')" != "" ] ; then
					sed -ri 's:extension=/(.*)/:extension=:g' /opt/${base_name}/etc/${j}/${a}
				elif [ "$(cat /opt/${base_name}/etc/${j}/${a} 2>/dev/null|grep 'zend_extension=/usr/lib')" != "" ] ; then
					sed -ri 's:extension=/(.*)/:extension=:g' /opt/${base_name}/etc/${j}/${a}
				fi
			fi

			## MR -- re-add path in 'zend_extension='
			if [ "$(cat /opt/${base_name}/etc/${j}/${a} 2>/dev/null|grep 'zend_extension=/')" == "" ] ; then
				sed -i 's:zend_extension=:zend_extension=/opt/'${base_name}'/usr/lib'${uname_m}'/php/modules/:' /opt/${base_name}/etc/${j}/${a}
			else
				if [ "$(cat /opt/${base_name}/etc/${j}/${a} 2>/dev/null|grep 'zend_extension=/opt/')" == "" ] ; then
					sed -i 's:zend_extension=/:zend_extension=/opt/'${base_name}'/usr/lib'${uname_m}'/php/modules/:' /opt/${base_name}/etc/${j}/${a}
				fi
			fi
		done
	fi
done

for j in php.d php-zts.d ; do
	if [ -d /opt/${base_name}/etc/${j} ] ; then
		if [ -d /opt/${base_name}/etc/${j} ] ; then

			a=$(dir -l /opt/${base_name}/etc/${j}|grep "\.nonini"|grep -v "_unused\."|awk '{print $9}'|tr '\n' ' ')

			for b in $a ; do
				mv -f /opt/${base_name}/etc/${j}/${b} /opt/${base_name}/etc/${j}/${b%.nonini}_unused.nonini
			done

			for i in dba dbase eaccelerator ioncube pdo_dblib pdo_odbc pdo_pgsql pgsql suhosin odbc mongo \
				apc apcu imagick interbase ioncube-loader sourceguardian memcache memcached \
				z-memcached mssql debug pdo_dblib pdo_firebird xdebug xcache opcache lzf redis enchant wddx ; do

				a=$(dir -l /opt/${base_name}/etc/${j}|grep "${i}\.ini"|awk '{print $9}'|tr '\n' ' ')

				for b in $a ; do
					c=$(dir -l /opt/${base_name}/etc/${j}|grep "${i}\.ini"|awk '{print $9}'|tr '\n' ' ');

					for d in $c ; do
						x="-- Disable '${i}' in '/etc/${base_name}/etc/${j}'"
						echo $x
						echo $x >>/opt/${base_name}/install.log

						'mv' -f /opt/${base_name}/etc/${j}/${d} /opt/${base_name}/etc/${j}/${d%.ini}_unused.nonini
					done
				done

			done

			## MR -- exception for php54
			if [ "${base_name}" == "php54m" ] || [ "${base_name}" == "php54s" ] ; then
				if [ -f /opt/${base_name}/etc/${j}/mysql.ini ] ; then
					'mv' -f /opt/${base_name}/etc/${j}/mysql.ini /opt/${base_name}/etc/${j}/mysql_unused.nonini
				fi
			fi
		fi
	fi
done

for j in php.d php-zts.d ; do
	if [ -d /opt/${base_name}/etc/${j} ] ; then
		for i in $(dir -l /opt/${base_name}/etc/${j}|grep "\.ini"|awk '{print $9}') ; do
			if [ -f /opt/${base_name}/etc/${j}/${i%.ini}_unused.nonini ] ; then
				x="-- Remove '${i}' in '/etc/${base_name}/etc/${j}'"
				echo $x
				echo $x >>/opt/${base_name}/install.log

				'rm' -f /opt/${base_name}/etc/${j}/${i}
			fi
		done
	fi
done

for j in php.d php-zts.d ; do
	if [ -d /opt/${base_name}/etc/${j} ] ; then
		for i in $(dir -l /opt/${base_name}/etc/${j}|grep "\.nonini"|awk '{print $9}') ; do
			if [ -f /opt/${base_name}/etc/${j}/${i%.nonini}_used.ini ] ; then
				x="-- Remove '${i}' in '/etc/${base_name}/etc/${j}'"
				echo $x
				echo $x >>/opt/${base_name}/install.log

				'rm' -f /opt/${base_name}/etc/${j}/${i}
			fi
		done
	fi
done

cd /opt/${base_name}

mkdir -p /opt/${base_name}/custom >/dev/null 2>&1

x="- Copy certain files to '/opt/${base_name}/custom'"
echo ${x}
echo ${x} >>/opt/${base_name}/install.log

'rm' -f  /opt/${base_name}/custom/php5* >/dev/null 2>&1

kpath="/usr/local/lxlabs/kloxo"
eripath="/etc/rc.d/init.d"
ulspath="/usr/lib/systemd/system"

x="-- Processing for 'php.ini.base'"
echo ${x}
echo ${x} >>/opt/${base_name}/install.log

'rm' -f  /opt/${base_name}/custom/php5* >/dev/null 2>&1

if [ -f ${kpath}/init/custom.php.ini.base ] ; then
	'cp' -rf ${kpath}/init/custom.php.ini.base /opt/${base_name}/custom/php.ini >/dev/null 2>&1

	if [ "$(grep 'm' <<<${base_name})" != "" ] ; then
		'cp' -rf ${kpath}/init/custom.php.ini.base /opt/${base_name}/custom/php-fpm.ini >/dev/null 2>&1
	fi
else
	'cp' -rf ${kpath}/init/php.ini.base /opt/${base_name}/custom/php.ini >/dev/null 2>&1

	if [ "$(grep 'm' <<<${base_name})" != "" ] ; then
		'cp' -rf ${kpath}/init/php.ini.base /opt/${base_name}/custom/php-fpm.ini >/dev/null 2>&1
	fi
fi

sed -i 's:__extension_dir__:/opt/'${base_name}'/usr/lib/php/modules:' /opt/${base_name}/custom/php.ini

if [ "$(grep 'm' <<<${base_name})" != "" ] ; then
	sed -i 's:__extension_dir__:/opt/'${base_name}'/usr/lib/php/modules:' /opt/${base_name}/custom/php-fpm.ini
fi

if [ "$(grep 'm' <<<${base_name})" != "" ] ; then
	sed -i 's:__disable_functions__::' /opt/${base_name}/custom/php.ini
	sed -i 's:__for_phpm__::' /opt/${base_name}/custom/php.ini
	sed -i 's:__for_phps__:;:' /opt/${base_name}/custom/php.ini
	sed -i 's:__session_save_path__:/var/lib/php/session:' /opt/${base_name}/custom/php.ini

	sed -i 's:__disable_functions__:;:' /opt/${base_name}/custom/php-fpm.ini
	sed -i 's:__for_phpm__::' /opt/${base_name}/custom/php-fpm.ini
	sed -i 's:__for_phps__:;:' /opt/${base_name}/custom/php-fpm.ini
	sed -i 's:__session_save_path__:/var/lib/php/session:' /opt/${base_name}/custom/php-fpm.ini

	sed -i 's:/var/log/php-error.log:/var/log/'${base_name}'-error.log:' /opt/${base_name}/custom/php-fpm.ini
	sed -i 's:/var/log/php-error.log:/var/log/'${base_name}'-error.log:' /opt/${base_name}/custom/php.ini
else
	sed -i 's:__disable_functions__:;:' /opt/${base_name}/custom/php.ini
	sed -i 's:__for_phpm__:;:' /opt/${base_name}/custom/php.ini
	sed -i 's:__for_phps__::' /opt/${base_name}/custom/php.ini
	sed -i 's:__session_save_path__:/usr/local/lxlabs/kloxo/session:' /opt/${base_name}/custom/php.ini

	'cp' -rf /opt/${base_name}/custom/php.ini /opt/${base_name}/custom/php-fpm.ini >/dev/null 2>&1


	sed -i 's:/var/log/php-error.log:/usr/local/lxlabs/kloxo/log/php-error.log:' /opt/${base_name}/custom/php-fpm.ini
	sed -i 's:/var/log/php-error.log:/usr/local/lxlabs/kloxo/log/php-error.log:' /opt/${base_name}/custom/php.ini
fi

x="-- Processing for 'php-cgi.sh/php-cli.sh/php-fpm.sh/php-ls.sh'"
echo ${x}
echo ${x} >>/opt/${base_name}/install.log

for i in php-cgi.sh php-cli.sh php-fpm.sh php-ls.sh ; do
	if [ -f ${kpath}/init/custom.${i}.base ] ; then
		'cp' -rf ${kpath}/init/custom.${i}.base /opt/${base_name}/custom/${i} >/dev/null 2>&1
	else
		'cp' -rf ${kpath}/init/${i}.base /opt/${base_name}/custom/${i} >/dev/null 2>&1
	fi

	sed -i 's:__phpm__:'${base_name}':' /opt/${base_name}/custom/${i} >/dev/null 2>&1
done

x="-- Processing for 'php52-fpm.conf.base/php53-fpm.conf.base'"
echo ${x}
echo ${x} >>/opt/${base_name}/install.log

if [ "${base_name}" == "php52s" ] || [ "${base_name}" == "php52m" ] ; then
	if [ -f ${kpath}/init/custom.php52-fpm.conf.base ] ; then
		'cp' -rf ${kpath}/init/custom.php52-fpm.conf.base /opt/${base_name}/custom/php-fpm.conf >/dev/null 2>&1
	else
		'cp' -rf ${kpath}/init/php52-fpm.conf.base /opt/${base_name}/custom/php-fpm.conf >/dev/null 2>&1
	fi

	sed -i 's:/var/run/php-fpm.pid:/var/run/'${base_name}'-fpm.pid:' /opt/${base_name}/custom/php-fpm.conf >/dev/null 2>&1
else
	if [ -f ${kpath}/init/custom.php53-fpm.conf.base ] ; then
		'cp' -rf ${kpath}/init/custom.php53-fpm.conf.base /opt/${base_name}/custom/php-fpm.conf >/dev/null 2>&1
	else
		'cp' -rf ${kpath}/init/php53-fpm.conf.base /opt/${base_name}/custom/php-fpm.conf >/dev/null 2>&1
	fi

	sed -i 's:/var/run/php-fpm/php-fpm.pid:/var/run/php-fpm/'${base_name}'-fpm.pid:' /opt/${base_name}/custom/php-fpm.conf
fi

x="- Setting .sh to 755"
echo ${x}
echo ${x} >>/opt/${base_name}/install.log

chmod 755 /opt/${base_name}/custom/*.sh

x="- Creating .sh symlink"
echo ${x}
echo ${x} >>/opt/${base_name}/install.log

for i in cgi cli ls fpm ; do
	if [ -f /opt/${base_name}/custom/php-${i}.sh ] ;  then
		x="-- From '/opt/${base_name}/custom/php-${i}.sh' to '/usr/bin/${base_name}-${i}'"
		echo ${x}
		echo ${x} >>/opt/${base_name}/install.log

		'rm' -f /usr/bin/${base_name}-${i} >/dev/null 2>&1
		ln -sf /opt/${base_name}/custom/php-${i}.sh /usr/bin/${base_name}-${i} >/dev/null 2>&1

		x="-- From '/opt/${base_name}/custom/php-${i}.sh' to '/usr/sbin/${base_name}-${i}'"
		echo ${x}
		echo ${x} >>/opt/${base_name}/install.log

		'rm' -f /usr/sbin/${base_name}-${i} >/dev/null 2>&1
		ln -sf /opt/${base_name}/custom/php-${i}.sh /usr/sbin/${base_name}-${i} >/dev/null 2>&1
	fi
done

if [ "${uname_m}" == "64" ] ; then
	x="- Create symlink from /opt/${base_name}/usr/lib64 to /opt/${base_name}/usr/lib"
	echo ${x}
	echo ${x} >>/opt/${base_name}/install.log

	if [ -d /opt/${base_name}/usr/lib ] ; then
		ln -sf /opt/${base_name}/usr/lib64/php /opt/${base_name}/usr/lib/php >/dev/null 2>&1

		if [ -d /opt/${base_name}/usr/lib64/php-zts ] ; then
			ln -sf /opt/${base_name}/usr/lib64/php-zts /opt/${base_name}/usr/lib/php-zts >/dev/null 2>&1
		fi
	else
		ln -sf /opt/${base_name}/usr/lib64 /opt/${base_name}/usr/lib >/dev/null 2>&1
	fi
fi

'cp' -f /opt/configs/php-fpm/etc/php-fpm.d/www.conf /opt/${base_name}/etc/php-fpm.d/www.conf >/dev/null 2>&1

if [ -f /opt/${base_name}/${base_name} ] ; then
	'rm' -f /opt/${base_name}/${base_name}
fi

if [ -f ${kpath}/init/custom.php-fpm.init.base ] ; then
	erifile="${kpath}/init/custom.php-fpm.init.base"
	merifile="${kpath}/init/custom.phpm-fpm.init.base"
else
	erifile="${kpath}/init/php-fpm.init.base"
	merifile="${kpath}/init/phpm-fpm.init.base"
fi

if [ -f ${kpath}/init/custom.php-fpm.service.base ] ; then
	ulsfile="${kpath}/init/custom.php-fpm.service.base"
	mulsfile="${kpath}/init/custom.phpm-fpm.service.base"
else
	ulsfile="${kpath}/init/php-fpm.service.base"
	mulsfile="${kpath}/init/phpm-fpm.service.base"
fi

if [ -f ${eripath}/phpm-fpm ] ; then
	chkconfig phpm-fpm off >/dev/null 2>&1
	service phpm-fpm stop >/dev/null 2>&1
	chkconfig -del phpm-fpm >/dev/null 2>&1
	'rm' -f ${eripath}/phpm-fpm
fi

stype=$(ps --no-headers -o comm 1)

#if [ "$(command -v systemctl)" != "" ] ; then
#if [ "$(ps --no-headers -o comm 1)" == "systemd" ] ; then
if [ "${stype}" == "systemd" ] ; then
	if [ -f ${ulspath}/phpm-fpm.service ] ; then
		chkconfig phpm-fpm off >/dev/null 2>&1
		service phpm-fpm stop >/dev/null 2>&1
		chkconfig -del phpm-fpm >/dev/null 2>&1
		'rm' -f ${ulspath}/phpm-fpm.service
		systemctl daemon-reload
	fi
fi

if [ "${base_name}" == "php" ] ; then
	echo "- No argument and then use 'PHP Branch'"

	#if [ "$(command -v systemctl)" != "" ] ; then
	#if [ "$(ps --no-headers -o comm 1)" == "systemd" ] ; then
	if [ "${stype}" == "systemd" ] ; then
		'cp' -f ${ulsfile} ${ulspath}/php-fpm.service
		sed -i 's:__custom_name__:'${base_name}':g' ${ulspath}/php-fpm.service
		chown root:root ${ulspath}/php-fpm.service
		chmod 0644 ${ulspath}/php-fpm.service
		chkconfig php-fpm on >/dev/null 2>&1
		sh /script/add-restart-queue restart-php-fpm
	else
		'cp' -f ${erifile} ${eripath}/php-fpm
		sed -i 's:__custom_name__:'${base_name}':g' ${eripath}/php-fpm
		chown root:root ${eripath}/php-fpm
		chmod 0755 ${eripath}/php-fpm
		chkconfig php-fpm on >/dev/null 2>&1
		sh /script/add-restart-queue restart-php-fpm
	fi
else
	if [ ! -f /opt/${base_name}/usr/sbin/php-fpm ] ; then
		echo "- Need ${base_name} installing with 'sh /script/phpm-installer ${base_name}'"
	else
		echo "- Create and enable service for ${base_name}"

		if [ "$(grep 's' <<<${base_name})" == "" ] ; then
			#if [ "$(command -v systemctl)" != "" ] ; then
			#if [ "$(ps --no-headers -o comm 1)" == "systemd" ] ; then
			if [ "${stype}" == "systemd" ] ; then
				'cp' -f ${mulsfile} ${ulspath}/${base_name}-fpm.service
				sed -i 's:__custom_name__:'${base_name}':g' ${ulspath}/${base_name}-fpm.service
				chown root:root ${ulspath}/php-fpm.service
				chmod 0644 ${ulspath}/${base_name}-fpm.service
			else
				'cp' -f ${merifile} ${eripath}/${base_name}-fpm
				sed -i 's:__custom_name__:'${base_name}':g' ${eripath}/${base_name}-fpm
				chown root:root ${eripath}/${base_name}-fpm
				chmod 0755 ${eripath}/${base_name}-fpm
			fi
		fi
	fi
fi

if [ ! -f /etc/php-fpm.d/default.conf ] ; then
	'cp' -f /opt/configs/php-fpm/conf/php/php-fpm.d/default.conf /etc/php-fpm.d/default.conf
fi
