#!/bin/sh

if [ "$(grep -i '^calluploadscript' /etc/pure-ftpd/pure-ftpd.conf)" != "" ] ; then
	echo "- Remove 'calluploadscript' line from '/etc/pure-ftpd/pure-ftpd.conf'"
	sed -i '/^CallUploadScript/ld' /etc/pure-ftpd/pure-ftpd.conf
fi

if [ "$(grep -i '^pure-uploadscript' /etc/rc.local)" != "" ] ; then
	echo "- Remove 'pure-uploadscript' line from '/etc/rc.local'"
	sed -i '/^pure-uploadscript/ld' /etc/rc.local
fi

