#!/bin/sh

echo "still unfinish..."
exit

homepath=/home
mysqlpath=/var/lib/mysql
stamp=$(date +"%Y-%m-%d-%H-%M")
zipfile=kloxo-mr_raw_$stamp.zip

echo
echo "*** Kloxo-MR raw-backup - BEGIN ***"
echo

if [ -f /etc/rc.d/init.d/mysqld ] ; then
	service mysqld stop;
else
	service mysql stop;
fi

cd /tmp

echo "- Create zip file"

if ! [ -d $mysqlpath/kloxo.bck ] ; then
	cp -rf $mysqlpath/kloxo $mysqlpath/kloxo.bck
fi

zip -r9yq  $zipfile $homepath $mysqlpath \
	-x \
	"$homepath/vpopmail/*" \
	"$homepath/lxadmin/bin/*" \
	"$homepath/kloxo/httpd/*" \
	"$homepath/kloxo/domain/*" \
	"$homepath/kloxo/lxguard/*" \
	"$homepath/kloxo/client/*/__backup/*" \
	"$homepath/lxlabs/*" \
	"$homepath/nouser/*" \
	"$mysqlpath/mysql/*" \
	"$mysqlpath/kloxo/*"

if [ -f /etc/rc.d/init.d/mysqld ] ; then
	service mysqld start;
else
	service mysql start;
fi

mv -f $zipfile /home/kloxo/client/admin/__backup

### MR -- also patch for lib.php to make backup process always finished
#sed -i 's:\t\tthrow new lxException("could_not_zip_dir:\t\/\/\tthrow new lxException("could_not_zip_dir:' \
#	/usr/local/lxlabs/kloxo/httpdocs/htmllib/lib/lib.php

echo
echo "- Patch for /usr/local/lxlabs/kloxo/httpdocs/htmllib/lib/lib.php "
echo "  for backup without error"

echo
echo "Attention:"
echo "- Raw backup only work for Mysql with MyISAM storage engine."
echo "  Run 'sh /script/mysql-convert' for convert to MyISAM"
echo
echo "- Your 'kloxo' database rename to 'kloxo.bck' inside zipfile"
echo
echo "- Your '$zipfile' move to: "
echo "  '/home/kloxo/client/admin/__backup'"
echo
echo "*** Kloxo-MR raw-backup - END ***"
echo
