#!/bin/sh

homepath=/home
mysqlpath=/var/lib/mysql
stamp=$(date +"%Y-%m-%d-%H-%M")
zipfile=kloxo-mr_raw_$stamp.tar.gz
clistfile=kloxo-mr_raw_$stamp.txt

echo
echo "*** Kloxo-MR raw-backup - BEGIN ***"
echo

if [ -f /etc/rc.d/init.d/mysqld ] ; then
	service mysqld stop;
else
	service mysql stop;
fi

cd /tmp

echo "- Create zip file"

if ! [ -d $mysqlpath/kloxo.bck ] ; then
	cp -rf $mysqlpath/kloxo $mysqlpath/kloxobck
fi

## mysql data; create zip
tar -czf "$zipfile" "$mysqlpath" \
	--exclude "$mysqlpath/mysql/*" \
	--exclude "$mysqlpath/kloxo/*"

if [ -f /etc/rc.d/init.d/mysqld ] ; then
	service mysqld start;
else
	service mysql start;
fi

## home dir; append zip
tar -uzf "$zipfile" "$homepath" \
	--exclude "$homepath/vpopmail/*" \
	--exclude "$homepath/lxadmin/bin/*" \
	--exclude "$homepath/kloxo/httpd/*" \
	--exclude "$homepath/kloxo/domain/*" \
	--exclude "$homepath/kloxo/lxguard/*" \
	--exclude "$homepath/kloxo/client/*/__backup/*" \
	--exclude "$homepath/lxlabs/*" \
	--exclude "$homepath/nouser/*" \
	--exclude "$homepath/backuper/*"


clist=$(dir -l /home/kloxo/client | grep "^d"|awk '{ print $NF }')
echo $clist > $clistfile

mv -f $zipfile /home/kloxo/client/admin/__backup

echo
echo "Attention:"
echo "- Raw backup only work for MySQL with MyISAM storage-engine."
echo "  Run 'sh /script/mysql-convert' for convert to MyISAM"
echo
echo "- Your 'kloxo' database rename to 'kloxo.bck' inside zipfile"
echo
echo "- Your '$zipfile' move to: "
echo "  '/home/kloxo/client/admin/__backup'"
echo
echo "*** Kloxo-MR raw-backup - END ***"
echo
