#!/bin/sh

if [ "${1}" == "" ] ; then
	for i in $(route -n|grep '!H'|awk '{print $1}'|tr '\n' ' ') ; do
		echo "- Removing ${i} from IP blackhole blocked"
		route del -host ${i} reject
	done
else
	echo "- Removing ${1} from IP blackhole blocked"
	route del -host ${1} reject
fi