#!/bin/sh

list=(named djbdns httpd nginx lighttpd hiawatha php-fpm qmail xinetd mysqld mysql kloxo)

for item in ${list[*]}
do
	if [ -f /etc/init.d/$item ] ; then
		if [ $item == 'qmail' ] ; then
			/etc/init.d/$item stop
			/etc/init.d/$item start
		else
			/etc/init.d/$item restart
		fi
	fi
done