#!/bin/sh

#list=(varnish trafficserver squid php-fpm memcached lighttpd nginx hiawatha httpd htcacheclean)

if [ -f /script/custom.restart-list.inc ] ; then
	. /script/custom.restart-list.inc
else
	. /script/restart-list.inc
fi

list=${list_web[*]}

if [ -f /script/custom.restart.inc ] ; then
	. /script/custom.restart.inc
else
	. /script/restart.inc
fi