#!/bin/sh

if [ ! -d /var/run/php-fpm ] ; then
	mkdir -p /var/run/php-fpm
fi

if [ -f /script/custom.restart-list.inc ] ; then
	. /script/custom.restart-list.inc
else
	. /script/restart-list.inc
fi

list=${list_phpfpm[*]}

if [ -f /script/custom.restart.inc ] ; then
	. /script/custom.restart.inc
else
	. /script/restart.inc
fi