#!/bin/sh

list=(named djbdns maradns httpd nginx lighttpd hiawatha php-fpm qmail xinetd mysqld mysql kloxo)

for item in ${list[*]}
do
	if $(chkconfig --list|grep $item|grep -i ':on' >/dev/null 2>&1) && [ -f /etc/init.d/$item ] ; then
		if [ $item == 'qmail' ] ; then
			/etc/init.d/$item stop
			/etc/init.d/$item start
		else
			/etc/init.d/$item restart
		fi
	fi
done