#!/bin/sh

list=(mysqld mysql named djbdns maradns pdns nsd varnish trafficserver squid httpd nginx lighttpd hiawatha qmail xinetd kloxo php-fpm)

for item in ${list[*]} ; do
	if [ -f /etc/init.d/${item} ] ; then
		for num in 0 1 2 3 4 5 6 ; do
			if $(dir /etc/rc.d/rc${num}.d|grep -E 'S[0-9]{2}'${item} >/dev/null 2>&1) ; then
				if [ $item == 'qmail' ] ; then
					qmailctl stop
					sleep 2
					qmailctl start
				else
					/etc/init.d/${item} restart
				fi

				break
			fi
		done
	fi
done