#!/bin/sh

list=(named djbdns httpd nginx lighttpd php-fpm qmail dovecot xinetd mysqld mysql)

for item in ${list[*]}
do
	if [ -f /etc/init.d/$item ] ; then
	#	/etc/init.d/$item restart
		/etc/init.d/$item stop
		/etc/init.d/$item start
	fi
done