#!/bin/sh

list=(mysqld mysql named djbdns pdns nsd mydns varnish trafficserver squid httpd nginx lighttpd hiawatha qmail xinetd php-fpm)

for item in ${list[*]} ; do
	if [ -f /etc/init.d/${item} ] ; then
		for num in 0 1 2 3 4 5 6 ; do
			if $(dir /etc/rc.d/rc${num}.d|grep -E 'S[0-9]{2}'${item} >/dev/null 2>&1) ; then
				### MR -- need special treatment for hiawatha because using by panel also
				if [ $item == 'hiawatha' ] ; then
					## tricky detect if hiawatha as web server
					if [ "$(grep 'hiawatha' /usr/local/lxlabs/kloxo/etc/slavedb/driver)" == "" ] ; then
						chkconfig hiawatha off
						if [ "$(service hiawatha status|grep '(pid')" == "" ] ; then
							/etc/init.d/${item} stop
						fi
					else
						chkconfig hiawatha on
						/etc/init.d/${item} restart
					fi
				elif [ $item == 'qmail' ] ; then
					qmailctl stop
					sleep 2
					qmailctl start
				else
					/etc/init.d/${item} restart
				fi

				break
			fi
		done
	fi
done