#!/bin/sh

if yum list installed *yum*|grep @ >/dev/null 2>&1 ; then
	if [ "$(uname -m)" == "x86_4" ] ; then
		v="1280000"
		m="1280000"
		d="128000"
	else
		v="160000"
		m="160000"
		d="128000"
	fi
else
	if [ "$(uname -m)" == "x86_4" ] ; then
		v="320000"
		m="320000"
		d="128000"
	else
		v="160000"
		m="160000"
		d="128000"
	fi

fi

ulimit -v $v -m $m -d $d
echo "Execute 'ulimit -v $v -m $m -d $d' finished."
