#!/bin/sh

sysctlf="/etc/sysctl.conf"

if grep 'add by Kloxo-MR' ${sysctlf} >/dev/null 2>&1 ; then
	echo "- 'add by Kloxo-MR' already exists in ${sysctlf}"
else
	echo "- add parameters between 'add by Kloxo-MR' in ${sysctlf}"

	echo "" >> ${sysctlf}
	echo "### begin -- add by Kloxo-MR" >> ${sysctlf}
	echo "fs.aio-max-nr = 65536" >> ${sysctlf}
	echo "fs.file-max = 65536" >> ${sysctlf}
	echo "#vm.swappiness = 10" >> ${sysctlf}
	echo "#vm.vfs_cache_pressure = 100" >> ${sysctlf}
	echo "#vm.dirty_background_ratio = 15" >> ${sysctlf}
	echo "#vm.dirty_ratio = 5" >> ${sysctlf}
	echo "### end -- add by Kloxo-MR" >> ${sysctlf}

	sysctl -e -p >/dev/null 2>&1
fi

limitsf="/etc/security/limits.conf"

if grep 'add by Kloxo-MR' ${limitsf} >/dev/null 2>&1 ; then
	echo "- 'add by Kloxo-MR' already exists in ${limitsf}"
else
	echo "- add parameters between 'add by Kloxo-MR' in ${limitsf}"
	echo "" >> ${limitsf}
	echo "### begin -- add by Kloxo-MR" >> ${limitsf}
	echo "*     soft  nofile  65536" >> ${limitsf}
	echo "*     hard  nofile  65536" >> ${limitsf}
	echo "root  soft  nofile  65536" >> ${limitsf}
	echo "root  hard  nofile  65536" >> ${limitsf}
	echo "### end -- add by Kloxo-MR" >> ${limitsf}

	ulimit -n 65536 >/dev/null 2>&1
fi