#!/bin/sh

for phpver in php52 php53u php54 ; do
	mkdir -p /opt/$phpver
	cd /opt/$phpver

	yumdownloader $phpver*

	for rpmfile in $(dir -x *.rpm) ; do
		rpm2cpio $rpmfile | cpio -idmv
		rm -rf $rpmfile
	done

	cd /opt/$phpver/etc/php.d/

	for inifile in eaccelerator memcache memcached xdebug \
			mysqlnd mysqlnd_ms mysqlnd_mysql mysqlnd_mysqli \
			interbase pdo_firebird pgsql pdo_pgsql pdo_mysqlnd ; do
		if [ -f $inifile.ini ] ; then
			mv -f $inifile.ini $inifile.nonini
		fi
	done

	echo '' > /opt/$phpver/etc/modules.ini

	cd /opt/$phpver/etc/php.d/

	for modinifile in $(dir -x *.ini) ; do
		cat $modinifile >> /opt/$phpver/etc/modules.ini
	done

	cd /opt/$phpver/etc/

	if [ ! -f php.ini.original ] ; then
		cp -rf php.ini php.ini.original
	fi

	cat /opt/$phpver/etc/modules.ini >> /opt/$phpver/etc/php.ini

	if [ -d /opt/$phpver/usr/lib64 ] ; then
		mv -f /opt/$phpver/usr/lib /opt/$phpver/usr/lib.bck
		ln -s /opt/$phpver/usr/lib64 /opt/$phpver/usr/lib
		cp -rf /opt/$phpver/usr/lib.bck/* /opt/$phpver/usr/lib64/
	fi

done
