#!/bin/sh

if [ "$1" == "--help" ] ; then
	echo
	echo " --------------------------------------------------------------"
	echo "  format: sh $0 <php/php53m/php54m/php55m>"
	echo " --------------------------------------------------------------"
	echo "   - 'php' mean 'php branch' (check with 'php v')"
	echo "   - for 'phpXYm', check with 'php55m-cli -v' (for php55m)"
	echo "   - unsupport for 'php52m'"
	echo
	exit;
fi

echo
echo "- For help, type 'sh $0 --help'"

kpath="/usr/local/lxlabs/kloxo"
eripath="/etc/rc.d/init.d"
ulspath="/usr/lib/systemd/system"

if [ "$#" == 0 ] ; then
	echo "- No argument supplied. Defaulting to localhost (master) servers"
	php_target="php"
else
	php_target=$1
fi

echo

if [ -f ${kpath}/init/custom.php-fpm.init.base ] ; then
	erifile="${kpath}/init/custom.php-fpm.init.base"
	merifile="${kpath}/init/custom.phpm-fpm.init.base"
else
	erifile="${kpath}/init/php-fpm.init.base"
	merifile="${kpath}/init/phpm-fpm.init.base"
fi

if [ -f ${kpath}/init/custom.php-fpm.service.base ] ; then
	ulsfile="${kpath}/init/custom.php-fpm.service.base"
	mulsfile="${kpath}/init/custom.phpm-fpm.service.base"
else
	ulsfile="${kpath}/init/php-fpm.service.base"
	mulsfile="${kpath}/init/phpm-fpm.service.base"
fi

if [ -f ${eripath}/phpm-fpm ] ; then
	chkconfig phpm-fpm off >/dev/null 2>&1
	service phpm-fpm stop >/dev/null 2>&1
	chkconfig -del phpm-fpm >/dev/null 2>&1
fi

if [ "$(command -v systemctl)" != "" ] ; then
	if [ -f ${ulspath}/phpm-fpm.service ] ; then
		chkconfig phpm-fpm off >/dev/null 2>&1
		service phpm-fpm stop >/dev/null 2>&1
		chkconfig -del phpm-fpm >/dev/null 2>&1
		'rm' -f ${ulspath}/phpm-fpm.service
		systemctl daemon-reload
	fi
fi

if [ "${php_target}" == "php" ] ; then
	echo "- No argument and then use 'PHP Branch'"

	if [ "$(command -v systemctl)" != "" ] ; then
		'cp' -f ${ulsfile} ${ulspath}/php-fpm.service
		sed -i 's:__custom_name__:'${php_target}':' ${ulspath}/php-fpm.service
		chown root:root ${ulspath}/php-fpm.service
		chmod 0644 ${ulspath}/php-fpm.service
		chkconfig php-fpm on >/dev/null 2>&1
		sh /script/add-restart-queue restart-php-fpm
	else
		'cp' -f ${erifile} ${eripath}/php-fpm
		sed -i 's:__custom_name__:'${php_target}':' ${eripath}/php-fpm
		chown root:root ${eripath}/php-fpm
		chmod 0755 ${eripath}/php-fpm
		chkconfig php-fpm on >/dev/null 2>&1
		sh /script/add-restart-queue restart-php-fpm
	fi
else
	if [ ! -f /opt/${php_target}/usr/sbin/php-fpm ] ; then
		echo "- Need ${php_target} installing with 'sh /script/phpm-installer ${php_target}'"
	else
		echo "- Set ${php_target} as php-fpm target for 'PHP Used'"

		if [ "$(command -v systemctl)" != "" ] ; then
			'cp' -f ${mulsfile} ${ulspath}/${php_target}-fpm.service
			sed -i 's:__custom_name__:'${php_target}':g' ${ulspath}/${php_target}-fpm.service
			chown root:root ${ulspath}/php-fpm.service
			chmod 0644 ${ulspath}/php-fpm.service
			chkconfig php-fpm on >/dev/null 2>&1
			sh /script/add-restart-queue restart-php-fpm
		else
			'cp' -f ${erifile} ${eripath}/${php_target}-fpm
			sed -i 's:__custom_name__:'${php_target}':g' ${eripath}/${php_target}-fpm
			chown root:root ${eripath}/${php_target}-fpm
			chmod 0755 ${eripath}/${php_target}-fpm
			chkconfig ${php_target}-fpm on >/dev/null 2>&1
			sh /script/add-restart-queue restart-php-fpm
		fi
	fi
fi

if [ ! -f /etc/php-fpm.d/default.conf ] ; then
	'cp' -f /opt/configs/php-fpm/conf/php/php-fpm.d/default.conf /etc/php-fpm.d/default.conf
fi

rm -f ${kpath}/etc/flag/use_php*.flg
echo '' > ${kpath}/etc/flag/use_${php_target}.flg