#!/bin/sh

path="/home/kloxo/httpd/webmail/afterlogic"

if [ "${1}" == "-y" ] ; then
	if [ ! -f ${path}/index.php ] ; then
		yum install kloxo-webmail-afterlogic -y
		chown -R apache:apache ${path}
	fi
fi

echo "*** Afterlogic Webmail Lite setup ***"

if [ ! -f ${path}/index.php ] ; then
	echo "- Application not exists. Exit"
	exit
fi

echo "- Preparing database"

rootpass=$(cd /usr/local/lxlabs/kloxo/httpdocs; lxphp.exe ../bin/common/mp.php)

mysql -f -u root -p"${rootpass}" < ${path}/data/settings/afterlogic_initial.sql >/dev/null 2>&1

#basefile="${path}/libraries/afterlogic/common/settings.php"

if [ -f ${path}/data/settings/afterlogic_config.json ] ; then
	'rm' -f ${path}/data/settings/config.json
	'cp' -f ${path}/data/settings/afterlogic_config.json ${path}/data/settings/config.json

#	cfgfile="${path}/data/settings/settings.xml.php"

#	echo "- Change 'setting.xml' to 'settings.xml.php' in 'settings/php'"

#	sed -i "s:'/settings/settings.xml':'/settings/settings.xml.php':g" ${basefile}

	chown -R apache:apache ${path}
fi

echo "- Generating password"

pass=$(date +%s | md5sum | base64 | head -c 8 ; echo)

echo "- Add Password to configuration file"

sed -i "s:<DBPassword>:${pass}:g" ${cfgfile}
sed -i "s:<AdminPassword>:${pass}:g" ${cfgfile}
sed -i "s:<Common>:<Common><?php exit;?>:g" ${cfgfile}

Q1="USE afterlogic;"
Q2="GRANT ALL ON afterlogic.* TO afterlogic@localhost IDENTIFIED BY '${pass}';"
Q3="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}"

mysql -u root -p"${rootpass}" -e "${SQL}" >/dev/null 2>&1
