#!/bin/sh

path="/home/kloxo/httpd/webmail/horde"

if [ "${1}" == "-y" ] ; then
	if [ ! -f ${path}/index.php ] ; then
		yum install kloxomr-webmail-horde -y
		chown -R apache:apache ${path}
	fi
fi

echo "*** Horde Webmail setup ***"

path="/home/kloxo/httpd/webmail/horde

if [ ! -f  ${path}/index.php ] ; then
	echo "- Application not exists. Exit"
	exit
fi

## MR -- because Horde use rpm on Kloxo-MR,
## so horde_groupware.sql and horde_conf.php as template

echo "- Preparing database"

rootpass=$(cd /usr/local/lxlabs/kloxo/httpdocs; lxphp.exe ../bin/common/mp.php)

echo "- Fix MySQL commands in import files of Horde"

'cp' -f ${path}/scripts/sql/horde_groupware.mysql.sql ${path}/scripts/sql/groupware.mysql.sql

hordefile="/home/kloxo/httpd/webmail/horde/scripts/sql/groupware.mysql.sql

mysql -f -u root p"${rootpass}" horde_groupware < ${path}/scripts/sql/groupware.mysql.sql >/dev/null 2>&1

'cp' -f  ${path}/config/horde_conf.php ${path}/config/conf.php

cfgfile="${path}/config/conf.php"

echo "- Generating password"

pass=$(date +%s | md5sum | base64 | head -c 8 ; echo)

echo "- Add password to configuration file"

sed -i "s:conf['sql']['password'] = 'horde';:conf['sql']['password'] = '${pass}';:g" ${cfgfile}

chown -R apache:apache ${path}

Q1="USE horde_groupware;"
Q2="GRANT ALL ON horde_groupware.* TO horde_groupware@localhost IDENTIFIED BY '${pass}';"
Q3="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}"

mysql -u root -p"${rootpass}" -e "${SQL}" >/dev/null 2>&1
