#!/bin/sh

path="/home/kloxo/httpd/cp/tht"

if [ ! -f ${path}/index.php ] ; then
	yum install kloxomr-panel-tht -y
	chown -R apache:apache $path
fi

. /script/directory
lxphp.exe ../bin/misc/setup-tht.php "$@"