#!/bin/sh

path="/home/kloxo/httpd/webmail/horde"

if [ ! -f ${path}/index.php ] ; then
	yum install kloxomr-webmail-horde -y
	chown -R apache:apache $path
fi

. /script/directory
lxphp.exe ../bin/misc/setup-horde.php "$@"