#!/bin/sh

path="/home/kloxo/httpd/webmail/telaen"

if [ ! -f ${path}/index.php ] ; then
	yum install kloxomr-webmail-telaen -y
	chown -R apache:apache $path
fi

. /script/directory
lxphp.exe ../bin/misc/setup-telaen.php "$@"