#!/bin/sh

path="/home/kloxo/httpd/webmail/t-dah"

if [ ! -f ${path}/index.php ] ; then
	yum install kloxomr-webmail-t-dah -y
	chown -R apache:apache $path
fi

. /script/directory
lxphp.exe ../bin/misc/setup-t-dah.php "$@"