#!/bin/sh

path="/home/kloxo/httpd/webmail/roundcube"

if [ ! -f ${path}/index.php ] ; then
	yum install kloxomr-webmail-roundcube -y
	chown -R apache:apache $path
fi

. /script/directory
lxphp.exe ../bin/misc/setup-roundcube.php "$@"