#!/bin/sh

path="/home/kloxo/httpd/webmail/rainloop"

if [ "${1}" == "-y" ] ; then
	if [ ! -f ${path}/index.php ] ; then
		yum install kloxomr-webmail-rainloop -y
		chown -R apache:apache ${path}
	fi
fi

echo "*** Rainloop Webmail setup ***"

if [ ! -f ${path}/index.php ] ; then
	echo "- Application not exists. Exit"
	exit
fi

appfiles=$(dir -l ${path}/rainloop/v/*/app/libraries/RainLoop/Config/Application.php 2>/dev/null | awk '{print $9}')

echo "- Change application.ini to application.ini.php"

if [ "${appfiles}" != "" ] ; then
	for x in $appfiles ; do
		sed -i "s:'application.ini':'application.ini.php':g" ${x}
		sed -i "s:; RainLoop Webmail configuration file:;<?php exit;?> RainLoop Webmail configuration file:g" ${x}
	done

	datfiles=$(dir -l ${path}/data/_data_*/_default_/configs/application.ini 2>/dev/null | awk '{print $9}')

	echo "- Change admin password"

	pass=$(date +%s | md5sum | base64 | head -c 8 ; echo)

	if [ "${datfiles}" != "" ] ; then
		for x in $datfiles ; do
			'mv' -f ${x} ${x}.php
			sed -i "s:\"12345\":\"${pass}\":g" ${x}
		done
	else
		echo "- Need access to webmail url first"	
	fi

	sh /script/add-rainloop-domains

	chown -R apache:apache ${path}
else
	echo "- Run '$0 -y' to install"
fi

