#!/bin/sh

ppath="/home/djbdns"

### MR - use 0.0.0.0 (that mean all ips) instead current IPs

if [ ! -d ${ppath} ] ; then
	mkdir -p ${ppath}
fi

for a in dnslog dnscache tinydns axfrdns ; do
	## MR -- delete wrong location
	if [ -d /${a} ] ; then
		'rm' -rf /${a}
	fi

	if [ -d /home/djbdns/${a} ] ; then
		'rm' -rf /home/djbdns/${a}
	fi

	if ! [ $(id -u ${a}) ] ; then
		/usr/sbin/useradd -r ${a}
	else
		/usr/sbin/userdel ${a}
		/usr/sbin/useradd -r ${a}
	fi
done

echo "* DJBDns setup for: "

echo '  - tinydns setup finished'
tinydns-conf tinydns dnslog ${ppath}/tinydns 127.0.0.1
if [ ! -d ${ppath}/tinydns/env ] ; then
	mkdir -p ${ppath}/tinydns/env
fi
echo '0.0.0.0' > ${ppath}/tinydns/env/IP

echo '  - axfrdns setup finished'
axfrdns-conf axfrdns dnslog ${ppath}/axfrdns ${ppath}/tinydns 0.0.0.0
/usr/bin/tcprules ${ppath}/axfrdns/tcp.cdb ${ppath}/axfrdns/tcp.tmp	< ${ppath}/axfrdns/tcp

echo '  - dnscache setup finished'
dnscache-conf dnscache dnslog ${ppath}/dnscache 127.0.0.1
if [ ! -d ${ppath}/dnscache/env ] ; then
	mkdir -p ${ppath}/dnscache/env
fi
echo '127.0.0.1' > ${ppath}/dnscache/env/IP

