#!/bin/sh

if [ "$1" == "httpd24" ] ; then
	if [ "$(rpm -qa|grep 'httpd24u-')" == "" ] ; then
		if [ "$(rpm -qa|grep 'httpd-')" == "" ] ; then
			echo
			echo "- Need select apache or proxy in 'Switch Programs'"
			echo
			exit
		else
			service httpd stop
			yum replace httpd --replace-with=httpd24u -y
			yum replace mod_suphp --replace-with=mod24u_suphp -y
			yum install mod24u_session -y
			chkconfig httpd on
		fi
	else
		echo
		echo "- httpd24 already installed"
		echo
		exit
	fi

	cat '' > /usr/local/lxlabs/kloxo/etc/flag/use_apache24.flg
elif [ "$1" == "httpd" ] ; then
	if [ "$(rpm -qa|grep 'httpd-')" == "" ] ; then
		if [ "$(rpm -qa|grep 'httpd24u-')" == "" ] ; then
			echo
			echo "- Need select apache or proxy in 'Switch Programs'"
			echo
			exit
		else
			service httpd stop
			yum replace httpd24u --replace-with=httpd -y
			yum replace mod24u_suphp --replace-with=mod_suphp -y
			yum remove mod24u_session -y			
			if [ "$(rpm -qa|grep 'mod24u_ruid2-')" != "" ] ; then
				yum replace mod24u_ruid2 --replace-with=mod_ruid2 -y
			fi
			yum install mod_ruid2 mod_fcgid mod_perl -y
			chkconfig httpd on
			echo
			echo "- Then, run 'sh /script/fixweb; sh /script/fixphp; sh /script/restart-web -y'"
			echo
			exit
		fi
	else
		echo
		echo "- httpd already installed"
		echo
		exit
	fi
	
	rm -f /usr/local/lxlabs/kloxo/etc/flag/use_apache24.flg
else
	echo
	echo "- Execute: '$0 httpd' or '$0 httpd24'"
	echo
fi