#!/bin/sh

if [ ! -f /script/programname ] ; then
	echo 'kloxo' > /script/programname
fi

if [ "$1" != "-y" ] ; then
	if [ -r /usr/bin/lxphp.exe ] ; then
		sh /script/cleanup
	else
		sh /usr/local/lxlabs/kloxo/install/setup.sh $*
	fi
else
	if [ -f /etc/rc.d/init.d/qmail ] ; then
		rm -f /etc/rc.d/init.d/qmail
	fi

	sh /usr/local/lxlabs/kloxo/install/setup.sh $*
fi

