#!/bin/sh

if [ "$1" == "--help" ] ; then
	echo
	echo " ------------------------------------------------------------------------------"
	echo "  format: sh $0 <programs> [--force]"
	echo " ------------------------------------------------------------------------------"
	echo "  programs"
	echo "      - httpd/httpd24/lighttpd/nginx/hiawatha/monkey/openlitespeed"
	echo "  --force"
	echo "      - for re-install"
	echo
	exit;
fi

echo
echo "- For help, type '$0 --help'"

if [ "$#" == 0 ] ; then
	echo "- No argument supplied."
	echo
	exit
fi

if [ "${2}" == "--force" ] || [ "${2}" == "-y" ] ; then
	type="reinstall"
else
	type="install"
fi

. /script/counter-start.inc

if [ -f /script/custom.web.inc ] ; then
	. /script/custom.web.inc
else
	. /script/web.inc
fi

web_select="web_${1}"
web_content=${!web_select}

if [ -z "${web_select}" ] ; then
	yum ${type} ${web_content} -y
	
	if [ "${web_select}" == "web_httpd24" ] ; then
		chkconfig httpd24-httpd off
		service httpd24-httpd stop
	else
		chkconfig ${web_select} off
		service ${web_select} stop
	fi
else
	echo "- Input not match"
	echo
	exit
fi

. /script/counter-end.inc

echo

