#!/bin/sh

if [ "$1" == "--help" ] ; then
	echo
	echo " ------------------------------------------------------------------------------"
	echo "  format: sh $0 <apache/lighttpd/nginx/hiawatha> [--force]"
	echo " ------------------------------------------------------------------------------"
	echo "  --force"
	echo "      - for re-install"
	echo
	exit;
fi

echo
echo "- For help, type '$0 --help'"

if [ "$#" == 0 ] ; then
	echo "- No argument supplied. Defaulting to localhost (master) servers"
	echo
	exit
fi

DATE=$(date +"%Y/%m/%d %H:%M:%S")

base_name="${1}"

mkdir -p /opt/${base_name}

cd /opt/${base_name}

x="=== BEGIN '$1' (${DATE}) install ==="
echo $x
echo $x >/opt/${base_name}/install.log

if yum list ${base_name} >/dev/null 2>&1 ; then
	pack_name="${base_name}"
else
	echo "- No '${base_name}' packages exists. Exit"
	echo
	exit
fi

if [ "$(uname -m)" == "x86_64" ] ; then
	v=".x86_64"
else
	v=""
fi

if [ "$(rpm -qa yum-utils)" == "" ] ; then
	yum install yum-utils -y
fi

pack_verrel=$(repoquery --nvr ${pack_name}|sed 's/${pack_name}-//')

if [ -f /opt/${base_name}/version ] ; then
	if [ "${2}" == "-y" ] || [ "${2}" == "--force" ] ; then
		#echo "${pack_ver}-${pack_rel}" > version
		echo "${pack_verrel}" > version
	else
		cver=$(cat /opt/${base_name}/version)

		if [ "$(rpm -qa rpmdevtools)" == "" ] ; then
			yum install rpmdevtools -y
		fi

		#out=$(rpmdev-vercmp ${pack_ver}-${pack_rel} ${cver})
		out=$(rpmdev-vercmp ${pack_verrel} ${cver})

		if [[ $out != *${pack_ver}-${pack_rel}* ]] ; then
			#x="- '${pack_name}-${pack_ver}-${pack_rel}' ready to installed"
			x="- '${pack_name}-${pack_verrel}' ready to installed"
			echo $x
			echo $x >>/opt/${base_name}/install.log
			exit	
		fi
	fi
else
	#echo "${pack_ver}-${pack_rel}" > version
	echo "${pack_verrel}" > version
fi

x="- Install '${pack_name}' general dependencies rpms... Please wait!"
echo $x
echo $x >>/opt/${base_name}/install.log

c=""

x="-- Check installed dependencies rpms"
echo $x
echo $x >>/opt/${base_name}/install.log

for i in pcre openssl bash chkconfig zlib glibc shadow bzip2 \
	redhat gdbm initscripts lua glibc gamin glibc openldap \
	libxml2 polarssl libxslt expat GeoIP ; do

	x="--- Check for ${i} installed or not"
	echo $x >>/opt/${base_name}/install.log

	if rpm -qa|grep ${i} >/dev/null 2>&1 ; then
		x="---- ${i} already installed"
		echo $x >>/opt/${base_name}/install.log
	else
		c=${c}${i}${v}" "

		x="---- ${i} not installed"
		echo $x >>/opt/${base_name}/install.log
	fi
done

if [ "${c}" != "" ] ; then
	x="-- Install for not installed dependencies rpms"
	echo $x
	echo $x >>/opt/${base_name}/install.log
	yum -y install $c >>/opt/${base_name}/install.log
else
	x="-- Dependencies rpms already installed"
	echo $x
	echo $x >>/opt/${base_name}/install.log
fi

x="- Download all rpms... Please wait!"
echo $x
echo $x >>/opt/${base_name}/install.log

if [ -f /opt/${base_name}/etc ] ; then
	\rm -f /opt/${base_name}/etc
fi

if [ -f /opt/${base_name}/${base_name} ] ; then
	\rm -f /opt/${base_name}/${base_name}
fi

if [ "${pack_name}" == "httpd" ] ; then
	yum install httpd httpd-tools httpd-devel mod_fastcgi mod_fcgid mod_perl mod_rpaf mod_ruid2 mod_ssl mod_suphp mod_define perl-Taint-Runtime -y >>/opt/${base_name}/install.log
else
	if [ "${pack_name}" == "lighttpd" ] ; then
		yumdownloader ${pack_name} >>/opt/${base_name}/install.log
		yumdownloader ${pack_name}-fastcgi >>/opt/${base_name}/install.log
	elif [ "${pack_name}" == "nginx" ] ; then
		yumdownloader ${pack_name} >>/opt/${base_name}/install.log
	elif [ "${pack_name}" == "hiawatha" ] ; then
		yumdownloader ${pack_name} >>/opt/${base_name}/install.log
	fi

	x="- Extract all rpms to '/opt/${base_name}'"
	echo $x
	echo $x >>/opt/${base_name}/install.log

	for i in $(ls ./*.rpm) ; do
		rpm2cpio $i | cpio -idmv >/dev/null 2>$1
	done

	\rm -rf ./*.rpm
fi

cd /

x="=== END '$1' (${DATE}) install ==="
echo $x
echo $x >>/opt/${base_name}/install.log

echo

echo "Note:"
echo " - See '/opt/${base_name}/install.log' for detail install process"
echo


