#!/bin/sh

#if $(rpm -qa|grep lxphp >/dev/null 2>&1) ; then
if $(ls -al /usr/bin/lxphp.exe|grep /usr/local/lxlabs >/dev/null 2>&1) ; then
	yum remove lxphp lxlighttpd lxzend >/dev/null 2>&1
	
	rm -rf /usr/local/lxlabs/ext >/dev/null 2>&1
	
	rm -rf /usr/bin/lxphp.exe
	
	yum install php52s -y >/dev/null 2>&1
fi

. /script/directory
lxphp.exe ../bin/common/cleanup.php


