#!/bin/sh

echo "*** Process for BIND service ***"

if [ ! -f /var/run/named.pid ] ; then
	if [ -f /var/lock/subsys/named ] ; then
		'rm' -f /var/lock/subsys/named
	fi
fi

echo "  - Process: restart"
## possible transfer zone with 'rndc retranfer' but need each zone - it's not practice
/etc/rc.d/init.d/named stop
pkill -9 named
/etc/rc.d/init.d/named start
