#!/bin/sh

echo "*** Restart for DJBDNS service ***"

if [ ! -f /var/run/djbdns.pid ] ; then
	if [ -f /var/lock/subsys/djbdns ] ; then
		'rm' -f /var/lock/subsys/djbdns
	fi
fi

## MR -- exists in list.transfered.conf.tpl
#echo "  - Process: dnsnotify"
#for i in $(ls /opt/configs/djbdns/conf/master) ; do
#	sh /script/dnsnotify ${i}
#done

prog='djbdns'

. /usr/local/lxlabs/kloxo/etc/process/service.inc

