#!/bin/sh

### lighhtpd not create pid

echo "*** Process for LIGHTTPD service ***"

if [ ! -f /var/run/lighttpd.pid ] ; then
	if [ -f /var/lock/subsys/lighttpd ] ; then
		'rm' -f /var/lock/subsys/lighttpd
	fi
fi

#echo "  - Process: reload"
#/etc/rc.d/init.d/lighttpd reload

echo "  - Process: restart"
/etc/rc.d/init.d/lighttpd stop
pkill -9 lighttpd
/etc/rc.d/init.d/lighttpd start
