#!/bin/sh

### lighhtpd not create pid

echo "*** Restart for LIGHTTPD service ***"

if [ ! -f /var/run/lighttpd.pid ] ; then
	if [ -f /var/lock/subsys/lighttpd ] ; then
		'rm' -f /var/lock/subsys/lighttpd
	fi
fi

prog='lighttpd'

. /usr/local/lxlabs/kloxo/etc/process/service.inc
