#!/bin/sh

echo "*** Process for MYSQL/MARIADB service ***"

if [ -f /etc/rc.d/init.d/mariadb ] || [ -f /usr/lib/systemd/system/mariadb.service ]; then
	prog="mariadb
elif [ -f /etc/rc.d/init.d/mysql ] || [ -f /usr/lib/systemd/system/mysql.service ]; then
	prog="mysqld"
elif [ -f /etc/rc.d/init.d/mysql ] || [ -f /usr/lib/systemd/system/mysql.service ]; then
	prog="mysql"
fi

if [ "$(pgrep ^${prog})" == "" ] ; then
	service ${prog} start
fi
sleep 1

echo "  - Process: restart"
service ${prog} stop
pkill -9 ${prog}
pkill -9 mysqld_safe
service ${prog} start
