#!/bin/sh

echo "*** Restart for NGINX service ***"

if [ ! -f /var/run/nginx.pid ] ; then
	if [ -f /var/lock/subsys/nginx ] ; then
		'rm' -f /var/lock/subsys/nginx
	fi
fi

prog='nginx'

. /usr/local/lxlabs/kloxo/etc/process/service.inc
