#!/bin/sh

echo "*** Process for NGINX service ***"

if [ ! -f /var/run/nginx.pid ] ; then
	if [ -f /var/lock/subsys/nginx ] ; then
		'rm' -f /var/lock/subsys/nginx
	fi
fi

echo "  - Process: restart"
service nginx stop
pkill -9 nginx
service nginx start
