#!/bin/sh

echo "*** Process for NGINX service ***"

if [ ! -f /var/run/nginx.pid ] ; then
	if [ -f /var/lock/subsys/nginx ] ; then
		'rm' -f /var/lock/subsys/nginx
	fi

	/etc/rc.d/init.d/nginx start
else
	echo "  - No need started"
fi

echo "  - Process: reload"
/etc/rc.d/init.d/nginx reload

