#!/bin/sh

echo "*** Restart for NSD service ***"

if [ ! -f /var/run/nsd/nsd.pid ] ; then
	if [ -f /var/lock/subsys/nsd ] ; then
		'rm' -f /var/lock/subsys/nsd
	fi
fi

prog='nsd'

. /script/directory

. ../etc/process/service.inc

