#!/bin/sh

echo "*** Process for NSD service ***"

if [ ! -f /var/run/nsd/nsd.pid ] ; then
	if [ -f /var/lock/subsys/nsd ] ; then
		'rm' -f /var/lock/subsys/nsd
	fi
fi

echo "  - Process 'nsd': restart"
/etc/rc.d/init.d/nsd restart


