#!/bin/sh

echo "*** Process for PHP-FPM service ***"
if [ $(ls -A /var/run/php-fpm/*.pid) ] ; then
	echo "  - No need started"
else
	/etc/rc.d/init.d/php-fpm start
fi

echo "  - Process: reload"
/etc/rc.d/init.d/php-fpm reload