#!/bin/sh

echo "*** Process for XINETD (including Pure-FTPd) service ***"

if [ ! -f /var/run/xinetd.pid ] ; then
	if [ -f /var/lock/subsys/xinetd ] ; then
		'rm' -f /var/lock/subsys/xinetd
	fi
fi

echo "  - Process: restart"
service xinetd stop
pkill -9 xinetd
service xinetd start
