#!/bin/sh

echo "*** Process for BIND service ***"

if [ ! -f /var/run/yadifa.pid ] ; then
	if [ -f /var/lock/subsys/yadifa ] ; then
		'rm' -f /var/lock/subsys/yadifa
	fi

	/etc/rc.d/init.d/yadifad start
else
	echo "  - No need started"
fi

echo "  - Process : reload"
/etc/rc.d/init.d/yadifad reload
