<?php
$__information['ndskshortcut_list__pre'] = " È possibile aggiungere una pagina in Kloxo ai preferiti, cliccando sul [b] aggiungi ai preferiti [/ b] link [b] quella determinata pagina. [/ b] Ogni collegamento ha un parametro chiamato [b] Ordina Id [/ b]. Impostando un adeguato [b] Ordina id [/ b] per ogni link e poi ordinare l'intero elenco di [b] Ordina Id [/ b], è possibile organizzare l'elenco in qualsiasi modo si desidera. La barra degli strumenti in alto rifletterà il modo esatto in cui questa particolare lista è ordinata.";
$__information['sshauthorizedkey_addform_lxlabs_pre'] = "Questo aggiungerà la chiave ssh lxlabs tra le chiavi autorizzate, che permetterà al personale di supporto lxlabs per il login sul server senza password. Si consiglia di fare questo, se avete optato per l'assistenza da lxlabs.";
$__information['rawlxguardhit_list__pre'] = "Questa è la lista delle connessioni raw. Questo è utile soprattutto per tracciare un IP se si conosce l'account utente. Per esempio, i propri clienti cercando di accedere al server, se tentano troppe volte, saranno bloccati. Questa pagina ha una [b] ricerca avanzata [/ b], dove è possibile cercare l'elenco in base alla [b] login utente [/ b], e quindi sarete in grado di scoprire l'indirizzo ip del cliente, che si può rimuovere dal pagina principale collegamenti.";
$__information['login_pre'] = "<p> Benvenuto su <%programname%>  </p><p>Utilizzare un nome utente e una password validi per accedere alla console. </p> ";
$__information['tickethistory_addform__pre'] = "È possibile usare  &#91quote&#93 &#91/quote&#93 per citare un testo, che verrà mostrato formattata correttamente. È anche possibile usare &#91code&#93 &#91/code&#93 per frammenti di codice, e &#91b&#93 &#91/b&#93 per il grassetto.";
$__information['lxguardwhitelist_addform__pre'] = "Si consiglia di utilizzare il pulsante [b] whitelist [/ b] nella parte superiore della pagina Connessioni <url:a=list&c=lxguardhitdisplay> </ url>, per whitelistare un indirizzo ip. Inserendo manualmente l'IP è possibile incorrere in errori di ortografia. Se stai inserendo il tuo IP qui, si prega di controllare che sia corretto.";
$__information ['Sshconfig_updateform_update_pre'] = "Si raccomanda di disattivare completamente l'accesso basato su password per questo server, e di utilizzare invece il <url:goback=1&a=list&c=sshauthorizedkey> autorizzazione gestore di chiavi SSH </ url> per consentire persone specifiche per accedere senza password. Se questo è HyperVM, e avete intenzione di vendere VPSes ad altre persone, non si sarà in grado di disabilitare completamente l'accesso ssh la password, dal momento vps-proprietari dovranno accedere al nodo di accesso loro console. In ogni caso, assicurarsi di disattivare la password basato accesso root al server Quindi, come regola generale, il Kloxo, disabilitare la password di accesso a tutto, mentre su HyperVM, disattivare la password di accesso a root da solo ";
$__information ['All_dns_list__pre'] = "Questa è la lista di ogni dns creati dai vostri proprietari VPS. <url:o=general&a=updateform&sa=reversedns> Clicca qui </ url> per configurare i server DNS in modo che tutti i clienti possono utilizzare . direttore di DNS è il HyperVM consente al proprietario di VPS per creare DNS direttamente in HyperVM stesso, ei dati saranno salvati sul server del fornitore VPS In altre parole, consente di ospitare DNS del vostro cliente VPS sui server. ";
$__information ['Actionlog_list__pre'] = "log registra atto tutte le azioni eseguite su un client o un VPS. La cosa più importante che si dovrebbe notare è che l'id ausiliario della persona connesso è correttamente registrato. Così si dovrebbe mai dare l'account principale per chiunque, invece creare le identità ausiliari <url:a=list&c=auxiliary> </ url> per ogni vostro personale ";
$__information ['Sshauthorizedkey_list__pre'] = "Si prega di notare, il file ~ / .ssh/authorized_keys2 è stato deprecato come di OpenSSH versione 3, e così solo è riuscito il file ~ / .ssh / authorized_keys. Queste sono le chiavi ssh dal . macchine che possono accedere a questo server senza fornire la password Assicurarsi di mantenere questa lista rifilata ";
$__information ['Updateform_forcedeletepserver_pre'] = "Forza Elimina server solo rimuove il server dal database di HyperVM Questo è utile se il server è stato completamente rimosso non è più accessibile.";
$__information ['Allowedip_addform__pre'] = "Si prega di notare:.. Questa è solo per bloccare l'accesso al pannello di controllo, e non bloccherà l'accesso alla risorsa reale È possibile aggiungere un IP della forma [b] 192.168.1 * [/ b] indicano un intervallo. Cioè, invece di fornire un numero, è possibile usare [b] * [/ b] per rappresentare l'intera gamma. È inoltre possibile aggiungere singoli ips della forma 192.168.1.2. Si prega di notare che la notazione con punti è necessario, ed è necessario fornire tutti i campi 4. Se si vuole permettere a tutti, rimuovere tutti gli ips consentite, o fornire [b] *. *. *. * [/ b]. Altre notazioni IP sono non supportato a questo punto ";
$__information ['Blockedip_addform__pre'] = "Attenzione: questo è solo per bloccare l'accesso al pannello di controllo, e non bloccherà l'accesso alla risorsa reale Questa è la lista dei ipaddresses bloccati La notazione ip è la stessa di quella.. di permesso ip Si dovrebbe aggiungere IP bloccati solo se la lista ip consentito è vuoto Se permesso lista ip non è vuota allora, automaticamente tutti ips non elencati sono negati ";
$__information ['Updateform_portconfig_pre'] = "Questa pagina è principalmente destinata a configurare le porte di Kloxo / HyperVM. Dopo aver apportato le modifiche qui, è necessario riavviare il servizio Kloxo / HyperVM una volta per le modifiche abbiano effetto. Eseguire questo comando ' . [b] sh / script / DefaultPort [/ b] 'e le porte saranno ripristinate ai valori predefiniti È possibile riavviare Kloxo / HyperVM lasciare i campi vuoti per ripristinare porte predefinite. ";
$__information ['Updateform_schedule_conf_pre'] = "Si prega di notare che solo i backup pianificati, cioè, i backup che iniziano con il nome di <% programmi%>-programma-, verranno ruotate. Se si crea il proprio sostegno con il proprio nome, essi non verranno ruotate Quindi, se volete un backup creato manualmente da ruotare, fornire la stringa iniziale, come [b] <% programmi%>-programma-[/ b] ";
$__information ['Updateform_ssl_kloxo_pre'] = "Questo imposterà il certificato SSL per <% programmi%> come questo particolare certificato Assicurati di riavviare <% programmi%> dopo aver impostato qui.";
$__information ['Updateform_ssl_authorized_keys_pre'] = "Queste sono le chiavi SSH dalle macchine che sono autorizzati ad accedere al tuo account senza specificare la password. Essi sono tenuti come 1 per riga. Potete aggiungere le chiavi delle macchine che si desidera avere . senza password l'accesso a questo computer Si deve anche tenere questo file tagliato in modo da ridurre le probabilità di persone indesiderate nella registrazione ";
$__information ['Updateform_ssl_hypervm_pre'] = "Questo imposterà il certificato SSL per <% programmi%> come questo particolare certificato Assicurati di riavviare <% programmi%> dopo aver impostato qui.";
$__information ['Updateform_selfbackupconfig_pre'] = "Questo è in primo luogo lo scopo di configurare il backup remoto dei database master e nient'altro. L'dump del database è presa tutti i giorni e viene salvato in una cartella locale nella macchina. Se un account FTP è configurato qui , il file verrà caricato la macchina Questo è utile soprattutto nel grande installazione di cluster in cui il fallimento del master può avere un impatto molto più grandi ";
$__information ['Lxguard_updateform_update_pre'] = "Lxguard vi protegge da attacchi di forza bruta, monitorando l'ssh e messaggi di log ftp, e bloccando ipaddresses che hanno troppi tentativi falliti di accedere al server. Lxguard predefinita è attivata, e si blocca automaticamente padroni di casa, e non può essere disattivata. È possibile configurare Lxguard specificando il [b] soglia di tentativi non riusciti [/ b] o con l'aggiunta di alcuni ipaddresses alla whitelist. Se un IP si trova nella lista bianca, non sarà bloccato ., anche se ha varcato la soglia di tentativi falliti Per rimuovere le avvertenze si ottiene circa Lxguard clicca sul contratto di casella sottostante ";
$__information ['Updateform_generalsetting_pre'] = "Il 'HelpDesk URL' è un link al tuo Helpdesk, che sarà utilizzato al posto del help desk di default integrato nel software. URL Comunità è il link del client vedrà sulla sua pagina di sinistra , e nei casi normali può puntare al tuo forum ";
$__information ['Custombutton_addform__pre'] = "nell'URL, è possibile utilizzare% Nname%, che verrà sostituito con il nome del cliente. Per Kloxo solo, è possibile utilizzare% default_domain% per il dominio di default del cliente.";
$__information ['Updateform_download_config_pre'] = "Normalmente, quando si scaricano file, il maestro crea una sessione temporanea e quindi reindirizza il browser direttamente allo slave. Si tratta di salvare la larghezza di banda, in quanto in caso contrario, i file vengono inutilmente devono passare attraverso il master Se si attiva questa, HyperVM sarà invece instradare il file tramite il master stesso Questo è utile se avete dato ips private per gli schiavi, e gli schiavi non sono accessibili dal mondo esterno ";
$__information ['Updateform_login_options_pre'] = "Nota:. Timeout di sessione non può essere inferiore a 100 e se inferiore, verrà impostato automaticamente a 100";
$__information ['Resourceplan_change_pre'] = ". Nota: Se si modificano i valori qui, ogni account che utilizza questo piano verrà aggiornato con i nuovi valori <url:a=updateForm&sa=account> Clicca qui per visualizzare gli account configurati su questo piano </ url> ";
$__information ['Lxbackup_updateform_backup_pre'] = "Il file di backup verrà visualizzato nella directory di backup__ della vostra area cliente. Potete accedervi cliccando sulla scheda 'File Manager'. Per ripristinare un backup, è possibile innanzitutto caricarlo sul server utilizzando il [b] Carica [/ b] scheda. Potete caricare direttamente o da un URL HTTP o un server ftp. Allora vieni qui, e fare clic su [b] directory [/ b] icona a destra in [b] ripristinare [/ b] forma, e vi permetterà di selezionare il file particolare. Quindi fare clic su [b] processo di ripristino start [/ b]. Si prega di notare che <% programmi%> di backup è gerarchica. Se si prende il backup di un . particolare risorsa, tutto sotto è incluso automaticamente Così, se si prende il backup di admin, allora avete bisogno di non prendere i backup di clienti sotto di te a parte ";
$__information ['Phpini_updateform_edit_admin_pre'] = "Devi abilitare il [b] Gestione configurazione di PHP [/ b] bandiera a lasciare Kloxo gestire completamente il vostro php.ini. Si prega di notare che il vostro vecchio php.ini verrà sovrascritto. Per ripristinare il vecchio php.ini, basta disabilitare [b] Gestione configurazione di PHP [/ b] e di aggiornamento Si consiglia di che si lascia Kloxo completamente gestire la configurazione di PHP, e chiedere nel nostro forum se avete bisogno di caratteristiche speciali. ";
$__information ['Client_updateform_wall_pre'] = ". Nota: il messaggio sarà inviato solo ai vostri figli diretti (un livello, tra cui questo account) che ha un set-mail di contatto";
$__information ['Ffile_updateform_upload_pre'] = "Se si desidera caricare più file / directory, zip in su e caricare, è possibile decomprimere gli archivi dall'interno del file manager.";
$__information ['Dskshortcut_a_list__pre'] = "Per aggiungere una pagina ai Preferiti, fare clic su [b] aggiungi ai preferiti [/ b] link che appare in alto a destra. È possibile fare clic su uno dei preferiti nella lista qui sotto e cambiare il suo nome a qualcosa di più personale riconoscibile. Fai clic su [b] descrizione [/ b] intestazione e l'elenco verranno ordinati in quel campo, e quindi aggiornare l'intera struttura. L'elenco dei preferiti attuale sul pannello di sinistra sarà esattamente rispecchiare l'ordine che è visibile qui." ;
$__information ['Ticketconfig_updateform_ticketconfig_pre'] = "Il mailgate è un conto da cui <% programmi%> scaricherà mail a intervalli determinati, e verrà analizzato e aggiunto il supporto tecnico. Quando l'invio di posta elettronica, <% programmi%> invierà le mail come proveniente da l'indirizzo di configurare. L'indirizzo è della forma [b] account@domain.com [/ b]. Server è il server pop da cui scaricare le mail. [b] server.com [/ b ]. Se si seleziona la [b] uso ssl [/ b] scatola, quindi la posta sarà scaricata su pop3-ssl, alla porta 995. Si consiglia sempre di utilizzare SSL, ma è necessario fare in modo che il serer posta remoto supporta il servizio pop3-ssl sulla porta 995. ";
$__information ['Updateform_mysqlpasswordreset_pre'] = "Questo dovrebbe essere usato solo se avete perso la password di root. In circostanze normali, è possibile modificare la password cliccando qui <url:a=list&c=dbadmin> (amministratore di database) </ url >. Si prega di essere pazienti, questo richiederà un po 'per finire. Ciò consente di resettare la password di root di MySQL eseguendolo con l'opzione skip-grant-tables. Se questo non funziona, effettua il login tramite ssh ed eseguire il' [b ] sh / script / reset-mysql-root-password [/ b] '";
$__information ['Updateform_pserver_s_pre'] = "Questo è il pool di server per questo rivenditore. Ciò mostra l'elenco dei server che questo rivenditore può utilizzare durante la creazione di un client. Cioè, quando la creazione di un nuovo cliente, questo rivenditore sarà in grado di assegnare i server in questa lista a lui. ";
$__information ['General_updateform_disableper_pre'] = "Questa è la percentuale di utilizzo al quale il conto sarà disattivato Il valore normale è 110% Ti verrà dato avvertimenti quando il contingente non raggiunge 90.100.110%.";

$__information ['Updateform_ftp_conf_pre'] = "- Se si abilita [b] dont tenere copia locale [/ b], il file locale essere eliminato.".
        "È possibile utilizzare questa opzione se si vuole risparmiare spazio nel tuo account. <br>".
        "- È possibile scrivere formato pieno come [b] ftps://1.2.3.4:21001 [/ b] (per esempio) su 'FTP Server'";

$__information ['Vv_updateform_skin_logo_pre'] = "Per applicare il vostro logo sui vostri figli, basta disabilitare il loro 'in grado di gestire il logo' nelle impostazioni di autorizzazione.";
$__information ['Pserver_updateform_information_pre'] = "FQDN è un settore molto importante e dovrebbe essere impostato su un nome di dominio che sarà adeguatamente per risolvere questa particolare macchina. Una volta impostato il nome di dominio completo, HyperVM utilizzerà tale valore per ogni ulteriore comunicazione di rete, e se il set di nome di dominio completo qui è sbagliato, quindi la comunicazione di rete tra il master / slave fallirebbe. Se si lascia il campo vuoto, HyperVM utilizzerà il primo IP address su questo server per la comunicazione. Set FQDN di un host mediante la quale è possibile accedere a questa macchina da tutto il mondo ";
$__information ['Pserver_addform__pre'] = "Se è stato appena installato un server slave, la password è admin. Si raccomanda vivamente che si aggiungono server con il loro nome, piuttosto che dal loro IP. Che il server deve essere accessibile dal master utilizzando il particolare nome si fornisce qui, per esempio, server.domain.com Il verbose-identifier è una stringa che può essere usato per descrivere questo server, e sarà visibile in scatole Scelta risorse ";

// MR - Modificato
$__information ['Updateform_upload_logo_pre'] = "-. Lasciare i campi vuoti per ripristinare i loghi di immagini predefinite <br />".
        "- Per applicare il vostro logo sui vostri figli, basta disabilitare il loro 'in grado di gestire il logo' nelle impostazioni di autorizzazione <br />.".
        "-. Carica immagine logo (esempio: appare in alto a sinistra pagina cp) dovrebbe essere in formato PNG con altezza ottimale di 75 pixel, mentre la larghezza è di un massimo di scelta degli utenti";

$__information ['Web_updateform_extra_tag_pre'] = "<b> <font color=red> Attenzione!! </ Font> </ b> Qualunque sia immesso qui verrà aggiunto direttamente al VirtualHost. Se c'è un errore di sintassi in questo, impedirà il webserver riavvio Questa opzione è disponibile solo per l'utente admin dopo il salvataggio qui, assicurarsi che il server sia in esecuzione ";
$__information ['Addondomain_list__pre'] = "Nota:. <br> * Se si desidera un dominio parcheggiato con DNS e gestione posta elettronica, creare un dominio completo che ha la stessa radice del documento come il dominio di destinazione <br> * Se si desidera un dominio reindirizzato con DNS e gestione posta elettronica, creare un dominio completo, e quindi reindirizzare la sua [b] / [/ b] per il dominio di destinazione ";
$__information ['Redirect_a_list__pre'] = "Questo permetterà di reindirizzare un particolare URL nel dominio a un altro. <url:a=updateform&sa=configure_misc> Clicca qui </ url> se si desidera reindirizzare la forza non www base di http :/ / domain.com a http://www.domain.com" ;
$__information ['Web_updateform_dirindex_pre'] = "Attivazione di [b] indice di directory [/ b] vi permetterà di sfogliare le directory del proprio dominio tramite il server web. Se indice di directory è disabilitato, e se un file index.xxx non si trova all'interno la directory, un messaggio di errore proibito sarà sollevata ";
$__information ['Updateform_editmx_pre'] = "Se si desidera configurare il server di posta remoto, <url:a=updateform&sa=remotelocalmail> Clicca qui </ url>. Si può dire Kloxo che il server di posta è configurato da remoto, in modo che tutti i locali messaggi generati saranno inviati al server Se non si configura la posta remota, quindi tutte le mail di questo dominio sarà consegnato in locale stesso, senza fare alcuna ricerca DNS ";
$__information ['Web_updateform_run_stats_pre'] = "Questo vi permetterà di eseguire forzatamente il programma di statistiche, in modo da poter vedere le ultime statistiche nella pagina di statistiche web. Usare [b] update tutto [/ b] per eseguirlo su tutti i domini visibili nella top menu a discesa ";

$__information ['Server_alias_a_addform__pre'] = "- È possibile aggiungere caratteri jolly (*) come un alias in modo che tutti i sottodomini vengono automaticamente a questo dominio.".
        "Kloxo anche aggiungere automaticamente una voce DNS per l'alias. <br />".
        "- Una volta configurato il sottodominio catchall con caratteri jolly (*), è possibile aggiungere la propria logica nello script per rilevare il sottodominio corretta e fare di conseguenza <br />.".
        "- Lighttpd può essere confusa con caratteri jolly selezionati (*) l'accesso alle impostazioni predefinite (di default, cp, disattivare e 'Personalizza') le pagine verranno guidati alla pagina del dominio.";

$__information ['Updateform_sesubmit_pre'] = "Il tuo dominio sarà sottoposta a tutte le searchengines sottoelencati L'e-mail deve essere un indirizzo che non è usato spesso, dal momento che sono molto altamente probabile che ricevono spam sulla e-mail si entra qui.";
$__information ['Mmail_updateform_authentication_pre'] = "Il server MX primario è incluso automaticamente nel SPF, e non è necessario aggiungere separatamente. È possibile usare [b] update tutto [/ b] per impressionare questi valori su tutti i domini visibile su cima a discesa ";
$__information ['Updateform_preview_config_pre'] = "Anteprima di dominio è un dominio master, a cui il pulsante di sito-anteprima verrà reindirizzato. Dovete aggiungere manualmente un dominio parcheggiato chiamato domain.com.previewdomain.com a questo dominio, e quindi aggiungere il previewdomain.com qui Poi il [b] dns meno anteprima [/ b] verrà reindirizzato a domain.com.previewdomain.com caso di dubbi, si prega di lasciare vuoto ";
$__information ['Updateform_stats_protect_pre'] = "Statistiche di protezione pagina è la password che viene utilizzata per proteggere la pagina delle statistiche per il tuo dominio Se è impostata su null la password, la protezione sarà disabilitata, e sarete in grado di accedere direttamente alle statistiche.";
$__information ['Updateform_installatron_pre'] = "Devi fare il logout del tuo utente corrente, e poi specificamente il login come questo utente per utilizzare Installatron per questo particolare conto. Cioè, Installatron è disponibile solo al momento per l'account che è direttamente connesso ." ;
$__information ['Ftpuser_admin'] = "Usa [b] - diretto - [/ b] per aggiungere un ftpuser che non contiene il nome di dominio.";
$__information ['Updateform_default_domain_pre'] = "Questo imposterà il dominio che è considerato come il dominio primario per questo particolare conto. Potete accedere radice del documento di questo dominio andando a http://IP/ ~ clientname. Per mappare un IP address ad un dominio, devi <URL: a=list&c=ipaddress> clicca qui </ url>, andare all'interno di un IP address e fare clic su 'configurare il dominio' scheda lì. Se si desidera visualizzare un dominio prima che il DNS è configurato, il migliore modo è quello di creare una voce per il dominio nel file locale etc / hosts Il percorso per il file su Windows è c :/ windows/system32/drivers/etc/hosts sufficiente aggiungere una voce come questa:.. [b] 192.168. 1.32 domain.com [/ b] su una linea separete, e allora si sarà in grado di accedere al dominio digitando nella casella URL del browser ";
$__information ['Updateform_blockip_pre'] = "Aggiungi un IP per linea. Se si desidera aggiungere utilizzare un range di IP il. *. * Notazione., Ad esempio, 192.168. *. *. Si prega di notare, questa è l'unica notazione supportato per . intervalli di ip La notazione IP standard non è supportato ";
$__information ['Web_updateform_statsconfig_pre'] = "Ogni giorno, se la dimensione del file di log è più grande di 50 MB, vengono spostati nella directory principale del client. Se si impostano le remove_processed_logs come vero, allora invece di muoversi, saranno cancellati. Tuo principale calcolo delle statistiche non saranno interessati a tutti ";
$__information ['Web_updateform_hotlink_protection_pre'] = "Il tuo dominio e sottodomini avranno automaticamente accesso alle immagini, e non c'è bisogno di aggiungere loro in particolare. Un *. Domain.com viene aggiunto automaticamente alla lista di domini consentiti si fornisce qui . L'[b] reindirizzare ad immagine [/ b] deve essere un percorso per l'immagine all'interno del tuo dominio, e non un URL completo. Si deve essere della forma (/ img / noaccess.gif). Devi inserire domini come semplici nomi senza alcun wild-personaggi, ad esempio, domain.com, mydomain.com, mysdomain.com ";
$__information ['Mailqueue_list__pre'] = "Ci vorrà un po 'più di tempo per la coda a scomparire in realtà. Così dopo aver fatto clic su Elimina, i messaggi verranno visualizzati in coda per un po' più di tempo. Basta aggiornare la pagina dopo circa un minuto per verificare se le mail vengono effettivamente cancellati o no ";
$__information ['Mailqueue_updateform_update_pre'] = "Per visualizzare il registro per la posta elettronica, si prega di tornare al profilo, e lavare la coda di posta una volta, dal momento che solo il registro per il passato ora viene analizzato.";
$__information ['Rubyrails_addform__pre'] = "L'applicazione sarebbe normalmente accessibile a http://domain.com/applicationname. Il percorso dovrebbe essere / home / client / ROR / domain.com / applicationname. Se si specifica il [b] accessibile direttamente [/ b] bandiera, l'applicazione sarebbe accessibile a http://domain.com stessa ";
$__information ['Installapp_addform__pre'] = "Per installare un'applicazione nel root del documento, si prega di lasciare il [b] Località [/ b] vuoto. Per installare la stessa applicazione per un altro dominio, si prega di utilizzare la casella di selezione sulla parte superiore, e cambiare il dominio ad un altro, e sarete in grado di ottenere lo stesso modulo con il nuovo dominio come il genitore un messaggio con le informazioni di accesso e url sarà inviata all'indirizzo e-mail di contatto che fornite qui. ";
$__information ['Mysqldb_updateform_restore_pre'] = "È possibile utilizzare questo solo per ripristinare i backup che sono state esplicitamente prese in Kloxo stesso utilizzando il [b] Get Backup [/ b] scheda. Per ripristinare il normale file di dump mysql, si prega di utilizzare phpMyAdmin.";
$__information ['Domainipaddress_updateform_update_pre'] = "Questo vi permetterà di mappare una particolare ipaddress ad un dominio che è, se qualcuno accede http://Indirizzo, quindi verrà visualizzata la radice del documento del dominio configurato qui.";
$__information ['Updateform_search_engine_pre'] = "Alcuni motori possono richiedere la tua mail di conferma per la presentazione. Non inserire il tuo principale indirizzo e-mail, dal momento che è possibile ricevere messaggi di spam. Per una migliore ripetizione graduatoria l'operazione ogni 3-4 settimane ma non prima, in quanto è possibile ottenere vietato ";
$__information ['Updateform_domainpserver_pre'] = "Questi sono i server su cui verrà configurato i domini sotto questo client su. Se si modificano i valori qui, automaticamente tutti i domini verranno spostati i server corretti. Cioè, se si cambia il [b] server di posta [/ b] e di aggiornamento, quindi [b] tutti [/ b] i gli account di posta per i domini sotto questo client verranno migrati dal vecchio server al nuovo server. L'[b] dnstemplate [/ b ] è il nuovo dnstemplate che i DNS di tutti i domini saranno passati a. Quindi bisogna fare in modo che si crea un dnstemplate che riflette la nuova configurazione, quindi prevedere che a Kloxo qui. Vedere in basso per ulteriori informazioni sul server di sposta È possibile effettuare modifiche DNS di massa successivamente andando a [b] dns manager -.> ricostruire [/ b] e facendo clic su [b] update tutto [/ b], che vi impressionare il nuovo dnstemplate su tutti i domini nel conto. ";
$__information ['Sslipaddress_updateform_update_pre'] = "Per impostare un SSL per un IP address, primo upload / aggiungere un certificato SSL da <url:goback=2&a=list&c=sslcert> qui </ url>";
$__information ['Domain_addform__pre_docroot'] = "Lascia la radice vuoto documento e Kloxo utilizzerà automaticamente mydomain.com come docroot.";
$__information ['Sslcert_updateform_update_pre_admin'] = "Per assegnare questo certificato SSL a un particolare ipaddress, <url:goback=1&l[class]=pserver&l[nname]=localhost&a=list&c=ipaddress> clicca qui </ url> e poi andare in un IP address, e fare clic su scheda [b] certificato SSL [/ b], ed è possibile impostare uno di questi certificati da un particolare IP address ";
// $__information ['Sslcert_updateform_update_pre'] = "Per assegnare questo certificato SSL a un particolare ipaddress, <url:goback=2&a=list&c=ipaddress> clicca qui </ url> e poi andare in un IP address, quindi fare clic su [b scheda [/ b]] certificato SSL, ed è possibile impostare uno di questi certificati da un particolare ipaddress L'amministratore deve aver assegnato voi un ipaddress esclusivo per l'accesso a questa funzione. ";
$__information ['Sslcert_updateform_update_pre'] = "Per assegnare questo certificato SSL a un particolare ipaddress, <url:goback=2&a=list&c=ipaddress> clicca qui </ url> e poi andare in un IP address, quindi fare clic su [b] ssl certificato [/ b] scheda, ed è possibile impostare uno di questi certificati da un particolare ipaddress Per client, l'amministratore deve aver assegnato voi un ipaddress esclusivo per l'accesso a questa funzione. ";

$__information ['Domain_not_customer'] = "Per aggiungere un dominio, creare un cliente in primo luogo, ed è possibile aggiungere domini sotto di lui Per aggiungere un cliente, <URL: a. = AddForm & c = client & dta [var] = cttype & dta [val] = cliente > clicca qui </ url> ";
$__information ['Ipaddress_list__pre'] = "IP esclusiva vi permetterà di avere il controllo dedicato di un particolare ipaddress. Ciò è utile per la creazione di SSL e anche per la creazione di un ip per un dominio. Cioè, se si desidera un particolare IP per risolvere a un dominio. Per voi di avere un IPaddress esclusivo, l'amministratore dovrà impostare il client di esclusiva di un particolare ipaddress. Per configurare SSL o per mappare un IP ad un dominio, fare clic su un IPaddress, quindi fare clic su [ b] Configurare SSL [/ b] o [b] configure dominio [/ b] ";
$__information ['Clientmail_list__pre'] = "Questo elencherà il numero di messaggi inviati dai client tramite il server web o di inoltro SMTP auth negli ultimi 2 giorni. Se è un mailaccount pieno come [b] user@domain.com [ / b], allora esso rappresenta mail inviata tramite relè. Se si tratta di un semplice nome utente, allora esso rappresenta mail inviata tramite un modulo nel server web. Se si utilizza mod_php su apache, quindi tutte applicazioni web vengono eseguiti come utente [b] apache [/ b], e solo [b] apache [/ b] sarà visualizzata qui. Utilizzare suPHP su Apache, se si prevede di hosting per conto terzi. In questo modo si sarà in grado di identificare ogni client usando il suo utente di sistema. ";
$__information ['Servermail_updateform_update_pre'] = "E 'molto importante che si imposta il mio nome ad una corretta risolvibile hostname, altrimenti, molti mail server pubblici come hotmail rifiuterà mail dal tuo server. Si può avere il server di posta in esecuzione sulla porta aggiuntiva specificando qui. lasciarlo vuoto per disabilitare SMTP aggiuntivi. Le istanze Max SMTP specifica il numero massimo di processi smtp che sono ammessi. Si consiglia di impostare a qualche numero, diciamo 10, se hai trovato un'enorme quantità di spam pesantemente. Se si lascia è vuoto, verrà impostato su UNLIMITED, che è l'impostazione predefinita ";

$__information ['Updateform_switchprogram_pre'] = "Programmi di commutazione impiega un po ', in quanto ha bisogno di rimuovere il vecchio programma dal sistema".
        "E installare quello nuovo usando yum. L'registro per questo sarà disponibile nel file shell_exec.".
        "Tutte le informazioni saranno trasparente migrato.".
        "Sarà necessario attendere un minuto prima che il nuovo servizio viene riavviato correttamente. <br />".
        "Nota: Abilita 'alcuna correzione config' eseguirà alcuna azione per risolvere la configurazione - importante per la quantità enorme di domin;".
        "Allora è necessario eseguire 'sh / script / fixwe; sh / script / fixdn; sh / script / fixmail' manualmente da ssh.";

$__information ['Updateform_permalink_pre'] = "Kloxo viene fornito con configurazione permalink di default per molte applicazioni. Si prega di selezionare l'applicazione e la directory in cui è installato, e Kloxo si aggiungerà la corrispondente regola di riscrittura nella configurazione Lighty. Si prega di notare che per alcuni applicazioni, permalink vengono raggiunti tramite l'impostazione del gestore di errore 404, per esempio wordpress ";
$__information ['Weblastvisit_list__pre'] = "Questa è la lista delle ultime 50 visitatori o il numero di visitatori nelle ultime 20 ore, a seconda del valore minore. Tempo reale rappresenta il tempo in unix timestamp, ed è là in modo che è possibile ordinare con precisione . dal tempo Le corde più lunghi sono troncati per adattarsi allo schermo, e si possono vedere i valori di fondo, spostando il mouse su di loro ";
$__information ['Subweb_a_addform__pre'] = "Questo è un semplice sottodominio. Un semplice sottodominio ha solo una componente web, e non è possibile aggiungere la posta o il gestore di DNS per questo. Se volete un sottodominio completo, si prega di utilizzare il tasto [b] sottodominio [/ b] sul principale [b] domini [/ b] Percorso della pagina Il semplice del sottodominio è / home / clientname / dominio / domain.com / sottodomini / SUBDOMAINNAME ";
$__information ['Updateform_skeleton_pre'] = "Questo è l'archivio della directory scheletro che verrà copiato nella directory home di dominio quando viene creato. L'archivio verrà decompresso nella directory home di un dominio appena creato. Puoi usare [b] <% dominio%>, <% clientname%> [/ b] all'interno del file index.html, e le variabili saranno sostituite correttamente con i valori corretti ";
$__information ['Updateform_lighty_rewrite_pre'] = "Questa è la regola di riscrittura lighttpd personalizzato che verrà direttamente aggiunto al file di configurazione senza alcuna variazione. Sarà di forma [b] url.rewrite = (... [/ b]. ";
$__information ['Updateform_custom_error_pre'] = "<p>. Nota: I valori si devono fornire sono i percorsi virtuali ai file che verranno mostrati nel caso di questi errori. Esempio: / error_files/404.html </ p> ";
$__information ['Domain_updateform_ipaddress_pre'] = "<p>. Nota: Assicurarsi di apportare le modifiche necessarie alla configurazione del server dei nomi troppo </ p>";
$__information ['Client_updateform_ipaddress_pre'] = "<p>. Nota: Il pool IP disponibili è selezionato dalle macchine nel pool di server web </ p>";
$__information ['Domaintemplate_addform__pre'] = "<p>. Nota: il valore massimo a destra mostra il limite di quota corrente È possibile creare un modello con valori più che la tua quota, ma non sarà in grado di utilizzarli per creare . Domini / Clienti </ p> ";
$__information ['Spam_updateform_update_pre'] = "<p> 'score' - che può essere 1-10 -. Rappresenta il valore al quale la posta viene contrassegnato come SPAM Quindi, se si imposta su valori più bassi, più sarà posta . valori contrassegnati come spam troppo basso potrebbe portare alla mail genuini sempre classificati come spam Troppo alti valori porteranno ad elevata quantità di spam ottenere attraverso il filtro </ p> ";
$__information ['Web_updateform_enable_frontpage_flag_pre'] = "<p> La pagina password di fronte sarà la stessa di quella del l'utente del sistema (principale utente ftp) </ p>";
$__information ['Ffile_show___lx_error_log_pre'] = "Questo è il log degli errori per il tuo dominio Il contenuto di questo vi aiuterà a disturbare il tiro se si hanno problemi per quanto riguarda il dominio.";
$__information ['Installappsnapshot_list__pre'] = "Le istantanee sono la copia esatta del database e dei file della vostra applicazione in un particolare momento. È possibile ripristinare l'applicazione di una particolare istantanea, fare clic sul pulsante [b] ripristino [/ b] . ";
$__information ['Sshclient_updateform_disabled_pre'] = "Il vostro amministratore non ha abilitato l'accesso alla shell per voi Si prega di aprire un ticket di supporto se avete bisogno di accesso ssh.";
$__information ['Sshclient_updateform_warning_pre'] = "Si prega di notare che tutte le attività vengono registrate e ogni tentativo di accedere a file che non appartengono a voi porterà alla chiusura del tuo account di hosting Quindi, per favore agire in modo responsabile.";
$__information ['Ffile_show___lx_access_log_pre'] = "Questo è il log di accesso per il tuo dominio. Potete scaricare facendo clic sul [b] Download [/ b] scheda a destra. Questo file contiene informazioni su ogni singolo colpo che viene fatto per per il vostro sito web ";
$__information ['Updateform_disable_url_pre'] = "Tutti i tuoi figli erediteranno automaticamente i tuoi Disattiva parametri URL. Far valere i tuoi Disabilitare URL su di loro, basta disabilitare il loro 'possibile impostare Disattiva URL' nelle impostazioni di autorizzazione. Questo è l'URL a cui un dominio verrà reindirizzato a quando questo è disattivato. ";
$__information ['Updateform_dnstemplatelist_pre'] = "Assegnare un solo modello DNS al vostro cliente Ciò significherebbe che Kloxo non mostrerà il modello DNS selezionare la casella, mentre l'aggiunta di un dominio, che renderà meno confusione al vostro cliente.";
$__information ['Forward_a_addform__pre'] = "Gli indirizzi forward sono un elenco di indirizzi di posta elettronica a cui la posta viene trasmessa a uno copia del messaggio viene salvato nella mailaccount effettiva troppo È possibile disattivare l'archiviazione locale per <url:.. A = updateform & sa = configuration> cliccando qui </ url> ";

// Aggiunta versione 6.1.6 Kloxo TODO! Dare una corretta informazione.
$__information ['Vv_dns_srv_message'] = "Qui è possibile gestire il record SRV.";
$__information ['Vv_dns_ddns_message'] = "Qui è possibile gestire DDNS.";
$__information ['Vv_dns_mx_message'] = "Qui è possibile gestire il record MX Invio '__base__', se si vuole ottenere il dominio di base.";
$__information ['Vv_dns_ns_message'] = "Qui è possibile gestire il record NS.";
$__information ['Vv_dns_aaaa_message'] = "Qui è possibile gestire il record IPv6 Invio '__base__', se si vuole ottenere il dominio di base.";
$__information ['Vv_dns_txt_message'] = ". Usa <% dominio> se si desidera che il nome di dominio all'interno di un record TXT, ad esempio, 'v = spf1 includono: <% dominio>'.";
$__information ['Vv_dns_cname_message'] = "Qui è possibile gestire il record CNAME.";
$__information ['Vv_dns_fcname_message'] = "Qui è possibile gestire il record FCNAME [b] FCNAME [/ b] indica piena CNAME e vi permetterà di puntare un sottodominio di un dominio esterno.";
$__information ['Vv_dns_a_message'] = "Qui è possibile gestire il record Invio '__base__', se si vuole ottenere il dominio di base.";
$__information ['Vv_dns_soa_message'] = "Qui è possibile gestire il record SOA.";
$__information ['Vv_dns_rebuild_message'] = "Qui è possibile ricostruire la tua zona di dominio da un modello DNS.";

// Aggiunta Kloxo 6.1.7
// $__information ['Vv_dns_template_message'] = "[b] DNS primario e secondario [/ b] <br /> Solo i nomi host sono consentiti";
// Modificato il 6.2.0
$__information ['Vv_dns_template_message'] = "[b] DNS primario e secondario [/ b] - 'default.dns' è 'simbolico' nome di dominio se selezionando 'default' per 'DNS Nome Modello'.".
        "[B] Esempio [/ b] - 'ns1.default.dns' (su 'DNS primario') verranno convertiti in 'ns1.domain.com' per 'domain.com'";

// Cambiato Kloxo versione 6.1.6
$__information ['Vv_dns_blank_message'] = "<p> Gestore DNS </ p>";

$__emessage ['Bloccato'] = "Il tuo indirizzo è bloccato";
$__emessage ['No_server'] = "Impossibile connettersi al server.";
$__emessage ['Set_emailid'] = "preghiamo di impostare le EmailID correttamente";
$__emessage ['No_socket_connect_to_server'] = "Impossibile connettersi al server [% s]. Ciò è molto probabilmente a causa di problemi di rete sottostante. Assicurarsi che il server è accessibile da questo particolare nodo eseguendo [b] telnet schiavo-id 7779 [/ b] ";
$__emessage ['Restarting_backend'] = "Riavvio del backend Riprova dopo 30 secondi.";
$__emessage ['Quota_exceeded'] = "Quota scaduto per [% s]";
$__emessage ['License_no_ipaddress'] = "Il ipaddress pubblico [% s] di questo server non è stato trovato in nel repository licenza prega di contattare Lxlabs vendite o il rivenditore per creare una licenza per il server </ a>.";
$__emessage ['Ssh_root_password_access'] = "Non hai disattivato l'accesso basato su password per root su questo server di accesso basato su password di root non è necessario dal momento che è possibile gestire le chiavi autorizzate ssh tramite HyperVM stessa <url:.. K [class] = pserver & k [Nname] = localhost & a = updateform & sa = update & o = sshconfig> Clicca qui </ url> per configurare il server ssh ";
$__emessage ['Already_exists'] = "La risorsa del nome [% s] esiste già.";
$__emessage ['Lxguard_not_configured'] = "Lxguard per questo server non è configurato. Prega <url:k[class]=pserver&k[nname]=localhost&a=show&o=lxguard> Clicca qui per configurare Lxguard </ url> poiché è molto . importante comprendere ciò che fa Lxguard è fondamentale per la sicurezza del server, allo stesso tempo, è in grado di bloccare il proprio IPaddress di accedere al server, che può essere frustrante se non si sa che cosa sta succedendo ";
$__emessage ['Root_cannot_extract_to_existing_dir'] = "Directory hai fornito esiste già utente root non può estrarre l'archivio in una directory esistente Si prega di fornire il nome di una directory che non esiste nel sistema...";
$__emessage ['No_imagemagick'] = "Non ci sono ImageMagick nel sistema, è possibile installare imagemagick eseguendo [b] yum-y install imagemagick [/ b].";
$__emessage ['Warn_license_limit'] = "Vi sono molto vicino al limite di licenza per [% s]. Se il sistema va oltre il limite per [% s] l'interfaccia smetterà di funzionare e non sarà in grado di gestire il sistema . Si prega di aumentare la vostra licenza in client.lxlabs.com e aggiornamento da <url:o=license&a=show> cliccando qui </ url> ";
$__emessage ['File_already_exists'] = "Il file [% s] esiste già.";
$__emessage ['Contact_set_but_not_correct'] = "Il vostro Informazioni di contatto non sembra essere un indirizzo email valido <url:a=updateform&sa=information> Clicca qui per risolvere il problema </ url>.";
$__emessage ['Contact_not_set'] = "Il vostro Informazioni di contatto non è impostato correttamente <url:a=updateform&sa=information> Clicca qui per risolvere il problema </ url>.";
$__emessage ['You_have_unread_message'] = "Sei [% s] Messaggio non letto (s) <burl:a=list&c=smessage> clicca qui per leggerlo </ burl>.";
$__emessage ['You_have_unread_ticket'] = "Hai [% s] Ticket Non letto (s) <burl:a=list&c=ticket> clicca qui per leggerlo </ burl>.";
$__emessage ['Security_warning'] = "La tua password è ora impostata come una password generica che costituisce una minaccia per la sicurezza tomba favore cambia immediatamente da <url:a=updateform&sa=password> cliccando qui </ url>.";
$__emessage ['Ssh_port_not_configured'] = "La porta ssh per questo server non è impostato E 'una buona idea di cambiarlo in qualcosa di diverso da quello predefinito 22 <url:a=show&o=sshconfig> prega cliccare qui per cambiare..: </ url> Se si desidera mantenere la porta SSH al 22 e ancora evitare questo messaggio, vai alla pagina e impostare con la forza a 22, e l'avviso non verrà visualizzato di nuovo. ";
$__emessage ['System_is_updating_itself'] = "Il sistema a questo punto si sta aggiornando, e quindi non sarà in grado di apportare eventuali modifiche per pochi minuti tutte le azioni di lettura funzionano normalmente però.";
$__emessage ['System_is_locked'] = "Qualcuno ha iniziato sistema-modifica-azione su questo particolare oggetto, che è ancora in corso È solito essere in grado di apportare modifiche fino a che non è finito Tutte le azioni di lettura funzionano normalmente però...";
$__emessage ['System_is_locked_by_u'] = "È stato avviato un sistema di-modifica-azione che è ancora in corso È solito essere in grado di apportare modifiche fino a che non è finito Tutte le azioni di lettura funzionano normalmente però...";
$__emessage ['Smtp_server_not_running'] = "HyperVM Impossibile connettersi a un server SMTP su questo server. Ciò significa che HyperVM non sarà in grado di inviare delle email. Ciò è molto critica poiché HyperVM monitora la salute di tutto il cluster e invia e-mail per l'amministratore se non vi è alcun problema. Si dovrebbe fare in modo che il servizio SMTP è in esecuzione su questo server. Dopo aver riavviato il servizio SMTP, attendere 5 minuti per questo messaggio di errore a scomparire per favore, dato che i controlli HyperVM per la disponibilità del servizio solo una volta ogni 5 minuti ";
$__emessage ['Template_not_owner'] = "Tu non sei il proprietario di questo modello";
$__emessage ['Ipaddress_changed_amidst_session'] = "Indirizzo IP Modificato Tra Sessione Possibile Session Hijacking.";
$__emessage ['More_than_one_user'] = "Più di un utente è connesso a tale conto <burl:a=list&c=ssession> Clicca qui per vedere la lista delle connessioni </ burl>.";
$__emessage ['Login_error'] = "Accesso non riuscito";
$__emessage ['File_exists'] = "file (s) [% s] esiste non incolla ...";
$__emessage ['Cannot_unzip_in_root'] = "Non è possibile decomprimere i file nella root prega di specificare una directory e decomprimere in quello.";
$__emessage ['Nouser_email'] = "L'email non corrisponde dell'utente contatto Indirizzo e-mail";
$__emessage ['Session_expired'] = "Sessione scaduta";
$__emessage ['E_password'] = "Password errata";
$__emessage ['Is_demo'] = "[% s] è disattivata in versione demo.";
$__emessage ['User_create'] = "L'utente [% s] non può essere creata Prova con un nome diverso.";
$__emessage ['Switch_done'] = "Modifica i server è stato eseguito in background Ti verrà inviata una e-mail quando l'interruttore è completa.";
$__emessage ['Mis_changed'] = "Configurazione del display di cambiata con successo.";
$__emessage ['Password_sent'] = "La password è stata resettata e inviata con successo.";
$__emessage ['Added_successfully'] = "[% s] è stato aggiunto con successo.";
$__emessage ['Backup_has_been_scheduled'] = "Il backup è ora accadendo in background Riceverai una mail al tuo contatto e-mail quando è fatto.";
$__emessage ['Update_scheduled'] = "Update è ora in esecuzione in background È possibile aggiornare questa pagina per vedere se l'aggiornamento è completato correttamente.";
$__emessage ['Restore_has_been_scheduled'] = "Il ripristino è ora accadendo in background Riceverai una mail al tuo contatto e-mail quando è fatto.";
$__emessage ['Same_dns'] = "master e slave non può essere sullo stesso server.";
$__emessage ['User_exists'] = "L'utente [% s] esiste già.";
$__emessage ['Mysql_error'] = "Errore Mysql, database Said: [% s]";
$__emessage ['This_domain_does_not_resolve_to_this_ip'] = "Per associare un indirizzo IP ad un dominio, il dominio deve eseguire il ping allo stesso IP, in caso contrario, il dominio smetterà di funzionare. Il dominio si sta cercando di mappare questo IP, non risolve indietro al PI, e quindi non può essere impostato come dominio predefinito per l'IP ";
$__emessage ['Dns_conflict'] = "Il dominio non è stato inserito a causa di un errore nelle impostazioni dns Controlla la tua modello DNS e verificare il messaggio dal server DNS è stato [% s].";
$__emessage ['Add_without_www'] = "Si dovrebbe aggiungere solo il dominio principale in forma di domain.com. L'[b] www [/ b] sottodominio verrà aggiunto automaticamente ad esso. Si consiglia di non aggiungere [b] www [/ b] durante la creazione di un dominio ";
$__emessage ['Could_not_connect_to_db'] = "Non può connettersi a database:.. È stato registrato l'errore prega di contattare l'amministratore";
$__emessage ['E_no_dbadmin_entries'] = "Non ci sono voci di amministratore di database configurati per questo particolare server Contattare l'amministratore per impostarle.";
$__emessage ['Please_add_one_domain_for_owner_mode'] = "È necessario avere almeno un dominio se si desidera passare alla modalità di proprietario del dominio. È possibile aggiungere un dominio da <url:a=addform&c=domain> cliccando qui </ url>. ";
$__emessage ['E_no_dbadmin_entries_admin'] = "Non ci sono voci di amministratore di database configurati per questo particolare server. Devi andare alla sezione del server per questo server, quindi fare clic sul link dbadmin, e aggiungere l'utente admin e password del database per questo particolare, ma il tipo di database ";
$__emessage ['Mail_server_name_not_set'] = "Il nome di identificazione per il server di posta non è impostato Questo significa che molti server di posta pubblici come hotmail rifiuterà mail dal server Cliccare <url:.. K [class] = pserver & k [Nname] = localhost & a = updateform & sa = update & o = servermail> qui per impostare </ url>";
$__emessage ['Dns_template_inconsistency'] = "Il modello DNS che hai scelto non è coerente con la scelta dei server., Ad esempio, potrebbe essere che l'IP address in DNS non è affatto trovato nel web server. Torna indietro e creare un modello di dns che ha i parametri coerenti con la configurazione del server. ";
$__emessage ['Adding_cron_failed'] = "Aggiungere crontab non è riuscito a causa di [% s] Si prega di eliminarlo e aggiungerlo di nuovo.";
$__emessage ['Se_submit_running_background'] = "Search Engine Submission è in esecuzione in background Ti verrà inviato un messaggio al tuo indirizzo email di contatto quando è fatto.";
$__emessage ['Err_no_dns_template'] = "Non ci sono modelli DNS nel sistema. Devi avere almeno un DNS template per aggiungere un dominio / client. Clicca <url:a=addform&c=dnstemplate> qui per aggiungere una dnstemplate. </ url> </ p> ";
$__emessage ['Certificate_key_file_empty'] = "Il certificato e il file chiave che avete scelto sono vuoti È necessario creare prima o caricarli prima di abilitare SSL.";

// Stampa sulla Kloxo 6.1.7
// Da mustafa.ramadhan @ lxcenter.org

$__information ['Webserver_config'] =
        "[B] PHP Branch [/ b] - Versione Php Branch-based -".
                "PHP-FPM per 'php52' potrebbe non funzionar;".
                "Risultato del test con 'php-v' via ssh per scoprire errore (moduli di solito incompatibili) <br />".
                "- Meglio riavvio dopo il cambiamento, soprattutto se si usa Lighttpd, Nginx o Apache con 'php-fpm' come 'php-tipo' <br />".
        "[B] PHP Tipo [/ b] - Process-based (httpd-prefork/-itk), filo-based (httpd-worker/-event) e".
                "Ambiente sicuro (suphp/php-fpm/ruid2/itk/fcgid) <br />".
        "[B] Apache Memory Optimize [/ b] - Ottimizzare l'utilizzo della memoria -".
                "Impostare la metà dell'importo per [b] nginx / lighttpd-proxy [/ b;".
                "'Default' scegliere se selezionare 'php-fpm' on 'Php Tipo' <br />".
        "[B] MySQL Convert [/ b] - MyISAM (minore utilizzo di memori; risparmiare 100-200 MB) e".
                "InnoDB (maggiori prestazioni) <br />".
        "[B] Fix 'proprietà' E 'Permessi' [/ b] - Prevenire '500 Errore interno del server 'in ambiente sicuro".
        "<br /> <br /> * Aggiungi '[b] AddHandler application/x-httpd-php52. Php [/ b]' in. Htaccess per l'utilizzo di PHP 5.2 su dual-php con php 5.3/5.4 come php primario" .
        "<br /> * Se si seleziona [b] suPHP / suphp_worker / suphp_event [/ b] e quindi selezionare 'fix-ALL' per evitare '500 Errore interno del server '";
// Contenuti Lingua di 656 °
// Da Andrew Ying
$__emessage ['Document_root_may_not_contain_spaces'] = "La radice del documento non può contenere alcun spazio alla fine o prima della barra si prega di controllare e inviare di nuovo.";

// Stampa sulla Kloxo 6.2.0
// Da mustafa.ramadhan @ lxcenter.org

$__information ['Php_config'] = "Installazione xcache / ioncube / Zend / Suhosin rpm tramite yum. Installando questo modulo dipendono ramo php e la versione installata sul sistema.".
        "[B] Esempio [/ b]:. Quando si utilizza ramo php53u, l'installazione con 'yum install php53u-xcache' Prova 'php-m' per fare in modo";

$__information ['Reverse_dns'] = "reverse DNS funzionano solo per la classe C (256 ips) o più";
