<?php
$var = array (
  'quotavar' => 
  array (
    'mysqldb' => 
    array (
      'mysqldb_usage' => 0,
    ),
    'mssqldb' => 
    array (
      'mssqldb_usage' => 0,
    ),
    'lxclient' => 
    array (
      'logo_manage_flag' => 0,
    ),
    'rubyrails' => 
    array (
      'rubyfcgiprocess_num' => 0,
    ),
    'ftpuser' => 
    array (
      'logo_manage_flag' => 0,
    ),
    'pserver' => 
    array (
      'logo_manage_flag' => 0,
    ),
    'mailaccount' => 
    array (
      'logo_manage_flag' => 0,
      'maildisk_usage' => 1,
      'autoresponder_num' => 2,
    ),
    'mmail' => 
    array (
      'logo_manage_flag' => 0,
      'maildisk_usage' => 1,
      'autoresponder_num' => 2,
      'mailaccount_num' => 3,
      'mailinglist_num' => 4,
    ),
    'uuser' => 
    array (
      'disk_usage' => 0,
      'logo_manage_flag' => 1,
    ),
    'web' => 
    array (
      'totaldisk_usage' => 0,
      'ssl_flag' => 1,
      'rubyfcgiprocess_num' => 2,
      'disk_usage' => 3,
      'logo_manage_flag' => 4,
      'ftpuser_num' => 5,
      'frontpage_flag' => 6,
      'php_manage_flag' => 7,
      'inc_flag' => 8,
      'awstats_flag' => 9,
      'easyinstaller_flag' => 10,
      'modperl_flag' => 11,
      'cgi_flag' => 12,
      'php_flag' => 13,
      'phpunsafe_flag' => 14,
      'subweb_a_num' => 15,
      'dotnet_flag' => 16,
      'cron_num' => 17,
      'cron_minute_flag' => 18,
      'cron_manage_flag' => 19,
      'phpfcgi_flag' => 20,
      'rubyrails_num' => 21,
      'phpfcgiprocess_num' => 22,
    ),
    'lxbackup' => 
    array (
      'backupschedule_flag' => 0,
    ),
    'domain' => 
    array (
      'traffic_usage' => 0,
      'totaldisk_usage' => 1,
      'ssl_flag' => 2,
      'rubyfcgiprocess_num' => 3,
      'disk_usage' => 4,
      'logo_manage_flag' => 24,
      'ftpuser_num' => 37,
      'frontpage_flag' => 7,
      'php_manage_flag' => 8,
      'inc_flag' => 9,
      'awstats_flag' => 10,
      'easyinstaller_flag' => 11,
      'modperl_flag' => 12,
      'cgi_flag' => 13,
      'php_flag' => 14,
      'phpunsafe_flag' => 15,
      'subweb_a_num' => 16,
      'dotnet_flag' => 17,
      'cron_num' => 18,
      'cron_minute_flag' => 19,
      'cron_manage_flag' => 20,
      'phpfcgi_flag' => 21,
      'rubyrails_num' => 22,
      'phpfcgiprocess_num' => 23,
      'maildisk_usage' => 25,
      'autoresponder_num' => 26,
      'mailaccount_num' => 27,
      'mailinglist_num' => 28,
      'mysqldb_usage' => 29,
      'mssqldb_usage' => 30,
      'backupschedule_flag' => 31,
      'traffic_last_usage' => 32,
      'backup_flag' => 33,
      'dns_manage_flag' => 34,
      'mysqldb_num' => 35,
      'mssqldb_num' => 36,
      'addondomain_num' => 38,
    ),
    'domaina' => 
    array (
      'traffic_usage' => 0,
      'totaldisk_usage' => 1,
      'ssl_flag' => 2,
      'rubyfcgiprocess_num' => 3,
      'disk_usage' => 4,
      'logo_manage_flag' => 24,
      'ftpuser_num' => 37,
      'frontpage_flag' => 7,
      'php_manage_flag' => 8,
      'inc_flag' => 9,
      'awstats_flag' => 10,
      'easyinstaller_flag' => 11,
      'modperl_flag' => 12,
      'cgi_flag' => 13,
      'php_flag' => 14,
      'phpunsafe_flag' => 15,
      'subweb_a_num' => 16,
      'dotnet_flag' => 17,
      'cron_num' => 18,
      'cron_minute_flag' => 19,
      'cron_manage_flag' => 20,
      'phpfcgi_flag' => 21,
      'rubyrails_num' => 22,
      'phpfcgiprocess_num' => 23,
      'maildisk_usage' => 25,
      'autoresponder_num' => 26,
      'mailaccount_num' => 27,
      'mailinglist_num' => 28,
      'mysqldb_usage' => 29,
      'mssqldb_usage' => 30,
      'backupschedule_flag' => 31,
      'traffic_last_usage' => 32,
      'backup_flag' => 33,
      'dns_manage_flag' => 34,
      'mysqldb_num' => 35,
      'mssqldb_num' => 36,
      'addondomain_num' => 38,
    ),
    'subdomain' => 
    array (
      'traffic_usage' => 0,
      'totaldisk_usage' => 1,
      'ssl_flag' => 2,
      'rubyfcgiprocess_num' => 3,
      'disk_usage' => 4,
      'logo_manage_flag' => 24,
      'ftpuser_num' => 37,
      'frontpage_flag' => 7,
      'php_manage_flag' => 8,
      'inc_flag' => 9,
      'awstats_flag' => 10,
      'easyinstaller_flag' => 11,
      'modperl_flag' => 12,
      'cgi_flag' => 13,
      'php_flag' => 14,
      'phpunsafe_flag' => 15,
      'subweb_a_num' => 16,
      'dotnet_flag' => 17,
      'cron_num' => 18,
      'cron_minute_flag' => 19,
      'cron_manage_flag' => 20,
      'phpfcgi_flag' => 21,
      'rubyrails_num' => 22,
      'phpfcgiprocess_num' => 23,
      'maildisk_usage' => 25,
      'autoresponder_num' => 26,
      'mailaccount_num' => 27,
      'mailinglist_num' => 28,
      'mysqldb_usage' => 29,
      'mssqldb_usage' => 30,
      'backupschedule_flag' => 31,
      'traffic_last_usage' => 32,
      'backup_flag' => 33,
      'dns_manage_flag' => 34,
      'mysqldb_num' => 35,
      'mssqldb_num' => 36,
      'addondomain_num' => 38,
    ),
    'client' => 
    array (
      'pserver_num' => 0,
      'client_num' => 1,
      'maindomain_num' => 2,
      'domain_num' => 3,
      'subdomain_num' => 4,
      'clientdisk_usage' => 5,
      'domain_add_flag' => 6,
      'can_change_limit_flag' => 7,
      'can_set_disabled_flag' => 8,
      'can_change_password_flag' => 9,
      'document_root_flag' => 10,
      'runstats_flag' => 11,
      'traffic_usage' => 12,
      'totaldisk_usage' => 13,
      'ssl_flag' => 14,
      'rubyfcgiprocess_num' => 15,
      'disk_usage' => 16,
      'logo_manage_flag' => 36,
      'ftpuser_num' => 49,
      'frontpage_flag' => 19,
      'php_manage_flag' => 20,
      'inc_flag' => 21,
      'awstats_flag' => 22,
      'easyinstaller_flag' => 23,
      'modperl_flag' => 24,
      'cgi_flag' => 25,
      'php_flag' => 26,
      'phpunsafe_flag' => 27,
      'subweb_a_num' => 28,
      'dotnet_flag' => 29,
      'cron_num' => 30,
      'cron_minute_flag' => 31,
      'cron_manage_flag' => 32,
      'phpfcgi_flag' => 33,
      'rubyrails_num' => 34,
      'phpfcgiprocess_num' => 35,
      'maildisk_usage' => 37,
      'autoresponder_num' => 38,
      'mailaccount_num' => 39,
      'mailinglist_num' => 40,
      'mysqldb_usage' => 41,
      'mssqldb_usage' => 42,
      'backupschedule_flag' => 43,
      'traffic_last_usage' => 44,
      'backup_flag' => 45,
      'dns_manage_flag' => 46,
      'mysqldb_num' => 47,
      'mssqldb_num' => 48,
      'addondomain_num' => 50,
      'webhosting_flag' => 51,
    ),
    'node' => 
    array (
      'pserver_num' => 0,
      'client_num' => 1,
      'maindomain_num' => 2,
      'domain_num' => 3,
      'subdomain_num' => 4,
      'clientdisk_usage' => 5,
      'domain_add_flag' => 6,
      'can_change_limit_flag' => 7,
      'can_set_disabled_flag' => 8,
      'can_change_password_flag' => 9,
      'document_root_flag' => 10,
      'runstats_flag' => 11,
      'traffic_usage' => 12,
      'totaldisk_usage' => 13,
      'ssl_flag' => 14,
      'rubyfcgiprocess_num' => 15,
      'disk_usage' => 16,
      'logo_manage_flag' => 36,
      'ftpuser_num' => 49,
      'frontpage_flag' => 19,
      'php_manage_flag' => 20,
      'inc_flag' => 21,
      'awstats_flag' => 22,
      'easyinstaller_flag' => 23,
      'modperl_flag' => 24,
      'cgi_flag' => 25,
      'php_flag' => 26,
      'phpunsafe_flag' => 27,
      'subweb_a_num' => 28,
      'dotnet_flag' => 29,
      'cron_num' => 30,
      'cron_minute_flag' => 31,
      'cron_manage_flag' => 32,
      'phpfcgi_flag' => 33,
      'rubyrails_num' => 34,
      'phpfcgiprocess_num' => 35,
      'maildisk_usage' => 37,
      'autoresponder_num' => 38,
      'mailaccount_num' => 39,
      'mailinglist_num' => 40,
      'mysqldb_usage' => 41,
      'mssqldb_usage' => 42,
      'backupschedule_flag' => 43,
      'traffic_last_usage' => 44,
      'backup_flag' => 45,
      'dns_manage_flag' => 46,
      'mysqldb_num' => 47,
      'mssqldb_num' => 48,
      'addondomain_num' => 50,
      'webhosting_flag' => 51,
    ),
    'superclient' => 
    array (
      'node_num' => 0,
      'pserver_num' => 1,
      'client_num' => 2,
      'maindomain_num' => 3,
      'domain_num' => 4,
      'subdomain_num' => 5,
      'clientdisk_usage' => 6,
      'domain_add_flag' => 7,
      'can_change_limit_flag' => 8,
      'can_set_disabled_flag' => 9,
      'can_change_password_flag' => 10,
      'document_root_flag' => 11,
      'runstats_flag' => 12,
      'traffic_usage' => 13,
      'totaldisk_usage' => 14,
      'ssl_flag' => 15,
      'rubyfcgiprocess_num' => 16,
      'disk_usage' => 17,
      'logo_manage_flag' => 37,
      'ftpuser_num' => 50,
      'frontpage_flag' => 20,
      'php_manage_flag' => 21,
      'inc_flag' => 22,
      'awstats_flag' => 23,
      'easyinstaller_flag' => 24,
      'modperl_flag' => 25,
      'cgi_flag' => 26,
      'php_flag' => 27,
      'phpunsafe_flag' => 28,
      'subweb_a_num' => 29,
      'dotnet_flag' => 30,
      'cron_num' => 31,
      'cron_minute_flag' => 32,
      'cron_manage_flag' => 33,
      'phpfcgi_flag' => 34,
      'rubyrails_num' => 35,
      'phpfcgiprocess_num' => 36,
      'maildisk_usage' => 38,
      'autoresponder_num' => 39,
      'mailaccount_num' => 40,
      'mailinglist_num' => 41,
      'mysqldb_usage' => 42,
      'mssqldb_usage' => 43,
      'backupschedule_flag' => 44,
      'traffic_last_usage' => 45,
      'backup_flag' => 46,
      'dns_manage_flag' => 47,
      'mysqldb_num' => 48,
      'mssqldb_num' => 49,
      'addondomain_num' => 51,
      'webhosting_flag' => 52,
    ),
  ),
  'fieldvar' => 
  array (
    'license' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_licensecom_b' => 3,
      'text_license_content' => 4,
    ),
    'loginattempt' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'count' => 3,
      'client_name' => 4,
    ),
    'blockedip' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ipaddress' => 3,
    ),
    'allowedip' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ipaddress' => 3,
    ),
    'ssession' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'cttype' => 3,
      'ip_address' => 4,
      'timeout' => 5,
      'last_access' => 6,
      'logintime' => 7,
      'ser_http_vars' => 8,
      'ser_ssession_vars' => 9,
      'tsessionid' => 10,
      'auxiliary_id' => 11,
      'ser_ssl_param' => 12,
      'consuming_parent' => 13,
    ),
    'utmp' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ssession_name' => 3,
      'cttype' => 4,
      'logintime' => 5,
      'timeout' => 6,
      'logouttime' => 7,
      'ip_address' => 8,
      'logoutreason' => 9,
      'auxiliary_id' => 10,
      'consuming_parent' => 11,
    ),
    'lxupdate' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'schedule' => 3,
    ),
    'version' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'major' => 3,
      'minor' => 4,
      'releasen' => 5,
      'extra' => 6,
    ),
    'notification' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_notflag_b' => 3,
      'text_newsubject' => 4,
      'text_newaccountmessage' => 5,
      'fromaddress' => 6,
      'coma_class_list' => 7,
    ),
    'ticketconfig' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ticketid' => 3,
      'ser_category_list_a' => 4,
      'mail_account' => 5,
      'mail_server' => 6,
      'mail_password' => 7,
      'mail_period' => 8,
      'mail_enable' => 9,
      'mail_ssl_flag' => 10,
    ),
    'ticket' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'password' => 3,
      'escalate' => 4,
      'realpass' => 5,
      'status' => 6,
      'cpstatus' => 7,
      'state' => 8,
      'priority' => 9,
      'responsible' => 10,
      'made_by' => 11,
      'sent_to' => 12,
      'date_modified' => 13,
      'unread_flag' => 14,
      'history_num' => 15,
      'subject' => 16,
      'category' => 17,
      'ddate' => 18,
      'mail_messageid' => 19,
    ),
    'smessage' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'made_by' => 3,
      'text_readby_cmlist' => 4,
      'text_sent_to_cmlist' => 5,
      'subject' => 6,
      'text_description' => 7,
      'category' => 8,
      'ddate' => 9,
    ),
    'tickethistory' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'made_by' => 3,
      'state_from' => 4,
      'state' => 5,
      'text_reason' => 6,
      'ddate' => 7,
      'from_ad' => 8,
    ),
    'interface_template' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_domain_show_list' => 3,
      'ser_client_show_list' => 4,
      'ser_vps_show_list' => 5,
    ),
    'general' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_generalmisc_b' => 3,
      'ser_helpdeskcategory_a' => 4,
      'ser_reversedns_b' => 5,
      'ser_selfbackupparam_b' => 6,
      'ser_hackbuttonconfig_b' => 7,
      'ser_customaction_b' => 8,
      'text_maintenance_message' => 9,
      'ser_portconfig_b' => 10,
      'ser_kloxoconfig_b' => 11,
      'ser_browsebackup_b' => 12,
      'login_pre' => 13,
      'ser_lxadminconfig_b' => 14,
      'disable_admin' => 15,
    ),
    'sslcert' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'upload_status' => 3,
      'certname' => 4,
      'syncserver' => 5,
      'ser_ssl_data_b' => 6,
      'text_crt_content' => 7,
      'text_key_content' => 8,
      'text_csr_content' => 9,
      'text_ca_content' => 10,
      'oldsyncserver' => 11,
      'olddeleteflag' => 12,
    ),
    'ndsktoolbar' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ddate' => 3,
      'ttype' => 4,
      'description' => 5,
      'external' => 6,
      'vpsparent_clname' => 7,
      'url' => 8,
    ),
    'ndskshortcut' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ddate' => 3,
      'ttype' => 4,
      'sortid' => 5,
      'separatorid' => 6,
      'description' => 7,
      'external' => 8,
      'vpsparent_clname' => 9,
      'url' => 10,
    ),
    'sshconfig' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ssh_port' => 3,
      'without_password_flag' => 4,
      'disable_password_flag' => 5,
      'config_flag' => 6,
    ),
    'rdnsrange' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'firstip' => 3,
      'lastip' => 4,
    ),
    'lxguard' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'configure_flag' => 3,
      'disablehit' => 4,
      'syncserver' => 5,
      'oldsyncserver' => 6,
      'olddeleteflag' => 7,
    ),
    'lxguardhit' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'access' => 3,
      'service' => 4,
      'ddate' => 5,
      'ipaddress' => 6,
      'user' => 7,
      'syncserver' => 8,
      'oldsyncserver' => 9,
      'olddeleteflag' => 10,
    ),
    'lxguardwhitelist' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ipaddress' => 3,
      'syncserver' => 4,
      'oldsyncserver' => 5,
      'olddeleteflag' => 6,
    ),
    'customaction' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'class' => 3,
      'action' => 4,
      'subaction' => 5,
      'exec' => 6,
      'where_to_exec' => 7,
    ),
    'custombutton' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'status' => 3,
      'class' => 4,
      'title' => 5,
      'url' => 6,
      'description' => 7,
    ),
    'skipbackup' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'clname' => 3,
    ),
    'actionlog' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'login' => 3,
      'loginclname' => 4,
      'auxiliary_id' => 5,
      'ipaddress' => 6,
      'class' => 7,
      'objectname' => 8,
      'action' => 9,
      'subaction' => 10,
      'ddate' => 11,
    ),
    'module' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'status' => 3,
    ),
    'sp_specialplay' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_specialplay_b' => 3,
    ),
    'sp_childspecialplay' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_specialplay_b' => 3,
    ),
    'sp_lstclass' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_lst_client_list' => 3,
      'ser_lst_vps_list' => 4,
    ),
    'clienttemplate' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_priv' => 3,
      'share_status' => 4,
      'disable_per' => 5,
      'skin_name' => 6,
      'description' => 7,
      'ddate' => 8,
      'ser_listpriv' => 9,
      'ttype' => 10,
      'ser_dnstemplate_list' => 11,
    ),
    'resourceplan' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'realname' => 3,
      'ser_priv' => 4,
      'description' => 5,
      'ddate' => 6,
      'ser_listpriv' => 7,
      'ser_dnstemplate_list' => 8,
      'status' => 9,
      'disable_per' => 10,
    ),
    'domaintemplate' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_priv' => 3,
      'share_status' => 4,
      'disable_per' => 5,
      'skin_name' => 6,
      'description' => 7,
      'ddate' => 8,
      'ser_listpriv' => 9,
      'ttype' => 10,
      'ser_dnstemplate_list' => 11,
      'dnstemplate' => 12,
      'ipaddress' => 13,
      'redirect_domain' => 14,
      'catchall' => 15,
    ),
    'dnstemplate' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_mx_rec_a' => 3,
      'ser_ns_rec_a' => 4,
      'ser_a_rec_a' => 5,
      'ser_cn_rec_a' => 6,
      'ser_txt_rec_a' => 7,
      'ttl' => 8,
      'soanameserver' => 9,
      'zone_type' => 10,
      'ser_dns_record_a' => 11,
      'webipaddress' => 12,
      'mmailipaddress' => 13,
    ),
    'serverweb' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'php_type' => 3,
    ),
    'watchdog' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'servicename' => 3,
      'syncserver' => 4,
      'port' => 5,
      'action' => 6,
      'status' => 7,
      'added_by_system' => 8,
      'oldsyncserver' => 9,
      'olddeleteflag' => 10,
    ),
    'client' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_pserver_num' => 3,
      'used_q_pserver_num' => 4,
      'priv_q_client_num' => 5,
      'used_q_client_num' => 6,
      'priv_q_maindomain_num' => 7,
      'used_q_maindomain_num' => 8,
      'priv_q_domain_num' => 9,
      'used_q_domain_num' => 10,
      'priv_q_subdomain_num' => 11,
      'used_q_subdomain_num' => 12,
      'priv_q_clientdisk_usage' => 13,
      'used_q_clientdisk_usage' => 14,
      'priv_q_domain_add_flag' => 15,
      'used_q_domain_add_flag' => 16,
      'priv_q_can_change_limit_flag' => 17,
      'used_q_can_change_limit_flag' => 18,
      'priv_q_can_set_disabled_flag' => 19,
      'used_q_can_set_disabled_flag' => 20,
      'priv_q_can_change_password_flag' => 21,
      'used_q_can_change_password_flag' => 22,
      'priv_q_document_root_flag' => 23,
      'used_q_document_root_flag' => 24,
      'priv_q_runstats_flag' => 25,
      'used_q_runstats_flag' => 26,
      'priv_q_traffic_usage' => 27,
      'used_q_traffic_usage' => 28,
      'priv_q_totaldisk_usage' => 29,
      'used_q_totaldisk_usage' => 30,
      'priv_q_ssl_flag' => 31,
      'used_q_ssl_flag' => 32,
      'priv_q_rubyfcgiprocess_num' => 33,
      'used_q_rubyfcgiprocess_num' => 34,
      'priv_q_disk_usage' => 35,
      'used_q_disk_usage' => 36,
      'priv_q_logo_manage_flag' => 37,
      'used_q_logo_manage_flag' => 38,
      'priv_q_ftpuser_num' => 39,
      'used_q_ftpuser_num' => 40,
      'priv_q_frontpage_flag' => 41,
      'used_q_frontpage_flag' => 42,
      'priv_q_php_manage_flag' => 43,
      'used_q_php_manage_flag' => 44,
      'priv_q_inc_flag' => 45,
      'used_q_inc_flag' => 46,
      'priv_q_awstats_flag' => 47,
      'used_q_awstats_flag' => 48,
      'priv_q_easyinstaller_flag' => 49,
      'used_q_easyinstaller_flag' => 50,
      'priv_q_modperl_flag' => 51,
      'used_q_modperl_flag' => 52,
      'priv_q_cgi_flag' => 53,
      'used_q_cgi_flag' => 54,
      'priv_q_php_flag' => 55,
      'used_q_php_flag' => 56,
      'priv_q_phpunsafe_flag' => 57,
      'used_q_phpunsafe_flag' => 58,
      'priv_q_subweb_a_num' => 59,
      'used_q_subweb_a_num' => 60,
      'priv_q_dotnet_flag' => 61,
      'used_q_dotnet_flag' => 62,
      'priv_q_cron_num' => 63,
      'used_q_cron_num' => 64,
      'priv_q_cron_minute_flag' => 65,
      'used_q_cron_minute_flag' => 66,
      'priv_q_cron_manage_flag' => 67,
      'used_q_cron_manage_flag' => 68,
      'priv_q_phpfcgi_flag' => 69,
      'used_q_phpfcgi_flag' => 70,
      'priv_q_rubyrails_num' => 71,
      'used_q_rubyrails_num' => 72,
      'priv_q_phpfcgiprocess_num' => 73,
      'used_q_phpfcgiprocess_num' => 74,
      'priv_q_maildisk_usage' => 77,
      'used_q_maildisk_usage' => 78,
      'priv_q_autoresponder_num' => 79,
      'used_q_autoresponder_num' => 80,
      'priv_q_mailaccount_num' => 81,
      'used_q_mailaccount_num' => 82,
      'priv_q_mailinglist_num' => 83,
      'used_q_mailinglist_num' => 84,
      'priv_q_mysqldb_usage' => 85,
      'used_q_mysqldb_usage' => 86,
      'priv_q_mssqldb_usage' => 87,
      'used_q_mssqldb_usage' => 88,
      'priv_q_backupschedule_flag' => 89,
      'used_q_backupschedule_flag' => 90,
      'priv_q_traffic_last_usage' => 91,
      'used_q_traffic_last_usage' => 92,
      'priv_q_backup_flag' => 93,
      'used_q_backup_flag' => 94,
      'priv_q_dns_manage_flag' => 95,
      'used_q_dns_manage_flag' => 96,
      'priv_q_mysqldb_num' => 97,
      'used_q_mysqldb_num' => 98,
      'priv_q_mssqldb_num' => 99,
      'used_q_mssqldb_num' => 100,
      'priv_q_addondomain_num' => 103,
      'used_q_addondomain_num' => 104,
      'priv_q_webhosting_flag' => 105,
      'used_q_webhosting_flag' => 106,
      'realname' => 107,
      'add_address' => 108,
      'add_city' => 109,
      'add_country' => 110,
      'add_telephone' => 111,
      'add_fax' => 112,
      'password' => 113,
      'cpstatus' => 114,
      'demo_status' => 115,
      'contactemail' => 116,
      'text_comment' => 117,
      'disable_per' => 118,
      'ser_hpfilter' => 119,
      'ddate' => 120,
      'ser_dskhistory' => 121,
      'ser_dskshortcut_a' => 122,
      'interface_template' => 123,
      'ser_boxpos' => 124,
      'dialogsize' => 125,
      'cttype' => 126,
      'ser_listpriv' => 128,
      'skeletonarchive' => 129,
      'ser_dnstemplate_list' => 130,
      'state' => 131,
      'status' => 132,
      'disable_reason' => 133,
      'disable_url' => 134,
      'template_used' => 135,
      'username' => 136,
      'realpass' => 137,
      'shell' => 138,
      'default_domain' => 139,
      'resourceplan_used' => 140,
      'websyncserver' => 141,
      'coma_dnssyncserver_list' => 142,
      'mmailsyncserver' => 143,
      'mysqldbsyncserver' => 144,
      'syncserver' => 145,
      'cron_mailto' => 146,
      'dnstemplate_name' => 147,
      'corerootdir' => 148,
      'disable_system_flag' => 149,
      'oldsyncserver' => 150,
      'olddeleteflag' => 151,
    ),
    'auxiliary' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'realname' => 3,
      'add_address' => 4,
      'add_city' => 5,
      'add_country' => 6,
      'add_telephone' => 7,
      'add_fax' => 8,
      'password' => 9,
      'cpstatus' => 10,
      'demo_status' => 11,
      'contactemail' => 12,
      'text_comment' => 13,
      'disable_per' => 14,
      'ser_hpfilter' => 15,
      'ddate' => 16,
      'ser_dskhistory' => 17,
      'ser_dskshortcut_a' => 18,
      'interface_template' => 19,
      'ser_boxpos' => 20,
      'dialogsize' => 21,
      'status' => 22,
      'realpass' => 23,
      'delete_flag' => 24,
      'pserver_flag' => 25,
    ),
    'domaintraffic' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ddate' => 3,
      'oldtimestamp' => 4,
      'timestamp' => 5,
      'webtraffic_usage' => 6,
      'mailtraffic_usage' => 7,
      'ftptraffic_usage' => 8,
      'traffic_usage' => 9,
    ),
    'addondomain' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ttype' => 3,
      'destinationdir' => 4,
      'mail_flag' => 5,
    ),
    'dirprotect' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'syncserver' => 3,
      'authname' => 4,
      'subweb' => 5,
      'path' => 6,
      'status' => 7,
      'ser_diruser_a' => 8,
      'oldsyncserver' => 9,
      'olddeleteflag' => 10,
    ),
    'dns' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_mx_rec_a' => 3,
      'ser_ns_rec_a' => 4,
      'ser_a_rec_a' => 5,
      'ser_cn_rec_a' => 6,
      'ser_txt_rec_a' => 7,
      'ttl' => 8,
      'soanameserver' => 9,
      'zone_type' => 10,
      'ser_dns_record_a' => 11,
      'syncserver' => 12,
      'serial' => 13,
      'oldsyncserver' => 14,
      'olddeleteflag' => 15,
    ),
    'domain' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_traffic_usage' => 3,
      'used_q_traffic_usage' => 4,
      'priv_q_totaldisk_usage' => 5,
      'used_q_totaldisk_usage' => 6,
      'priv_q_ssl_flag' => 7,
      'used_q_ssl_flag' => 8,
      'priv_q_rubyfcgiprocess_num' => 9,
      'used_q_rubyfcgiprocess_num' => 10,
      'priv_q_disk_usage' => 11,
      'used_q_disk_usage' => 12,
      'priv_q_logo_manage_flag' => 13,
      'used_q_logo_manage_flag' => 14,
      'priv_q_ftpuser_num' => 15,
      'used_q_ftpuser_num' => 16,
      'priv_q_frontpage_flag' => 17,
      'used_q_frontpage_flag' => 18,
      'priv_q_php_manage_flag' => 19,
      'used_q_php_manage_flag' => 20,
      'priv_q_inc_flag' => 21,
      'used_q_inc_flag' => 22,
      'priv_q_awstats_flag' => 23,
      'used_q_awstats_flag' => 24,
      'priv_q_easyinstaller_flag' => 25,
      'used_q_easyinstaller_flag' => 26,
      'priv_q_modperl_flag' => 27,
      'used_q_modperl_flag' => 28,
      'priv_q_cgi_flag' => 29,
      'used_q_cgi_flag' => 30,
      'priv_q_php_flag' => 31,
      'used_q_php_flag' => 32,
      'priv_q_phpunsafe_flag' => 33,
      'used_q_phpunsafe_flag' => 34,
      'priv_q_subweb_a_num' => 35,
      'used_q_subweb_a_num' => 36,
      'priv_q_dotnet_flag' => 37,
      'used_q_dotnet_flag' => 38,
      'priv_q_cron_num' => 39,
      'used_q_cron_num' => 40,
      'priv_q_cron_minute_flag' => 41,
      'used_q_cron_minute_flag' => 42,
      'priv_q_cron_manage_flag' => 43,
      'used_q_cron_manage_flag' => 44,
      'priv_q_phpfcgi_flag' => 45,
      'used_q_phpfcgi_flag' => 46,
      'priv_q_rubyrails_num' => 47,
      'used_q_rubyrails_num' => 48,
      'priv_q_phpfcgiprocess_num' => 49,
      'used_q_phpfcgiprocess_num' => 50,
      'priv_q_maildisk_usage' => 53,
      'used_q_maildisk_usage' => 54,
      'priv_q_autoresponder_num' => 55,
      'used_q_autoresponder_num' => 56,
      'priv_q_mailaccount_num' => 57,
      'used_q_mailaccount_num' => 58,
      'priv_q_mailinglist_num' => 59,
      'used_q_mailinglist_num' => 60,
      'priv_q_mysqldb_usage' => 61,
      'used_q_mysqldb_usage' => 62,
      'priv_q_mssqldb_usage' => 63,
      'used_q_mssqldb_usage' => 64,
      'priv_q_backupschedule_flag' => 65,
      'used_q_backupschedule_flag' => 66,
      'priv_q_traffic_last_usage' => 67,
      'used_q_traffic_last_usage' => 68,
      'priv_q_backup_flag' => 69,
      'used_q_backup_flag' => 70,
      'priv_q_dns_manage_flag' => 71,
      'used_q_dns_manage_flag' => 72,
      'priv_q_mysqldb_num' => 73,
      'used_q_mysqldb_num' => 74,
      'priv_q_mssqldb_num' => 75,
      'used_q_mssqldb_num' => 76,
      'priv_q_addondomain_num' => 79,
      'used_q_addondomain_num' => 80,
      'realname' => 81,
      'add_address' => 82,
      'add_city' => 83,
      'add_country' => 84,
      'add_telephone' => 85,
      'add_fax' => 86,
      'password' => 87,
      'cpstatus' => 88,
      'demo_status' => 89,
      'contactemail' => 90,
      'text_comment' => 91,
      'disable_per' => 92,
      'ser_hpfilter' => 93,
      'ddate' => 94,
      'ser_dskhistory' => 95,
      'ser_dskshortcut_a' => 96,
      'interface_template' => 97,
      'ser_boxpos' => 98,
      'dialogsize' => 99,
      'state' => 100,
      'status' => 101,
      'disable_reason' => 102,
      'ser_listpriv' => 103,
      'mmailpserver' => 104,
      'webpserver' => 105,
      'dnspserver' => 106,
      'secdnspserver' => 107,
      'ttype' => 108,
      'username' => 110,
      'nameserver' => 111,
      'redirect_domain' => 112,
      'template_used' => 113,
      'realpass' => 114,
      'dtype' => 115,
      'subdomain_parent' => 116,
      'resourceplan_used' => 117,
      'previewdomain' => 118,
    ),
    'domaindefault' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'remove_processed_stats' => 3,
    ),
    'web' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_totaldisk_usage' => 3,
      'used_q_totaldisk_usage' => 4,
      'priv_q_ssl_flag' => 5,
      'used_q_ssl_flag' => 6,
      'priv_q_rubyfcgiprocess_num' => 7,
      'used_q_rubyfcgiprocess_num' => 8,
      'priv_q_disk_usage' => 9,
      'used_q_disk_usage' => 10,
      'priv_q_logo_manage_flag' => 11,
      'used_q_logo_manage_flag' => 12,
      'priv_q_ftpuser_num' => 13,
      'used_q_ftpuser_num' => 14,
      'priv_q_frontpage_flag' => 15,
      'used_q_frontpage_flag' => 16,
      'priv_q_php_manage_flag' => 17,
      'used_q_php_manage_flag' => 18,
      'priv_q_inc_flag' => 19,
      'used_q_inc_flag' => 20,
      'priv_q_awstats_flag' => 21,
      'used_q_awstats_flag' => 22,
      'priv_q_easyinstaller_flag' => 23,
      'used_q_easyinstaller_flag' => 24,
      'priv_q_modperl_flag' => 25,
      'used_q_modperl_flag' => 26,
      'priv_q_cgi_flag' => 27,
      'used_q_cgi_flag' => 28,
      'priv_q_php_flag' => 29,
      'used_q_php_flag' => 30,
      'priv_q_phpunsafe_flag' => 31,
      'used_q_phpunsafe_flag' => 32,
      'priv_q_subweb_a_num' => 33,
      'used_q_subweb_a_num' => 34,
      'priv_q_dotnet_flag' => 35,
      'used_q_dotnet_flag' => 36,
      'priv_q_cron_num' => 37,
      'used_q_cron_num' => 38,
      'priv_q_cron_minute_flag' => 39,
      'used_q_cron_minute_flag' => 40,
      'priv_q_cron_manage_flag' => 41,
      'used_q_cron_manage_flag' => 42,
      'priv_q_phpfcgi_flag' => 43,
      'used_q_phpfcgi_flag' => 44,
      'priv_q_rubyrails_num' => 45,
      'used_q_rubyrails_num' => 46,
      'priv_q_phpfcgiprocess_num' => 47,
      'used_q_phpfcgiprocess_num' => 48,
      'status' => 49,
      'iisid' => 50,
      'ser_server_alias_a' => 51,
      'ser_subweb_a' => 52,
      'ser_redirect_a' => 53,
      'stats_username' => 54,
      'stats_password' => 55,
      'ttype' => 56,
      'username' => 57,
      'password' => 58,
      'ipaddress' => 59,
      'ser_webmisc_b' => 60,
      'redirect_domain' => 61,
      'text_extra_tag' => 62,
      'ser_customerror_b' => 63,
      'frontpage_flag' => 64,
      'syncserver' => 65,
      'cron_mailto' => 66,
      'ser_aspnetconf_b' => 67,
      'ser_webindexdir_a' => 68,
      'webmail_url' => 69,
      'text_lighty_rewrite' => 70,
      'ftpusername' => 71,
      'hotlink_flag' => 72,
      'text_hotlink_allowed' => 73,
      'hotlink_redirect' => 74,
      'remove_processed_stats' => 75,
      'ser_indexfile_list' => 76,
      'fcgi_children' => 77,
      'customer_name' => 78,
      'text_blockip' => 79,
      'docroot' => 80,
      'force_www_redirect' => 81,
      'oldsyncserver' => 82,
      'olddeleteflag' => 83,
    ),
    'webmimetype' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'syncserver' => 3,
      'mimehandler' => 4,
      'extension' => 5,
      'oldsyncserver' => 6,
      'olddeleteflag' => 7,
    ),
    'webhandler' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'syncserver' => 3,
      'mimehandler' => 4,
      'extension' => 5,
      'oldsyncserver' => 6,
      'olddeleteflag' => 7,
    ),
    'rubyrails' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_rubyfcgiprocess_num' => 3,
      'used_q_rubyfcgiprocess_num' => 4,
      'appname' => 5,
      'port' => 6,
      'syncserver' => 7,
      'accessible_directly' => 8,
      'oldsyncserver' => 9,
      'olddeleteflag' => 10,
    ),
    'mmail' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_logo_manage_flag' => 3,
      'used_q_logo_manage_flag' => 4,
      'priv_q_maildisk_usage' => 5,
      'used_q_maildisk_usage' => 6,
      'priv_q_autoresponder_num' => 7,
      'used_q_autoresponder_num' => 8,
      'priv_q_mailaccount_num' => 9,
      'used_q_mailaccount_num' => 10,
      'priv_q_mailinglist_num' => 11,
      'used_q_mailinglist_num' => 12,
      'webmailprog' => 13,
      'catchall' => 14,
      'remotelocalflag' => 15,
      'catchall_status' => 16,
      'username' => 17,
      'status' => 18,
      'redirect_address' => 19,
      'syncserver' => 20,
      'ttype' => 21,
      'redirect_domain' => 22,
      'webmail_url' => 24,
      'systemuser' => 25,
      'enable_spf_flag' => 26,
      'exclude_all' => 27,
      'text_spf_domain' => 28,
      'text_spf_ip' => 29,
      'oldsyncserver' => 30,
      'olddeleteflag' => 31,
    ),
    'mailforward' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'accountname' => 3,
      'forwardaddress' => 4,
      'syncserver' => 5,
      'oldsyncserver' => 6,
      'olddeleteflag' => 7,
    ),
    'mailaccount' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_logo_manage_flag' => 3,
      'used_q_logo_manage_flag' => 4,
      'priv_q_maildisk_usage' => 5,
      'used_q_maildisk_usage' => 6,
      'priv_q_autoresponder_num' => 7,
      'used_q_autoresponder_num' => 8,
      'realname' => 9,
      'add_address' => 10,
      'add_city' => 11,
      'add_country' => 12,
      'add_telephone' => 13,
      'add_fax' => 14,
      'password' => 15,
      'cpstatus' => 16,
      'demo_status' => 17,
      'contactemail' => 18,
      'text_comment' => 19,
      'disable_per' => 20,
      'ser_hpfilter' => 21,
      'ddate' => 22,
      'ser_dskhistory' => 23,
      'ser_dskshortcut_a' => 24,
      'interface_template' => 25,
      'ser_boxpos' => 26,
      'dialogsize' => 27,
      'state' => 28,
      'status' => 29,
      'disable_reason' => 30,
      'realpass' => 31,
      'syncserver' => 32,
      'forward_status' => 33,
      'ser_forward_a' => 34,
      'autorespond_status' => 35,
      'autores_name' => 36,
      'filter_spam_status' => 37,
      'no_local_copy' => 38,
      'oldsyncserver' => 39,
      'olddeleteflag' => 40,
    ),
    'mailfilter' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'rule' => 3,
      'action' => 4,
    ),
    'reversedns' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'reversename' => 3,
    ),
    'aspnet' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'version' => 3,
      'syncserver' => 4,
      'session_timeout' => 5,
      'ser_globalization_b' => 6,
      'ser_aspnetmisc_b' => 7,
      'oldsyncserver' => 8,
      'olddeleteflag' => 9,
    ),
    'autoresponder' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'status' => 3,
      'send_rule' => 4,
      'reply_subject' => 5,
      'text_message' => 6,
      'autores_name' => 7,
    ),
    'mailinglist' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'syncserver' => 3,
      'listname' => 4,
      'adminemail' => 5,
      'lang' => 6,
      'post_members_only_flag' => 7,
      'post_moderated_flag' => 8,
      'post_moderator_only_flag' => 9,
      'archived_flag' => 10,
      'archive_blocked_flag' => 11,
      'archive_guarded_flag' => 12,
      'digest_flag' => 13,
      'jumpoff_flag' => 14,
      'subscriberlist_flag' => 15,
      'remote_admin_flag' => 16,
      'subscription_mod_flag' => 17,
      'edit_text_flag' => 18,
      'coma_mailinglist_mod_a' => 19,
      'text_trailer' => 20,
      'text_prefix' => 21,
      'max_msg_size' => 22,
      'min_msg_size' => 23,
      'text_mimeremove' => 24,
      'oldsyncserver' => 25,
      'olddeleteflag' => 26,
    ),
    'spam' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'status' => 3,
      'spam_hit' => 4,
      'subject_tag' => 5,
      'ser_wlist_a' => 6,
      'ser_blist_a' => 7,
      'syncserver' => 8,
      'oldsyncserver' => 9,
      'olddeleteflag' => 10,
    ),
    'lxbackup' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_backupschedule_flag' => 3,
      'used_q_backupschedule_flag' => 4,
      'ftp_server' => 5,
      'ssh_server' => 6,
      'rm_username' => 7,
      'rm_password' => 8,
      'rm_directory' => 9,
      'upload_type' => 10,
      'send_email' => 11,
      'upload_to_ftp' => 12,
      'backupstage' => 13,
      'backuptype' => 14,
      'backupschedule_type' => 15,
      'rm_last_number' => 16,
      'ser_lxbackupmisc_b' => 17,
      'restorestage' => 18,
      'no_local_copy_flag' => 19,
    ),
    'installsoft' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'appname' => 3,
      'ddate' => 4,
      'dbprefix' => 5,
      'dbname' => 6,
      'installdir' => 7,
      'version' => 8,
      'dbhost' => 9,
      'realhost' => 10,
      'ser_installsoftmisc_b' => 11,
      'syncserver' => 12,
      'oldsyncserver' => 13,
      'olddeleteflag' => 14,
    ),
    'mimetype' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'domainname' => 3,
      'type' => 4,
      'extension' => 5,
    ),
    'uuser' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_disk_usage' => 3,
      'used_q_disk_usage' => 4,
      'priv_q_logo_manage_flag' => 5,
      'used_q_logo_manage_flag' => 6,
      'realname' => 7,
      'add_address' => 8,
      'add_city' => 9,
      'add_country' => 10,
      'add_telephone' => 11,
      'add_fax' => 12,
      'password' => 13,
      'cpstatus' => 14,
      'demo_status' => 15,
      'contactemail' => 16,
      'text_comment' => 17,
      'disable_per' => 18,
      'ser_hpfilter' => 19,
      'ddate' => 20,
      'ser_dskhistory' => 21,
      'ser_dskshortcut_a' => 22,
      'interface_template' => 23,
      'ser_boxpos' => 24,
      'dialogsize' => 25,
      'realpass' => 26,
      'shellflag' => 27,
      'shell' => 28,
      'syncserver' => 29,
      'status' => 30,
      'oldsyncserver' => 31,
      'olddeleteflag' => 32,
    ),
    'ftpuser' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_logo_manage_flag' => 3,
      'used_q_logo_manage_flag' => 4,
      'realname' => 5,
      'add_address' => 6,
      'add_city' => 7,
      'add_country' => 8,
      'add_telephone' => 9,
      'add_fax' => 10,
      'password' => 11,
      'cpstatus' => 12,
      'demo_status' => 13,
      'contactemail' => 14,
      'text_comment' => 15,
      'disable_per' => 16,
      'ser_hpfilter' => 17,
      'ddate' => 18,
      'ser_dskhistory' => 19,
      'ser_dskshortcut_a' => 20,
      'interface_template' => 21,
      'ser_boxpos' => 22,
      'dialogsize' => 23,
      'state' => 24,
      'status' => 25,
      'disable_reason' => 26,
      'realpass' => 27,
      'username' => 28,
      'directory' => 29,
      'syncserver' => 30,
      'ftp_disk_usage' => 31,
      'oldsyncserver' => 32,
      'olddeleteflag' => 33,
    ),
    'davuser' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'realname' => 3,
      'add_address' => 4,
      'add_city' => 5,
      'add_country' => 6,
      'add_telephone' => 7,
      'add_fax' => 8,
      'password' => 9,
      'cpstatus' => 10,
      'demo_status' => 11,
      'contactemail' => 12,
      'text_comment' => 13,
      'disable_per' => 14,
      'ser_hpfilter' => 15,
      'ddate' => 16,
      'ser_dskhistory' => 17,
      'ser_dskshortcut_a' => 18,
      'interface_template' => 19,
      'ser_boxpos' => 20,
      'dialogsize' => 21,
      'state' => 22,
      'status' => 23,
      'disable_reason' => 24,
      'realpass' => 25,
      'username' => 26,
      'directory' => 27,
      'syncserver' => 28,
      'oldsyncserver' => 29,
      'olddeleteflag' => 30,
    ),
    'mysqldb' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_mysqldb_usage' => 3,
      'used_q_mysqldb_usage' => 4,
      'primarydb' => 5,
      'username' => 6,
      'dbname' => 7,
      'dbtype' => 8,
      'dbpassword' => 9,
      'installsoft_flag' => 10,
      'installsoft_app' => 11,
      'syncserver' => 12,
      'password' => 13,
      'no_backup_flag' => 14,
      'oldsyncserver' => 15,
      'olddeleteflag' => 16,
    ),
    'mysqldbuser' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'username' => 3,
      'dbname' => 4,
      'dbpassword' => 5,
      'ser_dbpermission_b' => 6,
      'syncserver' => 7,
      'ser_dbhostlist_a' => 8,
      'password' => 9,
      'oldsyncserver' => 10,
      'olddeleteflag' => 11,
    ),
    'mssqldb' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_mssqldb_usage' => 3,
      'used_q_mssqldb_usage' => 4,
      'username' => 5,
      'dbname' => 6,
      'dbtype' => 7,
      'dbpassword' => 8,
      'installsoft_flag' => 9,
      'installsoft_app' => 10,
      'syncserver' => 11,
      'password' => 12,
      'oldsyncserver' => 13,
      'olddeleteflag' => 14,
    ),
    'mssqldbuser' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'username' => 3,
      'dbname' => 4,
      'dbpassword' => 5,
      'ser_dbpermission_b' => 6,
      'syncserver' => 7,
      'ser_dbhostlist_a' => 8,
      'password' => 9,
      'oldsyncserver' => 10,
      'olddeleteflag' => 11,
    ),
    'ipaddress' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'devname' => 3,
      'bproto' => 4,
      'ipaddr' => 5,
      'client_num' => 6,
      'shared' => 7,
      'netmask' => 8,
      'status' => 9,
      'userctl' => 10,
      'peerdns' => 11,
      'gateway' => 12,
      'itype' => 13,
      'ipv6init' => 14,
      'syncserver' => 15,
      'clientname' => 16,
      'oldsyncserver' => 17,
      'olddeleteflag' => 18,
    ),
    'domainipaddress' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'domain' => 3,
      'ipaddr' => 4,
      'syncserver' => 5,
      'oldsyncserver' => 6,
      'olddeleteflag' => 7,
    ),
    'sslipaddress' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'devname' => 3,
      'ipaddr' => 4,
      'sslclient' => 5,
      'ssldomain' => 6,
      'sslcert' => 7,
      'syncserver' => 8,
      'oldsyncserver' => 9,
      'olddeleteflag' => 10,
    ),
    'anonftpipaddress' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'status' => 3,
      'syncserver' => 4,
      'ipaddr' => 5,
      'message' => 6,
      'anondomain' => 7,
      'ser_anonftpmisc_b' => 8,
      'disk_limit' => 9,
      'connection_limit' => 10,
      'download_limit' => 11,
      'oldsyncserver' => 12,
      'olddeleteflag' => 13,
    ),
    'serverftp' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'maxclient' => 3,
      'highport' => 4,
      'lowport' => 5,
      'enable_anon_ftp' => 6,
    ),
    'odbc' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'odbcname' => 3,
      'description' => 4,
      'driver' => 5,
      'ser_odbcdetails_b' => 6,
      'syncserver' => 7,
      'oldsyncserver' => 8,
      'olddeleteflag' => 9,
    ),
    'service' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'servicename' => 3,
      'description' => 4,
      'grepstring' => 5,
      'syncserver' => 6,
      'oldsyncserver' => 7,
      'olddeleteflag' => 8,
    ),
    'llog' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'syncserver' => 3,
      'email' => 4,
      'period' => 5,
      'oldsyncserver' => 6,
      'olddeleteflag' => 7,
    ),
    'pserver' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'priv_q_logo_manage_flag' => 3,
      'used_q_logo_manage_flag' => 4,
      'realname' => 5,
      'add_address' => 6,
      'add_city' => 7,
      'add_country' => 8,
      'add_telephone' => 9,
      'add_fax' => 10,
      'password' => 11,
      'cpstatus' => 12,
      'demo_status' => 13,
      'contactemail' => 14,
      'text_comment' => 15,
      'disable_per' => 16,
      'ser_hpfilter' => 17,
      'ddate' => 18,
      'ser_dskhistory' => 19,
      'ser_dskshortcut_a' => 20,
      'interface_template' => 21,
      'ser_boxpos' => 22,
      'dialogsize' => 23,
      'ostype' => 24,
      'osversion' => 25,
      'dbadmin' => 26,
      'dbpassword' => 27,
      'realpass' => 28,
      'username' => 29,
      'ser_rolelist' => 30,
      'cron_mailto' => 31,
      'syncserver' => 32,
      'ser_pserverconf_b' => 33,
      'hostname' => 34,
      'description' => 35,
      'realhostname' => 36,
      'timezone' => 37,
      'coma_psrole_a' => 38,
      'load_threshold' => 39,
      'oldsyncserver' => 40,
      'olddeleteflag' => 41,
    ),
    'phpini' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'php_manage_flag' => 3,
      'enable_zend_flag' => 4,
      'enable_ioncube_flag' => 5,
      'register_global_flag' => 6,
      'syncserver' => 7,
      'display_error_flag' => 8,
      'ser_phpini_flag_b' => 9,
      'oldsyncserver' => 10,
      'olddeleteflag' => 11,
    ),
    'driver' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_driver_b' => 3,
    ),
    'component' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'componentname' => 3,
      'syncserver' => 4,
      'oldsyncserver' => 5,
      'olddeleteflag' => 6,
    ),
    'servermail' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'smtp_instance' => 3,
      'enable_maps' => 4,
      'domainkey_flag' => 5,
      'additional_smtp_port' => 6,
      'queuelifetime' => 7,
      'concurrencyremote' => 8,
      'spamdyke_flag' => 9,
      'syncserver' => 10,
      'myname' => 11,
      'virus_scan_flag' => 12,
      'max_size' => 13,
      'greet_delay' => 14,
      'graylist_flag' => 15,
      'coma_mail_graylist_wlist_a' => 16,
      'oldsyncserver' => 17,
      'olddeleteflag' => 18,
    ),
    'serverspam' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'status' => 3,
      'spam_hit' => 4,
      'subject_tag' => 5,
      'ser_wlist_a' => 6,
      'ser_blist_a' => 7,
      'syncserver' => 8,
      'oldsyncserver' => 9,
      'olddeleteflag' => 10,
    ),
    'cron' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'syncserver' => 3,
      'email' => 4,
      'ser_minute' => 5,
      'ser_hour' => 6,
      'ser_ddate' => 7,
      'ser_month' => 8,
      'ser_weekday' => 9,
      'jobid' => 10,
      'username' => 11,
      'command' => 12,
      'argument' => 13,
      'ttype' => 14,
      'simple_cron' => 15,
      'cron_day_hour' => 16,
      'oldsyncserver' => 17,
      'olddeleteflag' => 18,
    ),
    'hostdeny' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'syncserver' => 3,
      'hostname' => 4,
      'oldsyncserver' => 5,
      'olddeleteflag' => 6,
    ),
    'dbadmin' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'dbtype' => 3,
      'dbadmin_name' => 4,
      'dbpassword' => 5,
      'syncserver' => 6,
      'oldsyncserver' => 7,
      'olddeleteflag' => 8,
    ),
    'firewall' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'status' => 3,
      'id' => 4,
      'syncserver' => 5,
      'from_address' => 6,
      'from_port' => 7,
      'to_address' => 8,
      'to_port' => 9,
      'action' => 10,
      'oldsyncserver' => 11,
      'olddeleteflag' => 12,
    ),
    'proxy' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
    ),
    'proxyacl' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'syncserver' => 3,
      'status' => 4,
      'ttype' => 5,
      'classid' => 6,
      'description' => 7,
      'password' => 8,
      'http' => 9,
      'ftp' => 10,
      'oldsyncserver' => 11,
      'olddeleteflag' => 12,
    ),
    'genlist' => 
    array (
      'nname' => 0,
      'parent_clname' => 1,
      'parent_cmlist' => 2,
      'ser_dirindexlist_a' => 3,
    ),
  ),
);