#!/bin/sh

#LOGSIZE=`cat /var/qmail/control/logsize`
#LOGCOUNT=`cat /var/qmail/control/logcount`

#exec /usr/bin/setuidgid qmaill \
#	/usr/bin/multilog t s$LOGSIZE n$LOGCOUNT /var/log/qmail/authlib 2>&1

exec /usr/bin/setuidgid qmaill \
	/var/qmail/bin/splogger authlib 2>&1
