#!/bin/sh

#CALLER=$(ps ax | grep "^ *$PPID" | awk '{print $NF}' | grep '/usr/local/lxlabs/kloxo')
CALLER=$(ps -ocommand= -p $PPID | grep '/usr/local/lxlabs/kloxo')

if [ "$CALLER" == "" ] ; then
	echo "- No permit calling from outside '/usr/local/lxlabs/kloxo'"
	exit
fi

$@